### ISSUE TITLE
Quotes not allowed

### ISSUE THREAD

**Issue by spencerkittleson** [simpleidserver/SimpleIdServer#10]
https://github.com/simpleidserver/SimpleIdServer/blob/4c7a76d56a677cf3fd7b5e95d967a800f2f1337c/tests/SimpleIdServer.Scim.Tests/FilterFixture.cs#L16

According to the rfc7643 spec, this should be allowed: `userName eq "jsmith"`.

**Comment by simpleidserver** [comment]
Thanks you for your remarks, the issue has been moved to the next release.

**Comment by simpleidserver** [comment]
The bug is fixed in branch **release/1.0.4**
