### ISSUE TITLE
EF core performance issue

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#101]
Hello,

I have a problem with performance using EF core middleware:

![image](https://user-images.githubusercontent.com/10979448/108821220-8f659500-75bd-11eb-81d6-38d610c53431.png)

I tried to upgrade the EF core version to the latest one (5.0.3)
![image](https://user-images.githubusercontent.com/10979448/108821438-e2d7e300-75bd-11eb-8ce9-bbc5c1594017.png)

much better :-)

Do you plan to upgrade EF core version?

**Comment by simpleidserver** [comment]
Hello,

First thank you for you feedback. I'm going to upgrade EFCore to the latest version and include this change in the release 1.2.0.

I'm also going to a a look in EFCore, trying to understand why there is such performance diff between both versions :).

**Comment by steppo83** [comment]
Just so you know: @gabrielemilan also saw that if we use the sw instead of the eq in the filter, the timeout is drastically better. There is something wrong with the "equal" that doesn't occur with the "starts with" using the 2.2 version of ef core.

**Comment by steppo83** [comment]
For you to know, @gabrielemilan also found that if you use the sw instead of the eq in the filter, the timeout surprisingly decrease.
Hope this help :)

**Comment by simpleidserver** [comment]
The migration to DOTNET5.0 is in progress, a new release will be published in 2/3 days.

**Comment by simpleidserver** [comment]
The version 1.2.0 is released ! In this new version, SimpleIdServer is using the latest version of EFCore.
