### ISSUE TITLE
Support emails value filtering without value property

### ISSUE THREAD

**Issue by spencerkittleson** [simpleidserver/SimpleIdServer#11]
Currently filtering by user emails without property doesn't work. It be appended with `.value` to work properly.

See: https://tools.ietf.org/html/rfc7644#section-3.4.4.2
RFC Example: `userType eq "Employee" and (emails co "example.com" or  emails.value co "example.org")`

Or simply: `emails co \"example.com\"`

Tests found here:
https://github.com/simpleidserver/SimpleIdServer/blob/0d5ca547ae449d531d77f4f7f852ebe2216747a9/tests/SimpleIdServer.Scim.Tests/FilterFixture.cs#L12

**Comment by simpleidserver** [comment]
The issue has been moved to the next release

**Comment by simpleidserver** [comment]
The ticket is fixed in branch **release/1.0.4**
