### ISSUE TITLE
Server error adding members to a group (SQL)

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#114]
Hello,

Using sql middleware, I get this error adding a member to a group:

![image](https://user-images.githubusercontent.com/10979448/110829035-fa8ab900-8297-11eb-8b58-58419f7955e0.png)

Regards,
Gabriele

**Comment by simpleidserver** [comment]
The issue is fixed in the branch "release/1.2.1".
