### ISSUE TITLE
Empty array on complex type

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#116]
Hello, is it possible to have the property exposed as an empty array?

If the user has no group, now the payload has no group property.

Is it possible to have this?

> {
            "id": "0b2f3621-2e84-4419-9544-6c154032f378",
            "schemas": [
                "urn:ietf:params:scim:schemas:core:2.0:User"
            ],
            "meta": {
                "resourceType": "User",
                "created": "2021-02-04T16:02:26.4914617",
                "lastModified": "2021-02-04T16:02:26.4914621",
                "version": "45c27241-efe3-4690-8aca-91395bb6ff0c",
                "location": "https://travel.stg.fame.infra.uefa.com/Scim.Api/v2/Users/0b2f3621-2e84-4419-9544-6c154032f378"
            },
            "active": true,
            "displayName": "Amanda Debra Riseman",
            "userName": "arim@uefastaging.ch",
            **"groups": []**
}

I mean with an empty array in **groups**

**Comment by simpleidserver** [comment]
Hello,

Sorry for the delayed response, I was working on the project "NewsAggregator" : https://github.com/simpleidserver/NewsAggregator. I'm going to include the changes tomorrow & do a release next week :).

**Comment by simpleidserver** [comment]
The issue is now fixed in the branch "1.2.1". If everything is okay for you, I will publish a release next week.

**Comment by gabrielemilan** [comment]
Hello @simpleidserver , thanks for the change.

It seems working properly on groups in get users.

We have the same issue on members, getting group.

Can you check also this part?

Thanks a lot

**Comment by simpleidserver** [comment]
Hello,

Both issues should be fixed in the branch "release/1.2.1".
