### ISSUE TITLE
Members uniqueness in group

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#117]
Hello, 

I'm trying to avoid adding same member to the members list in group. I tried to set Uniqueness property to true in the schema, but the api allows to add same value to members array.

![image](https://user-images.githubusercontent.com/10979448/113861250-494c4580-97a7-11eb-86b1-5879e7651707.png)

Thanks.
Gabriele

**Comment by simpleidserver** [comment]
Hello,

The issue should be fixed in the branch "release/1.2.1".

If the target location already contains the value specified, there are no changes to the resource and a success response is returned.
