### ISSUE TITLE
SQL performace issue in get users

### ISSUE THREAD

**Issue by gianlucamasento** [simpleidserver/SimpleIdServer#118]
Hello,
I am trying to call the GET Users endpoint without any parameters and I have a timeout exceptions. I have a SQL database with around 1000 users and 30 groups
![image](https://user-images.githubusercontent.com/82225307/114200718-c3bac800-9955-11eb-98d0-64aa6abb9ef7.png)

I got a result with 10 records pagination, but it is very slow, 40 seconds
![image](https://user-images.githubusercontent.com/82225307/114200261-5018bb00-9955-11eb-9dc8-133621e4f461.png)

The query that cause the timeout:
[timeouQuery.txt](https://github.com/simpleidserver/SimpleIdServer/files/6286680/timeouQuery.txt)
The timeout postman response:
[timeoutResponse.txt](https://github.com/simpleidserver/SimpleIdServer/files/6286693/timeoutResponse.txt)

Thanks!
Gianluca

**Comment by simpleidserver** [comment]
Hello,

I'm going to take a look to your issue next week.

KR,

SimpleIdServer

**Comment by Mysonemo** [comment]
> Hello,
> 
> I'm going to take a look to your issue next week.
> 
> KR,
> 
> SimpleIdServer

Thank you because i have the same issue.

BR

**Comment by simpleidserver** [comment]
Hello,

The issue should be fixed in the branch "release 1.2.1".

**Comment by simpleidserver** [comment]
Hello,

Did-you test the changes made in the branch "release/1.2.1" ?

**Comment by gianlucamasento** [comment]
Hi, yes I tested it, now the users endpoint is fast, but I found a regression in pagination :(
I have a db with around 1800 users and for a request like:
/Users?startIndex=150
I get each time different result in the response

**Comment by simpleidserver** [comment]
Ty for your feedback :)
I'm going to take a look

**Comment by simpleidserver** [comment]
The modifications didn't impact the pagination. I checked the pagination in the "/Users" endpoint & the same result is always returned for the following requests :
=> HTTP GET : /Users?startIndex=150
=> HTTP GET : /Users?startIndex=2
=> HTTP GET : /Users?startIndex=2&filter=userName sw sid

I checked the SQL instruction and an "Order BY" is executed on the column "dbo.SCIMRepresentationLst.Id".

**Comment by gianlucamasento** [comment]
Hi,
the query that cause the issue is generated by this code:
src\Scim\SimpleIdServer.Scim.Persistence.EF\EFSCIMRepresentationQueryRepository.cs
result = queryableRepresentations.Skip(parameter.StartIndex).Take(parameter.Count).ToList().Select(s => s.ToDomain());
[wrongQuery.txt](https://github.com/simpleidserver/SimpleIdServer/files/6316750/wrongQuery.txt)
The instruction "ORDER BY (SELECT 1)" when the offset is applyed generate different result at each execution(I have a DB with 1000 users)

I fixed it by adding an orderby
result = queryableRepresentations.OrderBy(a => a.Id).Skip(parameter.StartIndex).Take(parameter.Count).ToList().Select(s => s.ToDomain());
[rightQuery.txt](https://github.com/simpleidserver/SimpleIdServer/files/6316771/rightQuery.txt)
With this fix the instruction "ORDER BY (SELECT 1)" has been replaced by "ORDER BY [s].[Id]" and in this case query execution return always the same recordset and so the pagination works fine.

Could be a proper fix? Can you apply it?

Thanks
Gianluca

**Comment by simpleidserver** [comment]
Hello,

Your solution seems to be correct. I made some modifications in the branch "release/1.2.1" to fix the pagination.

**Comment by gianlucamasento** [comment]
Hello,
thanks for the fix.
I found a small issue in the get user endpoint: the "display" property inside the group array is always null
![image](https://user-images.githubusercontent.com/82225307/115061875-fb8fb580-9ee9-11eb-9337-8f5115d3acf5.png)


Thanks
Gianluca

**Comment by simpleidserver** [comment]
Hello,

In order to improve the SQL query performance, a new column "DisplayName" has been added in the table "SCIMRepresentationLst". A list of empty "display" property is returned by the SCIM API because the column "DisplayName" doesn't contain any value.

An SQL migration script is attached, it can be executed to update the DisplayName column : 
[migrationScript.txt](https://github.com/simpleidserver/SimpleIdServer/files/6334447/migrationScript.txt)

Kind regards,

SimpleIdServer

**Comment by gianlucamasento** [comment]
Hi,
thanks for the data rollout script, after run it I can see the display property in the groups array in the user.

But if I add a user inside a group with a group patch /Groups/057846eb-ec73-44f6-b948-34c7b4401c88
{
    "schemas":  
       ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
         "Operations":
       [ 
         {
       "op":"add", 
         "path": "members", 
         "value":[
          {
            "value": "00147b93-04cb-4d00-8d05-3b5e9f7649d2" 
          } 
         ]
         } 
       ]  
}

The get user continue to show null in the display property of the group just updated:
![image](https://user-images.githubusercontent.com/82225307/115264541-ad232680-a136-11eb-8550-e7ac229d4157.png)


Thanks
Regards
Gianluca

**Comment by simpleidserver** [comment]
Hello,

The issue is fixed for the HTTP PATCH & HTTP PUT request.

Kind regards,

SimpleIdServer

**Comment by gianlucamasento** [comment]
Many thanks!
It is working fine!

Regards
Gianlu
