### ISSUE TITLE
Filter type treated as incorrect SCIMExpression type

### ISSUE THREAD

**Issue by spencerkittleson** [simpleidserver/SimpleIdServer#12]
Wrap parenthesis calls for filters should be a type according to RFC spec: https://tools.ietf.org/html/rfc7644#section-3.4.2.2

Example: `filter=(active eq true)` is treated as `SCIMAttributeExpression`.

I assume it should be treated as a `SCIMComplexAttributeExpression`.

**Comment by spencerkittleson** [comment]
I put together a simple fix but not likely the best way to handle it.

**Comment by simpleidserver** [comment]
Indeed, I discovered that there is an issue with the parsing method, when parentheses are present in the filter. 
Before the fix : the filter was considered as a SCIMAttributeExpression.
After the fix : the filter must be treated as a SCIMComparisonExpression.

The issue will be resolved with the ticket #11.

Note : Expression with square brackets is treated as a SCIMComplexAttributeExpression.

**Comment by simpleidserver** [comment]
The bug is fixed in branch **release/1.0.4**
