### ISSUE TITLE
Will simpleIdServer get openID connect certified?

### ISSUE THREAD

**Issue by aphuang2013** [simpleidserver/SimpleIdServer#120]
It seems to me that simpleIdServer came from simpleIdentityServer which was certified.  The current openID connect URL for simpleIdentityServer is no longer valid.   Can that be fixed?

**Comment by simpleidserver** [comment]
Hello,

Indeed SimpleIdServer is coming from the project "SimpleIdentityServer". 
We are going to pass the OPENID certifications, when the FAPI endpoint will be developed.

**Comment by luismdelgado** [comment]
Hi, do you have an estimate of when do you expect to complete the pending development and finalize the certification process? Thanks!

**Comment by simpleidserver** [comment]
Hello,
The development is finished & the changes are deployed in azure.
We are passing all the OPENID certifications & we will try to submit the project next week (probably next friday 30 april)

**Comment by simpleidserver** [comment]
Hello,

The fees to pass OPENID certifications are now quite expensive https://openid.net/certification/fees/ :(
Even if SimpleIdServer doesn't have official OpenID certifications, most of the test plans have been executed against the version 1.2.1. 

OpenID certifications are listed in the README file :
* OpenIdProvider (basic op, implicit op etc ...)
* OpenIdProvider for logout profile (RP initiated, session op etc...)
* FAPI OpenId Providers : FAPI MTLS, FAPI Private key.
* FAPI CIBA : Poll MTLS, Poll Private key, Ping MLTS etc ...

**Comment by luismdelgado** [comment]
Hello,

I would like to know which fees are applicable to your situation. The page lists member and non-member fees. I'm mostly interested in the OIDC certification, not so much the FAPI, to have an idea of how much the cost would be. We are analyzing the options where I work, and management could consider paying for the certification if we decide SimpleIdServer is the best option for our needs.

**Comment by simpleidserver** [comment]
Hello,

I'm already a member of the OPENID foundation. The fees needed to pass the standard OIDC certification are equals to $700 USD insead of $3500 USD.

![Fees](https://user-images.githubusercontent.com/10213388/118375555-93a0bd80-b5c2-11eb-8af4-20c2efed7319.png)
