### ISSUE TITLE
Not compatible with .net core 3.1

### ISSUE THREAD

**Issue by granhal** [simpleidserver/SimpleIdServer#13]
Hello guys,

im trying to install lib in my project with .net core 3.1 and encounter errors with version compatibilities dependencies, i attach the error.

_System.MissingMethodException: 'Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions.AddAuthorization(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action`1<Microsoft.AspNetCore.Authorization.AuthorizationOptions>)'.'_

![image](https://user-images.githubusercontent.com/5773419/72428938-0ca1c200-378f-11ea-96f1-194ff62f5996.png)

**Comment by thabart** [comment]
Hello,

We are going to investigate the bug ASAP and publish a new release 1.0.4 if it's needed.

**Comment by simpleidserver** [comment]
The bug is fixed in version 1.0.4, please try again.

https://github.com/simpleidserver/SimpleIdServer/releases/tag/v1.0.4
