### ISSUE TITLE
SCIMRepresentationExtensions.ApplyPatches is not taking into account attributes from extensions

### ISSUE THREAD

**Issue by SviatoslavVilkovych** [simpleidserver/SimpleIdServer#138]
It seems that when you have extensions to the schema, attributes from that extension in not taken into account in this function, therefore patch on extensions attributes constantly failing.

https://github.com/simpleidserver/SimpleIdServer/blob/b6d1f76fb0af5d60821fc85ed83b21b9803c7e78/src/Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs#L48

**Comment by simpleidserver** [comment]
Hello,

Sorry for the delayed response. When you executed PATCH operation on the resource, did-you check if the extension schema was present in the HTTP create request ?
The following scenario is working for me :

1. Launch the project "SimpleIdServer.Scim.Startup"
2. Create a resource :

HTTP POST : http://localhost:60002/Users
{
	"schemas": [ "urn:ietf:params:scim:schemas:core:2.0:User", "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" ],
	"userName": "{{$guid}}",
	"externalId": "{{$guid}}",
	"employeeNumber": "number",
	"name":{
		"familyName":"azeaze",
		"givenName": "azeaze"
	}
}

3. Execute PATCH operation :

HTTP PATCH :  http://localhost:60002/Users/<<userid>>
{
	"schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
	"Operations": [{
		"op": "replace",
		"path": "employeeNumber",
		"value": "newEmployeeNumber"
	}]
}

The property "employeeNumber" is present in the schema "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" and can be updated via HTTP PATCH operation.

**Comment by SviatoslavVilkovych** [comment]
Yes, but actually correct path to this extension property should include schemaId. For example, here is *page 56* of [standard](https://datatracker.ietf.org/doc/html/rfc7644#section-3.7.2)
You can see that **employeeNumber** is not under **data**, but under **urn:ietf:params:scim:schemas:extension:enterprise:2.0:User**:
```
{
       "method": "POST",
       "path": "/Users",
       "bulkId": "ytrewq",
       "data": {
         "schemas": [
           "urn:ietf:params:scim:schemas:core:2.0:User",
           "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
         ],
         "userName": "Bob",
         "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
           "employeeNumber": "11250",
           "manager": {
             "value": "bulkId:qwerty"
           }
         }
       }
}
```

**Comment by simpleidserver** [comment]
Good remark !
I'm going to update the SCIM project to support "Full Qualified Name" properties

**Comment by simpleidserver** [comment]
The branch 1.2.2 has been updated & full qualified name can be used in request :)
Can-you please check if it's working for you?

**Comment by SviatoslavVilkovych** [comment]
Unfortunately, cannot update right now and check, but I believe it is working! Thanks!
