### ISSUE TITLE
Empty array of complex types aren't be mapped correctly

### ISSUE THREAD

**Issue by felipejorgeh** [simpleidserver/SimpleIdServer#142]
We create a simple user using POST: http://localhost:60002/Users​
Request:
_{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "externalId": "externalId14a4979b3984",
  "userName": "userName14a4979b3984",
  "name": {
    "formatted": "formatted14a4979b3984",
    "givenName": "givenName14a4979b3984",
    "middleName": "middleName14a4979b3984",
    "familyName": "familyName14a4979b3984"
  },
  "emails": [
    {
      "value": "value14a4979b3984",
      "display": "display14a4979b3984"
    }
  ]
}_

Response:
_{
  "id": "f716a55f-ffd2-4f44-bc35-68f7864bf172",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "meta": {
    "resourceType": "Users",
    "created": "2021-06-03T10:21:44.7514457Z",
    "lastModified": "2021-06-03T10:21:44.7515593Z",
    "version": "e5705eb7-c1e0-4b87-94fe-f774eb2fed78",
    "location": "http://localhost:60002/Users/f716a55f-ffd2-4f44-bc35-68f7864bf172"
  },
  "externalId": "externalId14a4979b3984",
  "userName": "userName14a4979b3984",
  "name": {
    "formatted": "formatted14a4979b3984",
    "givenName": "givenName14a4979b3984",
    "middleName": "middleName14a4979b3984",
    "familyName": "familyName14a4979b3984"
  },
  "emails": [
    {
      "value": "value14a4979b3984",
      "display": "display14a4979b3984"
    }
  ],
  "phoneNumbers": [],
  "ims": [],
  "photos": [],
  "addresses": [],
  "groups": [],
  "entitlements": [],
  "roles": [],
  "x509Certificates": []
}_

After, we want to modify the user using PUT ​http://localhost:60002/Users​/Users​/f716a55f-ffd2-4f44-bc35-68f7864bf172 and set an empty array of emails
Request:
_{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "externalId": "externalId14a4979b3984",
  "userName": "userName14a4979b3984",
  "name": {
    "formatted": "formatted14a4979b3984",
    "givenName": "givenName14a4979b3984",
    "middleName": "middleName14a4979b3984",
    "familyName": "familyName14a4979b3984"
  },
  "emails": []
}_

Response:
_{
  "id": "f716a55f-ffd2-4f44-bc35-68f7864bf172",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "meta": {
    "resourceType": "Users",
    "created": "2021-06-03T10:21:44.7514457Z",
    "lastModified": "2021-06-03T10:24:26.8721781Z",
    "version": "e5705eb7-c1e0-4b87-94fe-f774eb2fed78",
    "location": "http://localhost:60002/Users/f716a55f-ffd2-4f44-bc35-68f7864bf172"
  },
  "externalId": "externalId14a4979b3984",
  "emails": [
    {
      "value": "value14a4979b3984",
      "display": "display14a4979b3984"
    }
  ],
  "userName": "userName14a4979b3984",
  "name": {
    "formatted": "formatted14a4979b3984",
    "givenName": "givenName14a4979b3984",
    "middleName": "middleName14a4979b3984",
    "familyName": "familyName14a4979b3984"
  },
  "phoneNumbers": [],
  "ims": [],
  "photos": [],
  "addresses": [],
  "groups": [],
  "entitlements": [],
  "roles": [],
  "x509Certificates": []
}_

As we can see in the response, the emails weren't be updated correctly.

The empty array of complex types aren't be mapped correctly.

![imagen](https://user-images.githubusercontent.com/85287426/120630992-a8f16500-c467-11eb-93ee-4c8678d1465c.png)

**Comment by simpleidserver** [comment]
Indeed it's a bug, i'm working on it

**Comment by simpleidserver** [comment]
The issue should be fixed in the branch "release/1.2.2"
