### ISSUE TITLE
Common schema

### ISSUE THREAD

**Issue by slimjack** [simpleidserver/SimpleIdServer#16]
According to https://tools.ietf.org/html/rfc7643#section-3.1 common attributes (`id`, `externalId` and `meta`) should not have own schema. They should be implicitly defined for any resource type except "ServiceProviderConfig" and "ResourceType" schemas. But SimpleIdServer throws an exception if I try to post a user with `externalId` attribute and without `urn:ietf:params:scim:schemas:core:2.0:Common` in schema.
This leads to exception:
```
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "userName": "someusername",
    "name": {
        "familyName": "somefamilyname",
        "givenName": "somegivenname"
    },
    "emails": [
        {
            "primary": true,
            "value": "someuser@gmail.com"
        }
    ],
    "externalId": "someexternalid"
}
```
and this is ok
```
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:core:2.0:Common"
    ],
    "userName": "someusername",
    "name": {
        "familyName": "somefamilyname",
        "givenName": "somegivenname"
    },
    "emails": [
        {
            "primary": true,
            "value": "someuser@gmail.com"
        }
    ],
    "externalId": "someexternalid"
}
```

I think `urn:ietf:params:scim:schemas:core:2.0:Common` should not be required to be specified

**Comment by simpleidserver** [comment]
Indeed it's an error, the common schema should be removed from the project to respect the RFC7643.
The changes are already committed into the branch "release/v1.0.5".
