### ISSUE TITLE
ResourceTypes endpoints wrong definition - missing "s"

### ISSUE THREAD

**Issue by Mysonemo** [simpleidserver/SimpleIdServer#184]
Hello guys,
It look's with the last version 2.0.0 i can see a regression on /resourceTypes endpoint.
The endpoint should be User**s**, Group**s** and Entitlement**s** (with "**s**")
![image](https://user-images.githubusercontent.com/19433015/129362351-f6639f74-c277-47a4-9b02-b924bc614164.png)
![image](https://user-images.githubusercontent.com/19433015/129362456-5dde1824-a007-42ea-9674-08fe7299ba58.png)
![image](https://user-images.githubusercontent.com/19433015/129362519-a1b0820d-1e08-47da-8b02-9c56a9642978.png)

Thank you in advance for your help and for this really good api. ;)

**Comment by Mysonemo** [comment]
@thabart Just to add some details, it looks like a regression added in the 2.0.0

**Comment by simpleidserver** [comment]
Hello,

Can-you check if the following SCIM Schema : "User", "Group" and "Entitlement" contain a valid "ResourceType" property ?
The "endpoint" value is defined by the previous property (ResourceType). 
The User SCIM Schema should contains a ResourceType property equals to "v2/Users".

Kind regrads,

SimpleIdServer

**Comment by Mysonemo** [comment]
Sorry i didn't get what you mean. 
The only things that i can see is a wrong attribute in the /resourceTypes. The attribute endpoints is "pluralized" by RFC.
https://datatracker.ietf.org/doc/html/rfc7643#section-6

![image](https://user-images.githubusercontent.com/19433015/129574162-c3f4bbd0-d100-4c52-aaf2-baaa711145c1.png)

**Comment by simpleidserver** [comment]
**InMemory**: If you are using an **In Memory** implementation then the **ResourceType** property must be updated with the correct value :

` var userSchema = SCIMSchemaExtractor.Extract(Path.Combine(basePath, "UserSchema.json"), "v2/Users", true);`

**SQLServer** : If you are using the SQLServer implementation then the column "ResourceType" (from the table "dbo.SCIMSchemaLst") 
must be updated with the correct value "v2/Users".

The endpoint attribute value is equal to the ResourceType property coming from the SCIMSchema class.
The code source can be found here : https://github.com/simpleidserver/SimpleIdServer/blob/release/2.0.0/src/Scim/SimpleIdServer.Scim/Api/ResourceTypesController.cs#L45

**Comment by Mysonemo** [comment]
Thanks you for the details, but if the endpoint attribute value is equal to the ResourceType property, it's wrong. Because it shouldn't be equal as mention in the previous RFC. So the resourcetypes is "User" and the endpoints should be "Users".
line 45 is not right
{ SCIMConstants.ResourceTypeAttribute.Endpoint, $"/{schema.ResourceType}" },

**Comment by simpleidserver** [comment]
The issue should be fixed in the branch "release/2.0.0"
