### ISSUE TITLE
StartIndex shouldn't be start from 0

### ISSUE THREAD

**Issue by steppo83** [simpleidserver/SimpleIdServer#185]
Hi,
From the 2.0.0 version of the SCIM Api there is a regression on the startIndex that starts from 0 and not from 1.
On top of the above regression if we filter with startIndex with 0, 1 or 2 it starts from the same user or group.
Below some screenshots:
Starting from 0 (should start from 1)
![image](https://user-images.githubusercontent.com/19529745/129365289-9525856b-a50b-4e94-9d72-b27d472ad5f5.png)

Starting from 0, 1 or 2

From 0
![image](https://user-images.githubusercontent.com/19529745/129365289-9525856b-a50b-4e94-9d72-b27d472ad5f5.png)

From 1
![image](https://user-images.githubusercontent.com/19529745/129365438-68678fcc-edd2-449a-b772-787c333454f2.png)

From 2
![image](https://user-images.githubusercontent.com/19529745/129365472-e7ade977-6acf-49cb-ac75-eac97385d793.png)

Thanks a lot for you investigation.

Stefano

**Comment by Mysonemo** [comment]
it looks also that the totalResults is wrong because i can do a get /users?startIndex=(totalResults+1) and i get the last value.
So it appear that "totalResults": start from 0.

**Comment by simpleidserver** [comment]
Hello,

The issue should be fixed in the branch "release/2.0.0", can-you please check if it's working.

Kind regards,

SimpleIdServer

**Comment by Mysonemo** [comment]
looks fixed to me. Thanks

**Comment by steppo83** [comment]
Fixed, thanks
