### ISSUE TITLE
No meta attributes in the /schemas endpoint (user, groups and entitlements) - regression on version 2.0.0

### ISSUE THREAD

**Issue by francesco-scullino** [simpleidserver/SimpleIdServer#186]
Hello,
it seems the release 2.0.0 introduced a couple of regressions on /schemas endpoint

- meta attribute is missing on user, groups and entitilements entities. Below a comparison between responses from v1.2.2 and v2.0.0
![image](https://user-images.githubusercontent.com/1720798/129365257-f04eade5-48bc-4919-998e-d9f4abccb45f.png)

- meta object contains default values
![image](https://user-images.githubusercontent.com/1720798/129365821-fb864842-9281-470a-b9ec-b1a076dded44.png)

Thank you so much for your effort on this amazing library

**Comment by Mysonemo** [comment]
Yes i've got this one as well. 
So i cannot anymore do incremental aggregation in my identity management tool because the meta attributes are no more in the /schemas endpoint.

**Comment by simpleidserver** [comment]
Hello,

The issue should be fixed in the branch **release/2.0.0**.
