### ISSUE TITLE
Return a different amount of total results for consecutive calls on version 2.0.0

### ISSUE THREAD

**Issue by francesco-scullino** [simpleidserver/SimpleIdServer#187]
Hello guys,
the version 2.0.0 seems to have a bug calling many times the /users endpoint. The **totalResults** field in the response change continuously. Below you can find a video that show this behaviour.

https://user-images.githubusercontent.com/1720798/129371068-9f3004c6-93bf-4c2f-926e-35d1f2caeeed.mp4

**Comment by simpleidserver** [comment]
Hello,

Can-you please check if the issue is still present in the branch "release/2.0.0", some modifications have been made in order to fix the tickets #186 & #185.

Kind regards,

Thierry H.
