### ISSUE TITLE
SCIM MongoDb transaction issue

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#189]
Hello, I noticed an issue on transaction in mongodb.

According to the documentation (https://docs.mongodb.com/manual/core/transactions/), to use the transaction it needs to pass in the session to the methods. In the code the session is never passed in, so the transaction it doesn't work, I tried putong the breakpoint after delete operation and indeed the data has been deleted before the transaction commit.

**Comment by simpleidserver** [comment]
Hello,

I made some modifications in the branch "release/2.0.0" in order to fix MongoDB transaction.
The changes have been tested and are working against a MongoDB cluster.

**Comment by gabrielemilan** [comment]
It works now 👍
