### ISSUE TITLE
[SCIM] Filtering error

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#207]
Hello guys,

we have this error, when we put this filter on query string ?filter=organizationId eq "600074", the result of filteri object is wrong:

![image](https://user-images.githubusercontent.com/10979448/136949523-0762fd94-ccf8-4954-b9b2-e6896571621e.png)

The issue seems related to this function:

![image](https://user-images.githubusercontent.com/10979448/136949613-f8193663-eb45-41ca-9a2c-3e2ffe2fbfef.png)

Can you have a look?

Thanks

**Comment by simpleidserver** [comment]
The issue should be fixed in the branch "release/2.0.2".

**Comment by gabrielemilan** [comment]
It works, thanks :-)
