### ISSUE TITLE
Dynamic add claims before token is generated

### ISSUE THREAD

**Issue by jigneshnarain** [simpleidserver/SimpleIdServer#210]
Hi

Is there a way to inject a claim dynamically before the token is generated?

Example: 

1. ClientA (uses client credentials grant type to retrieve access token) invokes ServiceA.
2. ServiceA generates a unique ID.
3. ServiceA needs to generate an access token with the unique ID claim.
4. ClientA uses access token to invoke ServiceB.

Is there alternatively flow whereby the unique ID can used to generate access token (silent authentication)? The unique ID will need to accessible from the token.

**Comment by simpleidserver** [comment]
The release 2.0.2 is now available.

Kind regards,

SimpleIdServer
