### ISSUE TITLE
typo in SCIM naming.

### ISSUE THREAD

**Issue by bzuidgeest** [simpleidserver/SimpleIdServer#22]
Line 20 in StandardSCIMRepresentationAttributes has a value of "descriptions" I believe this should be "description" without an "s" add the end. Please correct me if I am wrong.

Also The description on the schema (schemas endpoint) takes the name from the schemabuilder and not the provided description. The resourceType endpoint does do this properly.

{

  "id": "urn:ietf:params:scim:schemas:extension:nleducation:1.0:eduuser",
  "name": "eduUser",
  "description**s**": "eduUser",
  "attributes": [
    {
      "name": "eckId",
      "type": "string",
      "multiValued": false,
      "description**s**": "The unique identification of the user for digital content",
      "required": true,
      "caseExact": false,
      "mutability": "immutable",
      "returned": "request",
      "uniqueness": "global"
    },

**Comment by bzuidgeest** [comment]
I believe the second problem is caused by line 20 SCIMSchemaextensions.cs

{ SCIMConstants.StandardSCIMRepresentationAttributes.Name,  schema.Name},
 { SCIMConstants.StandardSCIMRepresentationAttribute**s.Description,  schema.Name}**

**Comment by simpleidserver** [comment]
This issue will be fixed in the next release.

**Comment by bzuidgeest** [comment]
You fixed the first but not the second one in SCIMSchemaextensions or is "{ SCIMConstants.StandardSCIMRepresentationAttributes.Description, schema.Name}" correct? I believe not.
Thank you for all your quick responses.

**Comment by simpleidserver** [comment]
Indeed we didn't pay attention about your second remark.

We will fix it and update the acceptance test to cover all the properties of the schema.

**Comment by bzuidgeest** [comment]
Don't worry about it, your responses have been fast and excellent and fixes are applied. I Cannot ask for more in what is after al an freely available project.

**Comment by simpleidserver** [comment]
The error is fixed in the commit : "https://github.com/simpleidserver/SimpleIdServer/commit/3a29ea1167045e3d2dc17401d88b0981f03ecada"

**Comment by bzuidgeest** [comment]
There is a new typo in this commit En**ter**priseUser is spelled as En**tre**priseUser. This is simple typo. I make many myself

**Comment by simpleidserver** [comment]
The typo is fixed in the commit "https://github.com/simpleidserver/SimpleIdServer/commit/d1a42226cc80088193a8b2983bd9b726a1a8fcb9".
