### ISSUE TITLE
[SCIM] Enrich payload notification

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#222]
Hello guys,

is it possible add the resource changed in the payload of notification of "RepresentationReferenceAttributeAddedEvent"?

Now there are:

![image](https://user-images.githubusercontent.com/10979448/150751678-d9bb41de-f9a1-4da3-8c07-1d5b7cbc78e6.png)

is it possible to have somthing like:

![image](https://user-images.githubusercontent.com/10979448/150751913-822b1c63-65a3-4478-8e7e-ac4c0204b065.png)

So also the resource that has been changed.

Thanks.
Gabriele

**Comment by simpleidserver** [comment]
Hello,

I'm going to update the SCIM project in order to add the `Source Representation` attribute in all the events.

Kind Regards,

Thierry H.

**Comment by simpleidserver** [comment]
Hello,

Some changes have been made in the branch "release/2.0.5" in order to return the "representation" in the events.

Kind Regards,

SimpleIdServer
