### ISSUE TITLE
[SCIM] ResourceTypes endpoint response

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#223]
Hello, is it possibile to change the response of the ResourceTypes endpoint?

This is the current response:

![image](https://user-images.githubusercontent.com/10979448/151361592-2c8ca31c-c4d2-433b-8bd2-b05e4999a735.png)

But following the RFC (https://datatracker.ietf.org/doc/html/rfc7643#section-8.6) it should be:

![image](https://user-images.githubusercontent.com/10979448/151362016-9ed9e087-de5b-422b-b06a-4a98e29714c1.png)

And also I think that is necessary to put the paging properties:

![image](https://user-images.githubusercontent.com/10979448/151362677-6d9cc40f-5629-4ed7-950e-35df765e7544.png)

https://developer.4me.com/v1/scim/resource_types/

Thanks.
Gabriele

**Comment by simpleidserver** [comment]
Hello,

There is an issue in the current implementation. I'm going to work on it.

Kind Regards,

SimpleIdServer

**Comment by simpleidserver** [comment]
This small issue has been fixed in the branch "release/2.0.5".

Kind Regards,

SimpleIdServer

**Comment by gabrielemilan** [comment]
Hello, tried new version, now the endpoint returns:
![image](https://user-images.githubusercontent.com/10979448/151559724-ac26a426-3063-4b93-93d4-8ba6647cf5e7.png)

I think that the id and the location should be singular, the only plural should be the endpoint, isn't it?

**Comment by simpleidserver** [comment]
Indeed the "id" & "location" parameters must be singular.
The following changes have been made in the branch "release/2.0.5" :
* Add a new endpoint "/ResourceTypes/{id}"
* Location & Id parameters are now singular.

Kind Regards,

SimpleIdServer

**Comment by gabrielemilan** [comment]
Hello,

I tried the new version and it seems there is another issue. The ResourceType should be singular:

![image](https://user-images.githubusercontent.com/10979448/152155006-8819e05e-0ce3-4606-b73c-976ab3dac940.png)

https://datatracker.ietf.org/doc/html/rfc7644#section-3.3.1

![image](https://user-images.githubusercontent.com/10979448/152155508-58fdc0f1-c172-434b-a37a-7cfe51a2eb90.png)

In the previous version it was singular.

Thanks.
G
