### ISSUE TITLE
Where can I find the documentation?

### ISSUE THREAD

**Issue by jaytonic** [simpleidserver/SimpleIdServer#226]
Hi,

I wanted to evaluate if SimpleIdServer was a good fit for us, and I was looking for some example(Asp.Net Core + Angular), but the github page refers to https://simpleidserver.github.io/SimpleIdServer/ which is empty except the welcome page.

I've found other references to https://simpleidserver.readthedocs.io/en/latest but it seems to be empty too.

Can somebody points me to some documentation/examples?

**Comment by simpleidserver** [comment]
Hello,

The documentation is available here : https://simpleidserver.github.io/SimpleIdServer/documentation/openid/protectappsusers.html#single-page-application-spa

And there is a sample project here : https://github.com/simpleidserver/SimpleIdServer/tree/master/samples/ProtectApplicationFromUndesirableUsers/Spa

Kind Regards,

Thierry H.
