### ISSUE TITLE
UseUMAToProtectAPI sample: The AuthorizationPolicy named: 'ManageResources' was not found. 

### ISSUE THREAD

**Issue by bitofvg** [simpleidserver/SimpleIdServer#234]
**UseUMAToProtectAPI** sample:
Starting **UmaHost** I get:
.....
      Request starting HTTP/2 GET https://localhost:5001/ - -
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMG1PSTAKH8P", Request id "0HMG1PSTAKH8P:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: **The AuthorizationPolicy named: 'ManageResources' was not found**.
         at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
.....

**Comment by simpleidserver** [comment]
Hello,

Indeed the sample project is using the wrong extension method. 
The project "UseUMAToProtectAPI" has been updated in the master branch and is using the correct extension method.

Kind Regards,

SimpleIdServer

**Comment by bitofvg** [comment]
thanks!
