### ISSUE TITLE
UseUMAToProtectAPI sample: port 5001 conflict

### ISSUE THREAD

**Issue by bitofvg** [simpleidserver/SimpleIdServer#235]
**UseUMAToProtectAPI** sample -   **UmaHost**  project - **launchsettings.json** file:
The port is **5001**. The OpenId project has the same port and generates a conflict. In my opinion, the right port number is **60003** [see installation doc](https://simpleidserver.github.io/SimpleIdServer/documentation/uma20/installation.html)

**Comment by simpleidserver** [comment]
Hello,

First thank you for your feedback. The launchsetting files have been updated in all the samples project.
Changes have been pushed in master branch.

Kind Regards,

SimpleIdServer

**Comment by bitofvg** [comment]
now it works, many thanks!
