### ISSUE TITLE
SCIM - Swagger support

### ISSUE THREAD

**Issue by nickmarkfurness** [simpleidserver/SimpleIdServer#237]
Hi,

I have the latest version up and running and works with the Authentication provider I am using. This is the sample application that hosts itself on port 60002 I think.
However I have switched to implementing in my own web application and hoping/used an older swagger example however i am getting an error when generating the swagger.json.

Is there an up to date example of this i can refer too?

**Comment by simpleidserver** [comment]
Hello,

A sample project can be found here : https://github.com/simpleidserver/SimpleIdServer/tree/master/samples/UseSCIMSwagger. 
The solution contains a SCIM server configured with Swagger.

**NOTE : Only the version 5 of swagger is supported**

Swagger can be configured like this :

* Install the Nuget package `SimpleIdServer.Scim.Swashbuckle`. 

```
dotnet add package SimpleIdServer.Scim.Swashbuckle
```

* Install the Nuget package `Swashbuckle.AspNetCore` version `5.5.0`.

```
dotnet add package Swashbuckle.AspNetCore --version 5.5.0
```


* Edit the `Startup.cs` file and configure Swagger. Copy and paste the following code into `ConfigureService`.

```
services.AddSwaggerGen(c =>
{
    var currentAssembly = Assembly.GetExecutingAssembly();
    var xmlDocs = currentAssembly.GetReferencedAssemblies()
        .Union(new AssemblyName[] { currentAssembly.GetName() })
        .Select(a => Path.Combine(Path.GetDirectoryName(currentAssembly.Location), $"{a.Name}.xml"))
        .Where(f => File.Exists(f)).ToArray();
    Array.ForEach(xmlDocs, (d) =>
    {
        c.IncludeXmlComments(d);
    });
});
services.AddSCIMSwagger();
```

* Enable Swagger API and its UI. Copy and paste the following code into `Configure`.

```
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "SCIM API V1");
});
```

Kind Regards,

SimpleIdServer

**Comment by nickmarkfurness** [comment]
Thanks for this, i will check it out today.
I downloaded a zip copy of the code the have a look at and learn and i think that missed out the sample you pointed out so i cloned it and i can see it now.

Do i need to raise a new issue to ask about when support for the latest swagger version is going to happen or can it be answered on this thread?

**Comment by simpleidserver** [comment]
Hello,

I create a ticket to support the latest swagger version (https://github.com/simpleidserver/SimpleIdServer/issues/238)
I'm going to work on it ASAP.

Kind Regards,

SimpleIdServer

**Comment by nickmarkfurness** [comment]
Just an update.

I have this working now thanks and the sample helped a lot thank you.
