### ISSUE TITLE
SCIM Question - users in groups

### ISSUE THREAD

**Issue by nickmarkfurness** [simpleidserver/SimpleIdServer#239]
Hi,

I have the latest version up and running and i am able to sync users and groups ... my question is should it sync data of which users are in which group?

The authentication server is called: OpenText Directory Services which is a federated gateway that supports SCIM 2.0

I see code around attribute mapping which makes me think i should?

Code i refer too:

.AddAttributeMapping(new List<SCIMAttributeMapping>
            {
                new SCIMAttributeMapping
                {
                    Id = Guid.NewGuid().ToString(),
                    SourceAttributeId = userSchema.Attributes.First(a => a.Name == "groups").Id,
                    SourceResourceType = StandardSchemas.UserSchema.ResourceType,
                    SourceAttributeSelector = "groups",
                    TargetResourceType = StandardSchemas.GroupSchema.ResourceType,
                    TargetAttributeId = groupSchema.Attributes.First(a => a.Name == "members").Id
                },
            });

**Comment by nickmarkfurness** [comment]
Hi,

Thanks for the very quick response, that was very much appreciated.

I have done this and I still cannot tell which users are in which groups in the SCIM database, unless I am missing something and looking in the wrong table?

**Comment by nickmarkfurness** [comment]
I think the problem might be in my authentication server, i don't see any mappings configured at for groups to enable groups.values to actually have a value for the users being imported

Is there a way to log the data that was sent in for easier inspection?

**Comment by nickmarkfurness** [comment]
Hi,

I have the solution running with VS Studio Debugger and turned all logging to Debug and i see a boat load more but i was hoping to see the raw data/json output so i can see what the Authentication Server is sending as i want to know if it is the implementation of SimpleIdServer or if the issue lies at source and it is not sending the data in the expected format.

I suppose i could try wireshark or something.

**Comment by simpleidserver** [comment]
Some changes have been made in the SCIM project (master branch) to log incoming requests.
There is no need to wait next SimpleIdServer release. All incoming & outgoing HTTP requests can be logged like this :
* Create the class `RequestLoggingMiddleware` and copy the following code.

```
public class RequestLoggingMiddleware
{
    private readonly ILogger<RequestLoggingMiddleware> _logger;
    private readonly RequestDelegate _next;

    public RequestLoggingMiddleware(ILogger<RequestLoggingMiddleware> logger, RequestDelegate next)
    {
        _logger = logger;
        _next = next;
    }

    public async Task Invoke(HttpContext httpContext)
    {
        if (httpContext == null) throw new ArgumentNullException(nameof(httpContext));
        var start = Stopwatch.GetTimestamp();
        try
        {
            var incomingRequest = await ReadIncomingRequest(httpContext);
            await _next(httpContext);
            var elapsedMs = GetElapsedMilliseconds(start, Stopwatch.GetTimestamp());
            var statusCode = httpContext.Response.StatusCode;
            LogCompletion(httpContext, statusCode, elapsedMs, null, incomingRequest);
        }
        catch (Exception ex)
        {
            LogCompletion(httpContext, 500, GetElapsedMilliseconds(start, Stopwatch.GetTimestamp()), ex);
        }
    }

    private async Task<string> ReadIncomingRequest(HttpContext httpContext)
    {
        var request = httpContext.Request;

        request.EnableBuffering();
        var buffer = new byte[Convert.ToInt32(request.ContentLength)];
        await request.Body.ReadAsync(buffer, 0, buffer.Length);
        var requestContent = Encoding.UTF8.GetString(buffer);
        request.Body.Position = 0;
        return requestContent;
    }

    private void LogCompletion(HttpContext httpContext, int statusCode, double elapsedMs, Exception ex, string incomingRequest = null)
    {
        if (ex != null)
        {
            _logger.LogError(ex.ToString());
            return;
        }

        var message =  $"RequestMethod: {httpContext.Request.Method}, RequestPath: {GetPath(httpContext, true)}, StatusCode: {statusCode}, Elapsed: {elapsedMs}";
        _logger.LogInformation(message);
        _logger.LogInformation($"Input: {incomingRequest}");
    }

    static double GetElapsedMilliseconds(long start, long stop)
    {
        return (stop - start) * 1000 / (double)Stopwatch.Frequency;
    }

    static string GetPath(HttpContext httpContext, bool includeQueryInRequestPath)
    {
        var requestPath = includeQueryInRequestPath
            ? httpContext.Features.Get<IHttpRequestFeature>()?.RawTarget
            : httpContext.Features.Get<IHttpRequestFeature>()?.Path;
        if (string.IsNullOrEmpty(requestPath))
        {
            requestPath = httpContext.Request.Path.ToString();
        }

        return requestPath;
    }
}
```

* Edit the `Startup.cs` class and add the following line in the `Configure` method :

```
app.UseMiddleware<RequestLoggingMiddleware>();
```

All incoming request will be logged in your console application.

**Comment by nickmarkfurness** [comment]
Hi,

Thanks for this, this worked great and helped me alot! I am very impressed with the level of support thank you.

The logging has shown that the Authentication server that is meant to support SCIM 2.0 isn't sending a members or groups property on the data coming in so i am going to check with them if there is something wrong with my configuration in their system.

They say they support 'core' SCIM attributes so am I right in thinking the groups/members properties are 'core', it is described in the json schema??

**Comment by simpleidserver** [comment]
Hello,

According to the RFC-7643 (Core Schema), the attributes "members" and "groups" must be present.
URL : https://datatracker.ietf.org/doc/html/rfc7643
Page 63 : The User representation contains a property "groups".
Page 69 : The Group representation contains a property "members".

You can check if both attributes are supported by browsing the URL : <<SCIM API>>/Schemas.
A JSON schema is returned and contains all the properties present in the "User" & "Group" representations.

**Comment by PetrutiuPaul** [comment]
@simpleidserver, I think logging all the attributes of the requests should not be mandatory for everybody, so it should be a way to opt-out from this. These calls are usually backend to backend and because of GDPR, you should maybe at least anonymize the values inside the attributes before logging it. Or give a simple way to rewrite or opt-out.

**Comment by simpleidserver** [comment]
Good remark. The modifications have been rolled back in the branch "release/2.0.6".
It's up to the user of our Nuget package to log all the incoming & outgoing HTTP requests by implementing a middleware or use a library like Serilog.

**Comment by nickmarkfurness** [comment]
I only needed the logging middleware for debugging, i was not going to leave it in once i am finished.
So was still a useful snip of code for me as it confirmed where my problem lied
