### ISSUE TITLE
Remove brackets from db values.

### ISSUE THREAD

**Issue by bzuidgeest** [simpleidserver/SimpleIdServer#24]
I noticed that when I add objects to the database it stores values like

ValueString
[]
["htt0f03fa"]
["Voornaam"]
["Achternaam"]

It also does that for valuesBoolean, ValuesInteger etc..... I hate to call this a bug, but I think it would certainly enhance backend data consumption of the data if there where no brackets and quotes in the data. So I would like to request they be removed. That would make is much easier to join to other datas.

If there are reasons for storing it this way, thats ok, I can always strip them in my queries.

**Comment by bzuidgeest** [comment]
Already figured out the answer. I did not notice the s in ValuesString. It assumes everything multivalue in the store. May that can be split into single value and multivalue column or such, but that might be a big change.

**Comment by simpleidserver** [comment]
We are going to check what we can do to avoid to store the list of values as JSON object.

One solution consists to create an another table **SCIMRepresentationAttributeValueModel** with the following properties, and update the **EFSCIMExpressionLinqExtension**  class which transforms SCIM expressions into LINQ expressions.
List of properties :
* Type (string, int ...) => enumeration
* ValueString
* ValueBoolean

Because there is no strong dependency between **SimpleIdServer.Scim** and **SimpleIdServer.Scim.Persistence.EF** projects, only the **SimpleIdServer.Scim.Persistence.EF** project must be updated.

**Comment by bzuidgeest** [comment]
If you want to do that, why not just create the single value columns in the [SCIMRepresentationAttributeLst] table? Seems to me to the less complex option. Its already an Entity-Attribute-Value model table and SQL wont mind a few extra columns.

**Comment by simpleidserver** [comment]
If we opt for the option you proposed and we keep the list of string (int ...) in one field, it will kill the performance for the following reasons :

* You can no longer use "=" but have to use something like "like".
* Lose the ability to join on that field.
* Try count/sum etc ... it won't work.

We'll probably add an another table with the following structure :

**RepresentationAttributeValue**
- Enumeration (string, int etc ...)
- ValueString
- ValueInt

The class **RepresentationAttribute** will contain a list of **Values**.

We will start to refactor the **SimpleIdServer.Scim.Persistence.EF** project when the release of CaseManagement version 1.0.2 is done.

**Comment by bzuidgeest** [comment]
That is not what I meant. What I was asking about was why a column like the existing ValueSstring and proposed new column ValueString could not be in the same table. When an attribute is multivalue it goes in the xxxxSvalue column and single value in the xxxValue column. Same for the types other than string.

But maybe I'm misinterpreting how the values are stored at the moment. I'm assuming a multivalue attribute goes into a xxxxxSvalues column like ["a","b"]. My current custom resource does not include multi value properties so I have not explicitly tested this.

**Comment by simpleidserver** [comment]
We want to avoid storing multiple values in a single column (ValuesString, ValuesBoolean etc ...) because of the following reasons :

- You can no longer use "=" but have to use something like "like".
- Lose the ability to join on that field.
- Try count/sum etc ... it won't work.

We rather prefer to store each individual value in a separate table.

**Comment by bzuidgeest** [comment]
I believe something is getting lost in translation or my understanding of current database schema. My primary "complaint" is that the current columns contain json style brackets preventing me from easy joining. 
I'm going to trust you as the experts in this case (no sarcasm intended) and just await your solution of choice, I'm sure it will work.

**Comment by simpleidserver** [comment]
The changes have been committed in the branch origin/1.0.9, can-you try again ?

The commit is : https://github.com/simpleidserver/SimpleIdServer/commit/c2b57a484fc6eb40e5cdb60bc9197012d103a324

**Comment by bzuidgeest** [comment]
I now have plain unformatted values without brackets. It's as lot of joins to get information out of it, but that is unavoidable with applications that have a "user" editable schema and types. One could consider a table per type db schema, but that has other problems. So I'm happy with the changes. 
If I had to find a complaint it would be that the columns seem to have "default" values applied against them. I would prefer only stringvalue to be filled in case of a string value leaving the rest at null. But this is minor. 

Very happy with the changes, thanks.

**Comment by simpleidserver** [comment]
The columns "ValueInteger", "ValueBoolean" and "ValueDateTime" are nullable, please find the changes in this commit : https://github.com/simpleidserver/SimpleIdServer/commit/55cee7d2456a98c853192c07f73e7a58ae3bf318
