### ISSUE TITLE
User.Sessions not work without persistence layer

### ISSUE THREAD

**Issue by RadekVoltr** [simpleidserver/SimpleIdServer#241]
Testing code on default solution 
![image](https://user-images.githubusercontent.com/22295123/159046164-7390ea19-7e8e-425d-ad9c-f283a9c4dbbf.png)

and it looks that Sessions makes issues in case of missing persistent layer.

0. trying to play with Postman/OAuth2/Authorization code
1. Sessions are stored in-memory or persistent layer
2. Sessions are used on plenty places without null check - code expect that there is always active session during issuing token
3. Session is created in BaseAuthenticateController / Sign

In case that user is already logged in (with cookie) then problem happen.

1. user gets autheticated via cookie (but without calling Sign)
2. user gets displayed Consent
 
![image](https://user-images.githubusercontent.com/22295123/159046931-b86b98d4-4113-49f4-8611-3b216b43968f.png)
3. after confirmation will user end on this exception 
![image](https://user-images.githubusercontent.com/22295123/159047118-9e54aa2a-754b-486a-92c7-2a5188876d80.png)

Proposed solution :

- GetActiveSession will create session if session list is empty and all code will call this code
- OpenIDUserConsentFetcher/FetchFromAuthorizationRequest will create session if session list will be empty

What version fix have better chance to be approved into main repo ?

**Comment by simpleidserver** [comment]
Hello,

Indeed there is an issue when a cookie is created and the in memory storage is used. 
An acceptable solution is to invalidate the cookie when the session disappeared. Your proposed solutions look also good, i m going to make some investigations about the pros and cons. 
I will give you an acceptable answer when I ve some free Time ( next week)

Kind regards,

Simpleidserver

**Comment by RadekVoltr** [comment]
`   public class OpenIDUserConsentFetcher : IUserConsentFetcher
    {
        private readonly OpenIDHostOptions _options;

        public OpenIDUserConsentFetcher(IOptions<OpenIDHostOptions> options)
        {
            _options = options.Value;
        }
        public OAuthConsent FetchFromAuthorizationRequest(OAuthUser oauthUser, JObject queryParameters)
        {
            if (oauthUser.Sessions?.Count == 0)
                oauthUser.Sessions.Add(new Common.Domains.UserSession() {AuthenticationDateTime = DateTime.Now, ExpirationDateTime = DateTime.Now.AddSeconds(_options.CookieAuthExpirationTimeInSeconds), SessionId = Guid.NewGuid().ToString(), State = Common.Domains.UserSessionStates.Active });
`

I did this hot fix (without too much analyze) and it works (in case which I found). Feel free to use it in case that you will find it working

**Comment by simpleidserver** [comment]
Several changes have been made in the "release/2.0.6" branch :
* When grant_type authorization code is used and there is no active session then user-agent is redirected to login page & cookie sare erased.
* If there is no active session then don't add the claims : `sid`, `auth_time`
* If there is no active session then don't build session state.

**Comment by RadekVoltr** [comment]
works without issues on release/2.0.6. Thank you !
