### ISSUE TITLE
SCIM - /schemas endpoint issue

### ISSUE THREAD

**Issue by PetrutiuPaul** [simpleidserver/SimpleIdServer#242]
When returning all the schemas, the mutability property has values like : immutable, readonly, writeonly, etc. In the rfc documentation looks like the props values should be camel case : immutable, readOnly, writeOnly, etc...

**Comment by simpleidserver** [comment]
Indeed it's an issue.
We are going to work on it.

Kr,

SimpleIdServer

**Comment by simpleidserver** [comment]
The issue is fixed in the branch "release/2.0.6"
