### ISSUE TITLE
[SCIM] exception thrown on users PUT

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#248]
The following exception was thrown:

```
System.ArgumentException: Can not add property value to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
  ?, in void JObject.ValidateToken(JToken o, JToken existing)
  ?, in bool JContainer.InsertItem(int index, JToken item, bool skipParentCheck)
  ?, in void JContainer.Add(object content)
  ?, in void SCIMRepresentationExtensions.EnrichResponse(IEnumerable<EnrichParameter> attributes, JObject jObj, bool isGetRequest)
  ?, in JObject SCIMRepresentationExtensions.ToResponse(SCIMRepresentation representation, string location, bool isGetRequest, bool includeStandardAttributes, bool addEmptyArray)
  ?, in async Task<IActionResult> BaseApiController.InternalUpdate(string id, RepresentationParameter representationParameter)
```

Unfortunately, I do not have the `PUT` payload.

**Comment by simpleidserver** [comment]
I'll try to reproduce the error on my machine.
If it's possible, can-you give more details (steps to reproduce the bug) ? It will help me to understand the cause of the issue.

**Comment by danflomin** [comment]
I was able to reproduce this problem.
It looks like in EF6, when you perform a `PUT` after a `POST` of a user, some attributes are being duplicated badly.
For example, I found duplicate email attributes, without a `ParentAttributeId`.
![image](https://user-images.githubusercontent.com/33806717/162960985-d6b519af-a515-4eb0-9e49-8c56c515acaf.png)

When I tested the same flow on a previous EF version, it did not reproduce.

**Comment by simpleidserver** [comment]
The project "SCIM EF" is supporting the version 5 of Entity Framework Core.
A new project SimpleIdServer.Scim.Persistence.EFNet6 has been created to support EF6. 
There is a working example in the branch "release/2.0.6" and it can be found here : https://github.com/simpleidserver/SimpleIdServer/tree/release/2.0.6/src/Scim/dotnet6/SimpleIdServer.Scim.SqlServer.Startup

**Comment by danflomin** [comment]
Amazing.
Thanks.

Is there an ETA for the 2.0.6 release?

**Comment by simpleidserver** [comment]
Hello,

I'm going to release SimpleIdServer 2.0.6 next week (21-04)

Kind Regards,

SimpleIdServer

**Comment by danflomin** [comment]
Great!

I used the SimpleIdServer.Scim.Persistence.EFNet6 using the 2.0.6 branch, it did not work as well.

I think you should test this use case, as the new EF version is not sufficient to fix this issue.

**Comment by simpleidserver** [comment]
Some modifications have been made in the branch "release/2.0.6".
There was an issue with the Entity Framework configuration, can-you retry again ?

Kind Regards,

SimpleIdServer.
