### ISSUE TITLE
[SCIM] 2.0.6 regression on adding twice the same user to a group using `PatchOp`

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#256]
The RFC for SCIM indicates that when adding an already existing user to a group, then the server should respond with an empty message or with the data of the group we are trying to add the user to.

The following commit introduced this exception.
https://github.com/simpleidserver/SimpleIdServer/commit/f7155753f7ba851edd3473ed73227a344bbad5f2#

<img width="650" alt="image" src="https://user-images.githubusercontent.com/33806717/165078144-327b10f6-b4c4-4640-b167-4f5de0899f8e.png">

**Comment by simpleidserver** [comment]
The issue should be fixed in the branch "release/2.0.7".

If the target location already contains the value specified, no changes should be made to the resource and a success response (204) is returned.
