### ISSUE TITLE
Query - How best to implement api versioning for SCIM endpoints

### ISSUE THREAD

**Issue by nickmarkfurness** [simpleidserver/SimpleIdServer#270]
I think i know the answer to this but i thought i would ask just in case.

If i wanted to implemement standard api versioning how would i do this?
example: /v1/****

I think i would have to extend all the built in controllers and implement  myself

**Comment by simpleidserver** [comment]
Hello,

First sorry for my late reply.
Indeed, there is no easy way to implement standard api versioning.
As you suggested, you can extend all the built-in controllers and implement yourself.

Kind regards,

SimpleIdServer

**Comment by nickmarkfurness** [comment]
We have successfully extended core controllers to implement :)

Please close this question
