### ISSUE TITLE
SCIM Resource ExternalId is not working with Patch Add and works only with Patch Replace

### ISSUE THREAD

**Issue by iyhammad** [simpleidserver/SimpleIdServer#280]
Hello,
I understand from [the code](https://github.com/simpleidserver/SimpleIdServer/blob/9ca83b7bd16bdaf6521d6dc21442df592f5fe95f/src/Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs#L257) that ExternalId is intended to work with Patch Add as well as Replace but I see since the ExternalId is not part of the schema, we [throw SCIMNoTargetException](https://github.com/simpleidserver/SimpleIdServer/blob/9ca83b7bd16bdaf6521d6dc21442df592f5fe95f/src/Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs#L199)
I will create a pull request for it.

**Comment by simpleidserver** [comment]
Hello,

Indeed there is an issue in the current implementation. Thank you for tour your contribution, we are going to take a look at it.

Kind regards,

SimpleIdServer

**Comment by iyhammad** [comment]
Thank you team, tried now and worked
