### ISSUE TITLE
[SCIM] enterprise user displayName not saved when mutability is readOnly

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#288]
Hello,

If the mutability of `manager.displayName` is `readOnly`, then when I POST a user, the property `manager.displayName` is not saved.

If I change the mutability to `readWrite` then it is saved and returned correctly.

**Comment by simpleidserver** [comment]
Hello,

According to the RFC 7644 section 3.3, attributes whose mutability is "readOnly" SHALL be ignored : https://datatracker.ietf.org/doc/html/rfc7644#section-3.3
The current implementation respects the RFC.

**Comment by danflomin** [comment]
Thank!
