### ISSUE TITLE
[SCIM] migrating to EF6

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#291]
Hello,

I am trying to convert my project from using EF5 to EF6.

When running the `dotnet ef migrations add` command, I get the following warnings.

```Build started...
Build succeeded.
The property 'SCIMSchemaAttribute.CanonicalValues' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
The property 'SCIMSchemaAttribute.DefaultValueInt' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
The property 'SCIMSchemaAttribute.DefaultValueString' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
The property 'SCIMSchemaAttribute.ReferenceTypes' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
Done. To undo this action, use 'ef migrations remove'
```

Do you think that a `ValueComparer` should be added to the configuration files as suggested in [stackoverflow](https://stackoverflow.com/questions/59890434/set-a-value-comparer-in-asp-net-core-3-1)?

Thanks!

**Comment by simpleidserver** [comment]
Hello,

Indeed you're right. According to MSDN,  the default comparison used by EF Core is not always appropriate. For example, mutation of string or integer array.
Some changes have been made in the Project to override the default comparer.

Thank you for your feedback :)

Kind regards,

Sid

**Comment by danflomin** [comment]
Thanks for your quick response as always :)

When do you think this will be released?

**Comment by simpleidserver** [comment]
The release will be published this friday.

**Comment by danflomin** [comment]
Hi,

I tried migrating to EF6 but encountered a few errors.

When trying to query just `emails` from Users, or excluding `members` from Groups, I get the following exception:

```
Response: 
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "status": "500",
  "scimType": "internalServerError",
  "detail": "System.InvalidOperationException: The expression 'r.Children' is invalid inside an 'Include' operation, since it does not represent a property access: 't => t.MyProperty'. To target navigations declared on derived types, use casting ('t => ((Derived)t).MyProperty') or the 'as' operator ('t => (t as Derived).MyProperty'). Collection navigation access can be filtered by 
```

This does not happen with EF5.

Thanks 
Dan

**Comment by simpleidserver** [comment]
Hello,

Indeed a regression has been introduced by the ticket #283 : Remove orphan.
Some modifications have been made in the branch "release/v2.0.12" and both bugs are fixed : 
* Remove orphans from Database.
* Support 'attributes' and 'excludedAttributes'".

Pre-release package have been published. 

dotnet add package SimpleIdServer.Scim --version 2.0.12-ci-00305 --source https://www.myget.org/F/advance-ict/api/v3/index.json
dotnet add package SimpleIdServer.Scim.Persistence.EFNet6 --version 2.0.12-ci-00305 --source https://www.myget.org/F/advance-ict/api/v3/index.json

KR,

Sid

**Comment by danflomin** [comment]
Hi,

Thank you very much for the preview packages.

Now my tests pass.

I will appreciate it if you can release the new version soon.


You are awesome as always!
