### ISSUE TITLE
Users filter - Precedence grouping

### ISSUE THREAD

**Issue by nickmarkfurness** [simpleidserver/SimpleIdServer#293]
Hi,

When filter for a user the brackets do not seem to function correctly.

Using the swagger page to invoke the GET request i set the filter text field to:

userName eq "NickF@ourdomain.com"

This works! 1 result is returned

i set to:

(userName eq "NickF@ourdomain.com")

and it returns pretty much everyone in the database.

Granted the brackets aren't needed here but i can't control the SCIM client side of things and this is what is coming in from their side.

**Comment by nickmarkfurness** [comment]
After further testing brackets do seem to work, the only time they don't is in my use case above where only the one userName is filtered for and you use brackets as well!

So:

(A or B) or (C or D) = fine
(A or B) = fine
(A) = doesn't behave correctly

A/B/C/D --> userName eq "***"

**Comment by nickmarkfurness** [comment]
Hi,

Wow fast work and response. Thank you.
When will the release be published to nuget?

Cheera

**Comment by simpleidserver** [comment]
The release will be published this friday.
