### ISSUE TITLE
[SCIM] update enterprise users with empty values

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#295]
Hi,

When I try to update an enterprise user with an empty value `""`, the returned value is null instead of empty.

For example updating the `CostCenter` attribute.

I think that this is a bug.

What do you think?

Thanks !

**Comment by simpleidserver** [comment]
Hello,

Indeed, it seems logical to set the value to `""`. Moreover, there is nothing mentionned in the RFC about this scenario.
Next Friday, I'll make some modifications in the solution to fix this bug.

Kind regards,

SID

**Comment by simpleidserver** [comment]
Hello,

The issue is fixed. 

KR,

SID
