### ISSUE TITLE
[SCIM] user has no `emails` attribute

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#297]
Hi,

I have had a few cases where users in SCIM are stored in the DB with `email` sub attributes, but without a `parentAttributeId`.

I could not reproduce this issue.

Is it possible to add a safe-mechanism for this issue?
If sub-attributes are to be created with a `parentAttributeId` which is null then to first create the parent attribute?

Kind regards

**Comment by simpleidserver** [comment]
Please read the answer in the ticket #300

**Comment by danflomin** [comment]
Hi,

Thanks for your reply.

This issue is happening with EF5.
I am not sure if it happens with EF6.

Thanks
Dan

**Comment by simpleidserver** [comment]
Indeed it is strange. Next week (>= 5 august), I'll spend some time to investigate this issue.

KR,

Sid
