### ISSUE TITLE
User in more than one group

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#30]
Hello,

if a user is in more than one group the get user, returns only one group.

Regards.

**Comment by simpleidserver** [comment]
Thank you for your pull request.

The extension method is fixed and the groups are returned in the JSON representation :).

**Comment by gabrielemilan** [comment]
> Thank you for your pull request.
> 
> The extension method is fixed and the groups are returned in the JSON representation :).

Ok, thanks. I noticed that in my PR there were an error:
![image](https://user-images.githubusercontent.com/10979448/80273602-ed8ec680-86d3-11ea-93c8-51737b5d8ae8.png)
But you fixed it properly :-)
