### ISSUE TITLE
Timeout - GET User or Group

### ISSUE THREAD

**Issue by nickmarkfurness** [simpleidserver/SimpleIdServer#301]
When you search for a User or Group that doesn't exist with the GUID it takes a long time and only returns with user or group not found because it timed out after 10 seconds. Whether this is by api call or use of the swagger page i am able to replicate either way.

See screenshot:

![image](https://user-images.githubusercontent.com/8597946/180779927-907a7f9c-61a7-4d27-979e-fb2d049d2d92.png)

Is there a way to shorten the timeout? The SCIM server that is integrating has its own timeout for the call and in turn not getting the correct result quick enough.

10 seconds seems a long time to not find a user or group, is there is a reason for this?

Cheers.

**Comment by nickmarkfurness** [comment]
Upon further investigation I can manually override the timeout via C# code when registering the dbcontext and reduce it to say 3 seconds but then i start to get errors around EF and SQL not finishing in time before the timeout forces it to stop.

Logs (Before my code change around the command timeout for EF):

2022-07-25 10:23:41,936  WARN Microsoft.EntityFrameworkCore.Query.? [?] - MESSAGE: Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.

 2022-07-25 10:23:41,965 ERROR Core.AIMSuite.Authorisation.REST.WS.Controllers.GroupsController.MoveNext [0] - MESSAGE: resource 7ba0c823-9b2d-4ebd-93e7-19569817aca6 not found

**Comment by simpleidserver** [comment]
Hello,

When there are a lot of data in your tables, the performance may be bad.
In order to avoid "cartesian explosion problem", you can split the LINQ queries into multiple SQL queries.
Update your configuration file like this :

```
services.AddScimStoreEF(options =>
{
    options.UseSqlServer(Configuration.GetConnectionString("db"), o =>
    {
        o.MigrationsAssembly(migrationsAssembly);
        o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
    });
});
```

And update your connection string to enable MultipleActiveResultSets (MARS)

```
Data Source=MSSQL; Initial Catalog=AdventureWorks; Integrated Security=SSPI; MultipleActiveResultSets=True
```

Kind regards,

Sid

**Comment by nickmarkfurness** [comment]
Hi,

I have 10 users and about 6 groups so i dont have alot of data, however i will try the config changes tomorrow and see what effect this has.

Thanks

**Comment by simpleidserver** [comment]
Indeed there is not a lot of data, there are 200k users in my database and it takes 50ms to get a user. 

For further investigation, you can use a tool like `sql server profiler` to monitor your SQL database and view the performance.

**Comment by nickmarkfurness** [comment]
oh wow that made that all the difference!

I would be putting that front and centre in the documentation. Like i said i have 10 users and 6 groups and it was taking towards 10 whole seconds (not ms)

Thanks for the support!
