### ISSUE TITLE
SCIM setup with public URL different than the internal one

### ISSUE THREAD

**Issue by iyhammad** [simpleidserver/SimpleIdServer#302]
Hello again,
In our SCIM setup, SCIM has 2 URLs, a public one that is accessible by our SCIM consumers and an internal one that is accessible inside our cluster network.
For example, our public SCIM consumers use /v1/scim to reach SCIM then our Nginx rewrites the URL to be /api/public/v1/scim after authentication/authorization.
Because of that resources meta section always has the internal URL as a location. In the above example, it looks like this,
```
"meta": {
                "resourceType": "User",
                "created": "2022-06-18T05:21:45.4929283Z",
                "lastModified": "2022-06-18T06:12:52.336043Z",
                "version": 4,
                "location": "https://mycustomscim.com/api/public/v1/scim/users/637911265056842059"
            }
```
We would like to have a way to specify the base URL of the service so we can make it matches our public service URL.
Do you have any suggestions? We can contribute it if we agree on the design.
Have a great day :)

**Comment by simpleidserver** [comment]
Hello,

One solution is to update the nginx configuration and pass the custom header : `X-Forwarded-Host`. For more information please refer to the official documentation: https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

Then in the Startup.cs class, add the following code to configure the middleware 

```
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});
```

Kind regards,

Sid

**Comment by iyhammad** [comment]
Thank you for your swift reply.
We have the header `X-Forwarded-Host` but the problem is not in the host. The problem is we change part of the path. Specifically, we change the base path from `/v1/scim` to `/api/public/v1/scim` and the service doesn't know about this mapping.
In [this line](https://github.com/simpleidserver/SimpleIdServer/blob/8a46181b87154c1d6b3c86d8e22aae3f703397c3/src/Scim/SimpleIdServer.Scim/Api/BaseApiController.cs#L202) we try to get the path using `GetAbsoluteUriWithVirtualPath`. Inside [GetAbsoluteUriWithVirtualPath](https://github.com/simpleidserver/SimpleIdServer/blob/8a46181b87154c1d6b3c86d8e22aae3f703397c3/src/Saml/SimpleIdServer.Saml/Extensions/HttpRequestExtensions.cs#L18) we get the url from the `PathBase` which have only the internal path base.
Best Regards,

**Comment by simpleidserver** [comment]
I don't know how your Nginx configuration is written. 
But one acceptable solution can be to pass a custom header and use it in your Middleware (ASP.NET CORE) to set the `request.PathBase`.

Nginx configuration :

```
proxy_set_header X-Forwarded-PathBase /api/public/v1/scim;
```

Middleware code

```
app.Use(async (context, next) =>
{
    context.Request.PathBase = new PathString(context.Request.Headers["X-Forwarded-PathBase"]);
    await next.Invoke();
});
```

**Comment by iyhammad** [comment]
I tried the change today and seems to fix it. However I'm afraid from other parts of the system that could access the BassPath and by this change we are changing its meaning.
The BassPath should have part of the internal service path.
Is it possible to create an interface to provide these paths with the existing implementation as the default implementation? This could give the host system the ability to provide a different implementation if required. I can contribute this change if you like the design or if you have another idea.
Best regards,

**Comment by simpleidserver** [comment]
Indeed, the logic used to build the `BaseUrl` can be moved into a class.
I'm on holiday and I don't have the time to add this logic. I'll be pleased if you can make a pull request with those changes :)

**Comment by iyhammad** [comment]
Great, Enjoy your holiday 😊.
I will creat a Pull Request with this design and you can review it.
Best regards,

**Comment by iyhammad** [comment]
I've created #304. Please let me know if it requires any modifications
Best regards,

**Comment by simpleidserver** [comment]
Thank you for your contribution ! The pull request is correct and has been merged.

KR,

SID

**Comment by simpleidserver** [comment]
Hello,

The release is scheduled next week (5 august).

KR,

Sid

**Comment by iyhammad** [comment]
Hello, Should we still expect the release today 😊
Best regards,
Ibrahim Hammad

**Comment by simpleidserver** [comment]
Hello, sorry for my late reply.
The release 2.0.14 is published.
KR,

Sid

**Comment by iyhammad** [comment]
Thank you 💪
