### ISSUE TITLE
[SCIM] upgrade MassTransit's major version to 8

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#303]
Hello,

MassTransit's version 8 was released earlier this year (around March).

This is a major version change, and it includes new features and enhancements. 

I would appreciate your help with upgrading the SimpleIdServer code to use MassTransit's version 8+.

Kind regards,
Dan

**Comment by simpleidserver** [comment]
Hello,

I'm going to make the changes on the branch "release/2.0.14".

KR,

Sid

**Comment by simpleidserver** [comment]
The MassTransit version has been upgraded to version 8 in the branch "release/v2.0.14".

KR,

SID

**Comment by danflomin** [comment]
Thanks!
