### ISSUE TITLE
[SCIM] `EnterpriseUser` attributes

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#305]
Hello,

I noticed 2 issues regarding enterprise attributes.

I will appreciate your help with them.

First:
Enterprise users' attributes are returned not as a sub attribute of the extension schema.

Steps to reproduce are:

1. POST a user using 

```
{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "userName": "00u5rqicjuAPteQPv5d7",
  "name": {
    "givenName": "Runscope853update",
    "familyName": "Xtadjhqoi844"
  },
  "emails": [
    {
      "primary": true,
      "value": "Runscope853Xtadjhqoi844@atko.com",
      "type": "work"
    }
  ],
  "displayName": "Runscope853update Xtadjhqoi844",
  "locale": "en-US",
  "externalId": "00u5rqicjuAPteQPv5d7",
  "groups": [],
  "password": "2j3K37Kt",
  "active": true
}
```

2. PUT a user's `organization` attribute.

```
{
  "id": "ca9601f0-787b-4dea-bba5-4fec88c9e88a",
  "emails": [
    {
      "primary": true,
      "value": "Runscope853Xtadjhqoi844@atko.com",
      "type": "work"
    }
  ],
  "name": {
    "familyName": "Xtadjhqoi844",
    "givenName": "Runscope853update"
  },
  "active": true,
  "userName": "00u5rqicjuAPteQPv5d7",
  "displayName": "Runscope853update Xtadjhqoi844",
  "locale": "en-US",
  "meta": {
    "resourceType": "User",
    "created": "2022-07-27T12:17:59.522638",
    "lastModified": "2022-07-27T12:17:59.522638",
    "version": 0
  },
  "externalId": "00u5rqicjuAPteQPv5d7",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User",
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
  ],
  "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
    "organization": "sof"
  },
  "groups": []
}
```

Then a GET to get this user will result with a payload that is flat (without the `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` sub attribute).

The second issue relates to trying to remove an enterprise attribute off of a user.

After performing the first 2 steps, use PUT to remove the user's `organization`.

```
{
  "id": "ca9601f0-787b-4dea-bba5-4fec88c9e88a",
  "name": {
    "familyName": "Xtadjhqoi844",
    "givenName": "Runscope853update"
  },
  "userName": "00u5rqicjuAPteQPv5d7",
  "emails": [
    {
      "type": "work",
      "primary": true,
      "value": "Runscope853Xtadjhqoi844@atko.com"
    }
  ],
  "active": true,
  "displayName": "Runscope853update Xtadjhqoi844",
  "locale": "en-US",
  "organization": "sof",
  "meta": {
    "resourceType": "User",
    "created": "2022-07-27T12:17:59.522638",
    "lastModified": "2022-07-27T12:18:24.388873",
    "version": 1
  },
  "externalId": "00u5rqicjuAPteQPv5d7",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "groups": []
}
```
* The error occurs regardless of indicating the flat `organization` attribute.

After the 2nd PUT I get the following error:

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": "500",
    "scimType": "internalServerError",
    "detail": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at SimpleIdServer.Scim.Domains.SCIMRepresentationAttribute.Clone()\n   at SimpleIdServer.Scim.Domains.SCIMRepresentation.<>c.<Clone>b__69_0(SCIMRepresentationAttribute a)\n   at System.Linq.Enumerable.SelectListIterator`2.ToList()\n   at SimpleIdServer.Scim.Domains.SCIMRepresentation.Clone()\n   at SimpleIdServer.Scim.Commands.Handlers.ReplaceRepresentationCommandHandler.Handle(ReplaceRepresentationCommand replaceRepresentationCommand)\n   at SimpleIdServer.Scim.Commands.Handlers.ReplaceRepresentationCommandHandler.Handle(ReplaceRepresentationCommand replaceRepresentationCommand)\n   at SimpleIdServer.Scim.Api.BaseApiController.InternalUpdate(String id, RepresentationParameter representationParameter)"
}
```

Are these two issues related?

Kind regards,
Dan

**Comment by simpleidserver** [comment]
Hello,

Indeed there is a small issue in the current implementation. The issue is fixed in the branch "release/v2.0.14".
Now, when Schemas don't exist they are inserted into the representation.

KR,

Sid

**Comment by danflomin** [comment]
Thank you!

I am not sure if it related or not, but if you update a user with a null `costCenter` then it will just change the value to `""`.

What do you think on this?

**Comment by simpleidserver** [comment]
The issue is not related to this ticket.

When a representation was updated and one property value was set to `NULL` then the property value was equal to `""`.
Some changes have been made in the branch "release/2.0.14", in order to set the value to `NULL`.

**Comment by danflomin** [comment]
Thanks !

I checked this [commit](https://github.com/simpleidserver/SimpleIdServer/commit/1c74fe98bb5d9a65042dc7e25300e525c0546dd9) and I am not sure it fixes what I was talking about.

What I meant was that enterprise sub attributes appear in he first hierarchy of the `UserResource`.
For example 

```
{
    "costCenter: "a-cost-center"
}
```

And not like this (as I understand they should be):

```
{
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" : {
            "costCenter: "a-cost-center"
        }
}
```

Does this makes sense?

**Comment by simpleidserver** [comment]
A new property `MergeExtensionAttributes` has been introduced in SimpleIdServer.Scim since the version 2.0.10 (please refer to this ticket https://github.com/simpleidserver/SimpleIdServer/issues/287)
* If the attribute is `false` then entreprise attributes are returned in their corresponding namespace (`urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`).
* If the attribute is `true` then entreprise attributes are returned as CORE attributes.
By default the attribute is `false`.

This attribute has been implemented because one of the user is expecting this behavior even if it's not a standard way.

**Comment by danflomin** [comment]
This works!
