### ISSUE TITLE
SCIM Question - how to not publish only some masstransit events

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#306]
Hello,

I want to disable publishing events for the GroupsController, but to keep publishing for the UsersController.

I did so with a hack by 
`SCIMConstants.MappingScimResourceTypeToCommonType.Remove("Group");`

Do you have a better non-hacky idea for this?

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello Dan,

Can-you explain the reason why you want to disable publishing events in the GroupsController ?
If you are not interested by an Event then don't add a Consumer.

**Comment by danflomin** [comment]
Hello,

I want to consume events for all user's events.
Since the events are shared among users and groups, I must also consume the
groups events.


Thanks

**Comment by simpleidserver** [comment]
Some changes have been made in the branch "release/2.0.15".
Two properties have been added in the `SCIMHostOptions`:
* `IsUserPublishEvtsEnabled`: Enable or disable publishing user events.
* `IsGroupPublishEvtsEnabled` : Enable or disable publishing group events.

If you want to disable publishing events in a custom controller then override the property `IsPublishEvtsEnabled` and set the value to `false`:

```
protected override bool IsPublishEvtsEnabled => false;
```

**Comment by danflomin** [comment]
You are the best!

**Comment by danflomin** [comment]
In the case a user was added to a group, and then the user is being `Notify`ied that it was updated, it will not get an event with the current implementation.
Right?

I still want to consume the reference events for the users that are being added\removed from groups.

**Comment by danflomin** [comment]
You are super quick !!

Thanks :)

Is it possible to release this as an official nuget?
