### ISSUE TITLE
[SCIM] upgrading to EF6 with 2.0.14

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#308]
Hello,

I am trying to upgrade my SCIM server to EF6 using 2.0.14.

One of my UTs fail.
How to reproduce:
1. POST a user
2. POST a group with the user in it
3. PATCH the group's name to a different `displayName`
4. GET the user

The returned user contains 2 group objects instead of 1.
One with the PATCHed `displayName`, and the other one with null `displayName`.

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

The issue is fixed in the branch "release/v2.0.15". 
There is still an issue with the change trakcer of EFCore6 :(. 
I made a small modification to force the change tracker to set the EntityState to "Updated" when reference attributes are changed.

KR,

Sid

**Comment by danflomin** [comment]
Thank you!

Can you please create a preview nuget for v2.0.15?

Kind regards
Dan

**Comment by simpleidserver** [comment]
A preview version is available here : https://www.myget.org/feed/advance-ict/package/nuget/SimpleIdServer.Scim.Persistence.EFNet6 version 2.0.15-ci-00320.

**Comment by danflomin** [comment]
I checked it and all my UTs pass now.

Thanks !
