### ISSUE TITLE
Schema attributes should be case insensitive

### ISSUE THREAD

**Issue by andreidabryian** [simpleidserver/SimpleIdServer#319]
When I send POST request with body:
```json
{
    "UserName": "UserName123",
    "Active": true,
    "DisplayName": "BobIsAmazing",
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
  "externalId": "${__UUID}",
    "name": {
        "formatted": "Ryan Leenay",
        "familyName": "Leenay",
        "givenName": "Ryan"
    },
    "emails": [
        {
            "Primary": true,
            "type": "work",
            "value": "testing@bob.com"
        },
        {
            "Primary": false,
            "type": "home",
            "value": "testinghome@bob.com"
        }
    ]
}
```
I get an error:
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": "400",
    "scimType": "invalidValue",
    "detail": "required attributes urn:ietf:params:scim:schemas:core:2.0:User:userName are missing"
}
```
If change UserName to userName, it returns a similar error about the next attribute.

I see that according to [RFC 7643](https://datatracker.ietf.org/doc/html/rfc7643) "attribute names are case insensitive":
![image](https://user-images.githubusercontent.com/93668324/187908455-60d7656c-45d9-4223-93fc-38796949f9c0.png)

**Comment by simpleidserver** [comment]
Hello,

Indeed there is an issue. Some changes have been made in the `master` branch and attribute names are case insensitive.
I'll release a pre-release package tomorrow as soon as MYGET is available :).

KR,

SID

**Comment by simpleidserver** [comment]
The pre-relase package version "2.0.17-ci-00341" is available here : 

https://www.myget.org/feed/advance-ict/package/nuget/SimpleIdServer.Scim

**Comment by andreidabryian** [comment]
Thanks a lot!
And how long should we wait the release 2.0.17?
