### ISSUE TITLE
.search support

### ISSUE THREAD

**Issue by bzuidgeest** [simpleidserver/SimpleIdServer#32]
Section 3.4.3.  Querying Resources Using HTTP POST speaks about doing post request for search when .search is appended to the URL. When I do this I get a 404. So either I'm doing this wrong or its not implemented yet. Could you tell me if this should work? 

If this is not implemented yet, no worries I can use URL parameters for search with get request

**Comment by simpleidserver** [comment]
Indeed the ".search" operation is not supported by **SimpleIdServer.Scim** project. 
We will include this feature in the next release :).

**Comment by bzuidgeest** [comment]
Thank you, at least its not me doing something wrong then :)

**Comment by simpleidserver** [comment]
The feature is available !
You can test it with a pre-released version of the Nuget package available on the feed https://www.myget.org/F/advance-ict/api/v3/index.json :) (version : 1.1.3-ci-00068)
