### ISSUE TITLE
[SCIM] added\removed reference event

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#324]
Hello,

I am trying to utilize the User representation found on top of the published MassTransit events.

I noticed that if a user is added or removed from a group, then the representation that is attached to the event is not updated.
Meaning, if I remove a user from a group, then the user representation will still have the group that he is not longer a member of.

Can we fix this so that the representations attached to these events will be updated?

Kind regards,
Dan

**Comment by simpleidserver** [comment]
Hello,

I used the latest version "2.0.17" and I couldn't reproduce the issue on my local machine.

Following scenarios have been executed without error.

1. Add a user to a group:

HTTP REQUEST 

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "add",
      "path": "members",
      "value": {
            "value": "{{userId}}"
        }
      
    }
  ]
}
```
Event received by MassTransit :

![AssignUserToGruop](https://user-images.githubusercontent.com/10213388/189630793-09c98bd7-4e6b-47e1-a006-025358ee2613.png)

The `group` attribute is present.

2. Remove a user from one group 

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "remove",
      "path": "members",
      "value": {
            "value": "{{userId}}"
        }
      
    }
  ]
}
```

Event received by MassTransit :

![RemoveUserFromGroup](https://user-images.githubusercontent.com/10213388/189630828-d1165daa-5809-4799-b2b1-8ce678286e06.png)

The `group` attribute is removed.
