### ISSUE TITLE
Wrong meta.created and meta.lastModified values in the ServiceProviderConfig

### ISSUE THREAD

**Issue by aliaksiejmaroz** [simpleidserver/SimpleIdServer#333]
There is always _"0001-01-01T00:00:00"_ in meta.**created** and meta.**lastModified** properties in the ServiceProviderConfig.

**Comment by simpleidserver** [comment]
This issue is already fixed in the `master` branch.
KR,

SID

**Comment by aliaksiejmaroz** [comment]
Now current time is displayed all the time.

**Comment by simpleidserver** [comment]
Because the `ServiceProviderConfig` is generated on the fly (for each request), the `CreateDateTime` and `UpdateDateTime` properties were updated.
We made some changes in the master branch, to set the `CreateDateTime` and `UpdateDateTime` only one time, when the application is launched.
