### ISSUE TITLE
[SCIM] add `RepresentationReferenceAttributeUpdatedEvent`

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#334]
Hello :)

How have you been?

A few months ago you added the ability to update the group name saved on a user whenever the group's name is being updated.

Update events such as this are not being published to masstransit (like adding or removing a user from a group).

Can you please add a `RepresentationReferenceAttributeUpdatedEvent` and publish it in times such as updating a group's name?

Kind regards
Dan

**Comment by simpleidserver** [comment]
Good remark :)
I made some changes in the `master` branch to publish the integration event `RepresentationReferenceAttributeUpdatedEvent` when the reference attribute is updated.

**Comment by danflomin** [comment]
This is a huge help !

Thank you

When will this be available on nuget?

**Comment by simpleidserver** [comment]
The nuget package is released :)

KR,

SID

**Comment by danflomin** [comment]
Hello,

I tried the new version and it works great with PATCH operations on groups.

When I try to PUT a group's name I do not see a reference updated event.

Am I correct?


Kind regards
Dan

**Comment by simpleidserver** [comment]
My mistake,  I didn't make the changes for the HTTP PUT request.
The issue is now fixed in the `master` branch.

KR,

SID

**Comment by danflomin** [comment]
Great! 

Thanks :)

Can you please release this as a nuget?

**Comment by simpleidserver** [comment]
The nuget package is released :)

**Comment by danflomin** [comment]
Thanks !
