### ISSUE TITLE
SCIM endpoint get representation by id doesn't handle exceptions

### ISSUE THREAD

**Issue by andrei-boika** [simpleidserver/SimpleIdServer#342]
Hi, 

I was looking through `SimpleIdServer.Scim.Api.BaseApiController` code and came across incosistency with SCIM RFC (from my point of view).
I see that almost all `Internal...` methods (e. g. `InternalAdd` or `InternalSearch`) have `try/catch` block to handle exceptions and return  corresponding response, but `InternalGet` method doesn't have exception handling.
As far as I understand, according to SCIM RFC document (https://www.rfc-editor.org/rfc/rfc7644#section-3.12) `500 Internal Server Error` response is applicable for GET endpoints, isn't it?
![image](https://user-images.githubusercontent.com/90264207/202153882-6fab2d5b-d85e-4cd7-b3b2-80f93f31f93f.png)

It it a bug? 
If yes, could you please add exception handling at least for base Exception?
If no, could you please clarify why it should work as is?

**Comment by simpleidserver** [comment]
Hello,

Indeed it is a mistake, thank you for your feedback !
The bug is fixed in the `master` branch .

KR,

SID

**Comment by andrei-boika** [comment]
Great, thank you!

When are you going to release the changes?

**Comment by simpleidserver** [comment]
Hi, the release "2.0.21" is already available.

KR,

SID
