### ISSUE TITLE
[SCIM] Error in update if the payload contains id

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#35]
If I put the id in the payload, an error occured in update method.

I know that the id is in the path, but can happens that consumer pass also the id in the payload.

Thanks.
Gabriele

**Comment by simpleidserver** [comment]
The is fixed in the branch "release/1.1.3" : https://github.com/simpleidserver/SimpleIdServer/commit/8ee094899684cf7ea9472260877cd85f315c9c4f
