### ISSUE TITLE
PATCH: No CheckRequiredAttributes for PATCH method

### ISSUE THREAD

**Issue by aliaksiejmaroz** [simpleidserver/SimpleIdServer#356]
Should be the same as for the **POST** method, because there are fields that **required** by the logic and **required** by the schema. 
In the **PATCH** method should be not possible to **UPDATE** user with an empty name/email, there should be 400 error.

**Comment by simpleidserver** [comment]
The issue is fixed in the branch "release/v2.0.22".

KR,

SID
