### ISSUE TITLE
Schemas endpoint doesn't show schemas extensions (like extension:enterprise:2.0:User)

### ISSUE THREAD

**Issue by andreidabryian** [simpleidserver/SimpleIdServer#369]
1. urn:ietf:params:scim:schemas:core:2.0:User and urn:ietf:params:scim:schemas:extension:enterprise:2.0:User schemas are used

2. /ResourceTypes endpoint returns the next object. As you can see there is a schema extension “urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "totalResults": 1,
    "itemsPerPage": 1,
    "startIndex": 1,
    "Resources": [
        {
            "schemas": [
                "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
            ],
            "id": "User",
            "name": "User",
            "description": "User Schema",
            "endpoint": "/Users",
            "schema": "urn:ietf:params:scim:schemas:core:2.0:User",
            "schemaExtensions": [
                {
                    "schema": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
                    "required": false
                }
            ],
            "meta": {
                "location": "http://test.ips.dev.sharedsvcs.system-monitor.com/ResourceTypes/User",
                "resourceType": "ResourceType"
            }
        }
    ]
}
```
3. When getting info from /Schemas endpoint, there is no information about schema extension “urn:ietf:params:scim:schemas:extension:enterprise:2.0:User“ , there is only basic schema for users “urn:ietf:params:scim:schemas:core:2.0:User“

Looks like the schemas endpoint should return all used schemas in the application including extensions, at least in the rfc example it exists https://www.rfc-editor.org/rfc/rfc7643#section-8.7

![image](https://user-images.githubusercontent.com/93668324/208690025-254590a5-8828-45d8-a651-e7e92d3bc178.png)
![image](https://user-images.githubusercontent.com/93668324/208690078-a5948a2f-5d14-4918-865b-bac5378d54fe.png)

**Comment by simpleidserver** [comment]
Hello,

In the current implementation of the `Schemas` endpoint, all the schemas registered in your local DB are returned by the endpoint (Table is `dbo.SCIMSchemaLst`).
Can-you please check if your schema is registered in your table (`dbo.SCIMSchemaLst`) ?

KR,

SID

**Comment by andreidabryian** [comment]
I don't use database at all, all schemas are loaded in memory

**Comment by simpleidserver** [comment]
First sorry for my late reply, I'm working a lot on the next version of SimpleIdServer and I didn't have the time to work on the bugs reported for the next release `2.0.24`.
This issue is only present for `in memory` implementation & I'm going to fix it.

KR,

SID

**Comment by simpleidserver** [comment]
Sorry again for my late reply. 
If you are using the InMemory implementation then don't forget to add extension schemas into the `AddSchema` method.
For example:

```
var userSchema = SCIMSchemaExtractor.Extract(Path.Combine(basePath, "UserSchema.json"), SCIMResourceTypes.User, true);
var enterpriseUserSchema = SCIMSchemaExtractor.Extract(Path.Combine(basePath, "EnterpriseUserSchema.json"), SCIMResourceTypes.User);
userSchema.SchemaExtensions.Add(new SCIMSchemaExtension
 {
   Id = Guid.NewGuid().ToString(),
   Schema = enterpriseUserSchema.Id
});
var schemas = new List<SCIMSchema>
{
  userSchema,
  enterpriseUserSchema
};
services.AddSIDScim().AddSchemas(schemas);
```

KR,

SID

**Comment by andreidabryian** [comment]
This helped to solve the problem. Thanks! 
Thus it is not a bug
