### ISSUE TITLE
[SCIM] GetAbsoluteUriWithVirtualPath and https

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#37]
I saw that the https is managed with this line:

if (requestMessage.IsHttps)
....

But in our scenario we have a load balancing and 2 scim server that coomunicate in http, So in this case the request is in http and not https, but load balancer expose the api in https.

Thanks.

**Comment by simpleidserver** [comment]
I suppose you are using NGINX as a proxy server. If it's the case, your SCIM server must be configured to accept and treat the "**X-Forwarded-Proto**" HTTP header.
When the header is received from NGINX, the property "**HttpContext.Request.Scheme**" is updated with the received value and the code "**requestMessage.IsHttps**" will work.
For more information you can always refer to the documentation https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

To configure your host project follow the steps below :

1. Open the Startup.cs file, add the following code in the **ConfigureServices** method:


```
    services.Configure<ForwardedHeadersOptions>(options =>
    {
        options.ForwardedHeaders = 
            ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    });
```

2. Add the following line in the **Configure** method :

```
app.UseForwardedHeaders();

```

3. Update your nginx configuration file, it should looks to something like this :

```
location /scim {
		proxy_pass http://localhost:51724;
                 ....
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
```
