### ISSUE TITLE
PATH with Replace with multiple value properties with one being externalId doesn't replace other values

### ISSUE THREAD

**Issue by tharidu** [simpleidserver/SimpleIdServer#377]
I observed when PATCHING a SCIM resource with replace operation, if we provide multiple values and one is externalId, simpleid doesn't patch other properties.  
```
"op": "replace",
"value": {
  "displayName": "newValue",
  "externalId": "newExternalId"
}
```

So, in above example it doesn't patch `displayName` property. This is due to behavior in https://github.com/simpleidserver/SimpleIdServer/blob/master/src/Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs#L281. Any reason why it `continue`?

Thanks!

**Comment by simpleidserver** [comment]
Hello, indeed it is a small issue 😥
The continue statement has been removed and the issue is fixed in the master branch.

Kr,

Sid

**Comment by tharidu** [comment]
Seems like the fix has introduced a bug where if the REPLACE or ADD operation have only `externalId` it will fail. It throws `SCIMNoTargetException`

**Comment by tharidu** [comment]
Hi again. It looks like its fixed now. Thanks for the quick fix!
