### ISSUE TITLE
Add operation success with "    " (whiteSpaces) property value.

### ISSUE THREAD

**Issue by IlyaAbramau** [simpleidserver/SimpleIdServer#379]
Hello. The Adding operation fails with empty value property, but for series of whitespaces it works.
For the validation cases we can assume that the empty value and whitespaces values are very similar, so we can check for both of them.

Please, see SimpleIdServer.Scim.Extensions.JObjectExtensions class, method HasNotEmptyElement (called from CheckRequiredAttributes)
<img width="591" alt="image" src="https://user-images.githubusercontent.com/118731468/213482970-5cda5030-a5f1-46df-a35c-a9437ea12061.png">

possible solution: the 35's line can be fixed to: `return !string.IsNullOrWhiteSpace(value);` Optionally, the method HasNotEmptyElement can be renamed to HasElement :)

**Comment by simpleidserver** [comment]
Hello,

First thank you for your feedback :)
Your solution solve the problem, when required attributes contain whitespace, they are considered as empty.
I made some modifications in the `master` branch to fix this issue.

KR,

SID

**Comment by IlyaAbramau** [comment]
Thank you!
