### ISSUE TITLE
[SCIM] Resource type shouldn't be plural

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#38]
Hello,

the resource type is in plural:

public static SCIMSchemaBuilder Create(string id, string name, string resourceType,
![image](https://user-images.githubusercontent.com/10979448/81053051-cea6e600-8ec4-11ea-84f7-3f06d9eadc61.png)

Bu I think that should be "Resource Type" and "User".

Regards.

**Comment by simpleidserver** [comment]
The issue is fixed.
A pre-released version of the nuget package is available on the feed https://www.myget.org/F/advance-ict/api/v3/index.json :) (version : 1.1.3-ci-00068)
