### ISSUE TITLE
.search not working as expected.

### ISSUE THREAD

**Issue by bzuidgeest** [simpleidserver/SimpleIdServer#41]
I was testing .search endpoint and I seem to have some trouble with the filter command.

posting to /EduUsers/.search with
 {
     "schemas": ["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],
     "attributes": ["externalId"]
   }

gives response:

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:ListResponse"
  ],
  "totalResults": 1,
  "itemsPerPage": 100,
  "startIndex": 1,
  "Resources": [
    {
      "externalId": "123ddfs457@magis.main"
    }
  ]
}

Using:
 {
     "schemas": ["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],
     "attributes": ["externalId"],
     "filter": [
     	"externalId eq 123ddfs457@magis.main"
       ]
   }
gives me:

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:ListResponse"
  ],
  "totalResults": 0,
  "itemsPerPage": 100,
  "startIndex": 1,
  "Resources": []
}

The expected result would be the exact same response both times as there is only this single item in the test db.

**Comment by simpleidserver** [comment]
According to the RFC "https://tools.ietf.org/html/rfc7644#section-3.4.3", the **filter** parameter must be specified as a string and not as an array.
Can-you try with the following request ?

```
{
"schemas": ["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],
"attributes": ["externalId"],
"filter": "externalId eq 123ddfs457@magis.main"
}
```

**Comment by bzuidgeest** [comment]
You seem to be correct. It works when passed as string. Thanks for looking it over.
