### ISSUE TITLE
[SCIM] query a group id on the users controller and vice versa returns the resource

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#422]
Hello,

I noticed that in 2.0.25, I can do the following:

- Assume we have a group with `group-id` and a user with `user-id`.
- I can query `groups/user-id` and `users/group-id` and it returns data.

Kind regards
Dan

**Comment by simpleidserver** [comment]
The issue is fixed in the branch `release/2.1.0`.

KR,

SID

**Comment by simpleidserver** [comment]
Hello,

The Nuget Package version 3.0.0 is available, it contains the modifications made on the branch `release\2.1.0`.

KR,

SID
