### ISSUE TITLE
search not functioning to spec.

### ISSUE THREAD

**Issue by bzuidgeest** [simpleidserver/SimpleIdServer#45]
Looking at paragraph 3.4.2 of the spec, It says that on search (and maybe elsewhere) the "Id" of an object should always be returned. This seems not to be the case in simpleIdserver at the moment. Could this be fixed?

I have put the relevant line in bold letters below.

3.4.2.  Query Resources

   The SCIM protocol defines a standard set of query parameters that can
   be used to filter, sort, and paginate to return zero or more
   resources in a query response.  Queries MAY be made against a single
   resource or a resource type endpoint (e.g., "/Users"), or the service
   provider Base URI.  SCIM service providers MAY support additional
   query parameters not specified here and SHOULD ignore any query
   parameters they do not recognize instead of rejecting the query for
   versioning compatibility reasons.

[......]

   GET /Users?attributes=userName
   Host: example.com
   Accept: application/scim+json
   Authorization: Bearer h480djs93hd8

   The following is an example response to the query above:

   HTTP/1.1 200 OK
   Content-Type: application/scim+json

   {
     "schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],
     "totalResults":2,
     "Resources":[
       {
         "id":"2819c223-7f76-453a-919d-413861904646",
         "userName":"bjensen"
       },
       {
         "id":"c75ad752-64ae-4823-840d-ffa80929976c",
         "userName":"jsmith"
       }
     ]
   }

   **Note that in the above example, "id" is returned because the "id"
   attribute has the "returned" characteristic of "always".**

for now it works when I put the atttribute Id in the attribute list, but we are working with a third party that has a system that does not do so and fails. I cannot ask them to adjust if this is a spec violation.

**Comment by simpleidserver** [comment]
We are going to fix this issue

**Comment by bzuidgeest** [comment]
Well can't argue with that. You've been quite fast with fixes in the past. If you don't mind me asking. Do you have a estimated timeframe for the fix / version 1.1.5?

**Comment by simpleidserver** [comment]
The bug is fixed and the package 1.1.5 is available :) https://github.com/simpleidserver/SimpleIdServer/commit/aaf80d8274b0f38cfe8aa7636391b89a7a412207

**Comment by bzuidgeest** [comment]
As always, awesome. Just tested and seems to work.
