### ISSUE TITLE
PATCH: missing validation of required fields for Remove operation

### ISSUE THREAD

**Issue by aliaksiejmaroz** [simpleidserver/SimpleIdServer#461]
Validation should be the same as for `Add` and `Replace` (400 status code) if no value presented. I believe the thing is in `/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs` line:
```
if (SCIMFilterParser.DontContainsFilter(patch.Path) && patch.Value != null)
{
...
}
```

**Comment by simpleidserver** [comment]
Hello,

First thank you for reporting this bug :)
The issue is fixed in the branch `release/3.0.3`.
Required & Readonly attributes cannot be removed.

KR,

SID
