### ISSUE TITLE
problem with duplicate nested attributes in output of webservice

### ISSUE THREAD

**Issue by bzuidgeest** [simpleidserver/SimpleIdServer#47]
Hi,

I think I may have found a bug. (I'm using version 1.1.5)

When I do a request like so:
post to eduuser endpoint
{
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:nleducation:1.0:eduuser"
    ],
    "eckId": "https://eckid.nl/abcdef",
    "externalId": "bob@magis.main",
    "name": {
        "givenName": "bob",
        "familyName": "Achternaam"
    }
}
result:
{
    "id": "ce3c99b9-5f17-472e-bb58-d779fe603117",
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:nleducation:1.0:eduuser"
    ],
    "meta": {
        "resourceType": "eduUsers",
        "created": "2020-09-04T12:38:15.9166424Z",
        "lastModified": "2020-09-04T12:38:15.9166424Z",
        "version": "31a5696d-a553-4c3d-8bf2-0bee3aa1f854",
        "location": "http://xxxxxxx.nl/eduUsers/ce3c99b9-5f17-472e-bb58-d779fe603117"
    },
    "externalId": "bob@magis.main",
    "eckId": "https://eckid.nl/abcdef",
    "name": {
        **"givenName": "bob",
        "familyName": "Achternaam"**
    }
}
This is as expected. nothing wrong there. But then I try to request the object back
get xxx.nl/EduUsers/ce3c99b9-5f17-472e-bb58-d779fe603117
result:
{
    "id": "ce3c99b9-5f17-472e-bb58-d779fe603117",
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:nleducation:1.0:eduuser"
    ],
    "meta": {
        "resourceType": "eduUsers",
        "created": "2020-09-04T12:38:15.9166424",
        "lastModified": "2020-09-04T12:38:15.9166424",
        "version": "31a5696d-a553-4c3d-8bf2-0bee3aa1f854",
        "location": "xxxxx.nl/eduUsers/ce3c99b9-5f17-472e-bb58-d779fe603117"
    },
    "externalId": "bob@magis.main",
    **"givenName": "bob",
    "familyName": "Achternaam",**
    "name": {
        **"givenName": "bob",
        "familyName": "Achternaam"**
    }
}
Note here that the givenname and familyname are duplicated. The child attributes are also added to the root object. 
Here is the schema as output by the schema endpoint for eduUser
{
    "id": "urn:ietf:params:scim:schemas:extension:nleducation:1.0:eduuser",
    "name": "eduUser",
    "description": "SCIM extended resource for representing users for digital educational content in the Netherlands",
    "attributes": [
        {
            "name": "name",
            "type": "complex",
            "multiValued": false,
            "description": "A complex type containing the name of the EduUser",
            "required": true,
            "caseExact": false,
            "mutability": "readwrite",
            "returned": "default",
            "uniqueness": "none",
            "subAttributes": [
                {
                    "name": "familyName",
                    "type": "string",
                    "multiValued": false,
                    "description": "The surname of the EduUser, including prefixes like 'van' or 'van der'",
                    "required": true,
                    "caseExact": false,
                    "mutability": "readwrite",
                    "returned": "always",
                    "uniqueness": "none"
                },
                {
                    "name": "givenName",
                    "type": "string",
                    "multiValued": false,
                    "description": "The given name of the EduUser",
                    "required": true,
                    "caseExact": false,
                    "mutability": "readwrite",
                    "returned": "always",
                    "uniqueness": "none"
                }
            ]
        },
        {
            "name": "eckId",
            "type": "string",
            "multiValued": false,
            "description": "The unique identification of the user for digital content",
            "required": true,
            "caseExact": false,
            "mutability": "readwrite",
            "returned": "request",
            "uniqueness": "global"
        },
        {
            "name": "externalId",
            "type": "string",
            "multiValued": false,
            "description": "The identifaction of the user as defined by Kennisnet: nlEduPersonRealId",
            "required": false,
            "caseExact": true,
            "mutability": "readwrite",
            "returned": "always",
            "uniqueness": "global"
        }
    ]
}

I only noticed this when we started sending update request on objects. We get foreignkey constraint errors on
FK_SCIMRepresentationAttributeLst_SCIMRepresentationAttributeLst_ParentId
I expect it's not the key that is the problem but the scimserver messing up with the "mysterious" extra attributes.

Could you look in to this for me?

**Comment by bzuidgeest** [comment]
I set logging to info level and did some checking of the generated queries when requesting an eduuser object.

These are some of the queries entitity framework executes (I pasted in the proper parameter values)

SELECT TOP(1) [s].[Id], [s].[Created], [s].[ExternalId], [s].[LastModified], [s].[ResourceType], [s].[Version]
      FROM [SCIMRepresentationLst] AS [s]
      WHERE ([s].[Id] = 'ce3c99b9-5f17-472e-bb58-d779fe603117') AND ([s].[ResourceType] = 'eduUsers')
      ORDER BY [s].[Id]

 SELECT [s.Attributes].[Id], [s.Attributes].[ParentId], [s.Attributes].[RepresentationId], [s.Attributes].[SchemaAttributeId], [s.SchemaAttribute].[Id], [s.SchemaAttribute].[CanonicalValues], [s.SchemaAttribute].[CaseExact], [s.SchemaAttribute].[DefaultValueInt], [s.SchemaAttribute].[DefaultValueString], [s.SchemaAttribute].[Description], [s.SchemaAttribute].[MultiValued], [s.SchemaAttribute].[Mutability], [s.SchemaAttribute].[Name], [s.SchemaAttribute].[ParentId], [s.SchemaAttribute].[ReferenceTypes], [s.SchemaAttribute].[Required], [s.SchemaAttribute].[Returned], [s.SchemaAttribute].[SchemaId], [s.SchemaAttribute].[Type], [s.SchemaAttribute].[Uniqueness]
      FROM [SCIMRepresentationAttributeLst] AS [s.Attributes]
      LEFT JOIN [SCIMSchemaAttributeModel] AS [s.SchemaAttribute] ON [s.Attributes].[SchemaAttributeId] = [s.SchemaAttribute].[Id]
      INNER JOIN (
          SELECT TOP(1) [s0].[Id]
          FROM [SCIMRepresentationLst] AS [s0]
           WHERE ([s0].[Id] = 'ce3c99b9-5f17-472e-bb58-d779fe603117') AND ([s0].[ResourceType] = 'eduUsers')
          ORDER BY [s0].[Id]
      ) AS [t] ON [s.Attributes].[RepresentationId] = [t].[Id]
      ORDER BY [t].[Id], [s.Attributes].[Id]

SELECT [s.Attributes.Values].[Id], [s.Attributes.Values].[SCIMRepresentationAttributeId], [s.Attributes.Values].[ValueBoolean], [s.Attributes.Values].[ValueDateTime], [s.Attributes.Values].[ValueInteger], [s.Attributes.Values].[ValueReference], [s.Attributes.Values].[ValueString]
      FROM [SCIMRepresentationAttributeValueLst] AS [s.Attributes.Values]
      INNER JOIN (
          SELECT DISTINCT [s.Attributes0].[Id], [t0].[Id] AS [Id0]
          FROM [SCIMRepresentationAttributeLst] AS [s.Attributes0]
          LEFT JOIN [SCIMSchemaAttributeModel] AS [s.SchemaAttribute0] ON [s.Attributes0].[SchemaAttributeId] = [s.SchemaAttribute0].[Id]
          INNER JOIN (
              SELECT TOP(1) [s1].[Id]
              FROM [SCIMRepresentationLst] AS [s1]
               WHERE ([s1].[Id] = 'ce3c99b9-5f17-472e-bb58-d779fe603117') AND ([s1].[ResourceType] = 'eduUsers')
              ORDER BY [s1].[Id]
          ) AS [t0] ON [s.Attributes0].[RepresentationId] = [t0].[Id]
      ) AS [t1] ON [s.Attributes.Values].[SCIMRepresentationAttributeId] = [t1].[Id]
      ORDER BY [t1].[Id0], [t1].[Id]


	 SELECT [s.Attributes.Children].[Id], [s.Attributes.Children].[ParentId], [s.Attributes.Children].[RepresentationId], [s.Attributes.Children].[SchemaAttributeId], [s.SchemaAttribute1].[Id], [s.SchemaAttribute1].[CanonicalValues], [s.SchemaAttribute1].[CaseExact], [s.SchemaAttribute1].[DefaultValueInt], [s.SchemaAttribute1].[DefaultValueString], [s.SchemaAttribute1].[Description], [s.SchemaAttribute1].[MultiValued], [s.SchemaAttribute1].[Mutability], [s.SchemaAttribute1].[Name], [s.SchemaAttribute1].[ParentId], [s.SchemaAttribute1].[ReferenceTypes], [s.SchemaAttribute1].[Required], [s.SchemaAttribute1].[Returned], [s.SchemaAttribute1].[SchemaId], [s.SchemaAttribute1].[Type], [s.SchemaAttribute1].[Uniqueness]
      FROM [SCIMRepresentationAttributeLst] AS [s.Attributes.Children]
      LEFT JOIN [SCIMSchemaAttributeModel] AS [s.SchemaAttribute1] ON [s.Attributes.Children].[SchemaAttributeId] = [s.SchemaAttribute1].[Id]
      INNER JOIN (
          SELECT DISTINCT [s.Attributes1].[Id], [t2].[Id] AS [Id0]
          FROM [SCIMRepresentationAttributeLst] AS [s.Attributes1]
          LEFT JOIN [SCIMSchemaAttributeModel] AS [s.SchemaAttribute2] ON [s.Attributes1].[SchemaAttributeId] = [s.SchemaAttribute2].[Id]
          INNER JOIN (
              SELECT TOP(1) [s2].[Id]
              FROM [SCIMRepresentationLst] AS [s2]
              WHERE ([s2].[Id] = 'ce3c99b9-5f17-472e-bb58-d779fe603117') AND ([s2].[ResourceType] = 'eduUsers')
              ORDER BY [s2].[Id]
          ) AS [t2] ON [s.Attributes1].[RepresentationId] = [t2].[Id]
      ) AS [t3] ON [s.Attributes.Children].[ParentId] = [t3].[Id]
      ORDER BY [t3].[Id0], [t3].[Id], [s.Attributes.Children].[Id]

I attached an file with the output of these queries
[scim output.txt](https://github.com/simpleidserver/SimpleIdServer/files/5175137/scim.output.txt)

I notice that both the second and the fourth queries return the attributes givenName and familyName. The strange thing is this also happens when requesting the schema thru the schema endpoint. So for now my assumption is that the schema endpoint controller does some magic to filter some of the attributes out.
I also noticed that when creating a new eduUser the response to the request also has properly formatted output with no extra attributes. But when I do a get for that attribute they are there again. So I surmise that either the queries are wrong (mostly the second) or some controllers are missing filtering.

**Comment by simpleidserver** [comment]
We will investigate your problem asap

**Comment by bzuidgeest** [comment]
I checked out the git code and combined that with a copy of my project (The project normally uses the nuget packages)

I did some debugging and code changes below seem to fix things. 
* It removes the duplicate attribute. But I'm not sure of the side effects outside my particular use case. I don't have a full picture of how things are processed when there is more then 1 level of property nesting. 
* As a secondary thing it also fixed the fact that externalId is ignored on a update. ExternalId is a property that can be modified, but it is not an attribute and so was not included in the normal update. I guess it should be treated separate like the changedate.

Hope this helps somewhat in fixing things. I don't want to push things, but it would be nice to have a fixed nuget this week.


diff --git a/src/Scim/SimpleIdServer.Scim.Persistence.EF/Extensions/MappingExtensions.cs b/src/Scim/SimpleIdServer.Scim.Persistence.EF/Extensions/MappingExtensions.cs
index 76181ab..b70133a 100644
--- a/src/Scim/SimpleIdServer.Scim.Persistence.EF/Extensions/MappingExtensions.cs
+++ b/src/Scim/SimpleIdServer.Scim.Persistence.EF/Extensions/MappingExtensions.cs
@@ -148,7 +148,8 @@ namespace SimpleIdServer.Scim.Persistence.EF.Extensions
                 ResourceType = representation.ResourceType,
                 Id = representation.Id,
                 Schemas = representation.Schemas.Select(s => ToDomain(s.Schema)).ToList(),
-                Attributes = representation.Attributes.Select(s =>
+                Attributes = representation.Attributes.Where(x => x.ParentId == null).Select(s =>
+                //Attributes = representation.Attributes.Select(s =>
                 {
                     return ToDomain(s);
                 }).ToList()                
diff --git a/src/Scim/SimpleIdServer.Scim/Commands/Handlers/ReplaceRepresentationCommandHandler.cs b/src/Scim/SimpleIdServer.Scim/Commands/Handlers/ReplaceRepresentationCommandHandler.cs
index 88e8e59..6e57fa9 100644
--- a/src/Scim/SimpleIdServer.Scim/Commands/Handlers/ReplaceRepresentationCommandHandler.cs
+++ b/src/Scim/SimpleIdServer.Scim/Commands/Handlers/ReplaceRepresentationCommandHandler.cs
@@ -67,6 +67,7 @@ namespace SimpleIdServer.Scim.Commands.Handlers
                 }
             }
 
+            existingRepresentation.SetExternalId(updatedRepresentation.ExternalId);
             existingRepresentation.SetUpdated(DateTime.UtcNow);
             using (var transaction = await _scimRepresentationCommandRepository.StartTransaction())
             {
diff --git a/src/Scim/SimpleIdServer.Scim/Domain/SCIMRepresentation.cs b/src/Scim/SimpleIdServer.Scim/Domain/SCIMRepresentation.cs
index 62c4b2d..e688ae5 100644
--- a/src/Scim/SimpleIdServer.Scim/Domain/SCIMRepresentation.cs
+++ b/src/Scim/SimpleIdServer.Scim/Domain/SCIMRepresentation.cs
@@ -75,6 +75,11 @@ namespace SimpleIdServer.Scim.Domain
             LastModified = lastModified;
         }
 
+        public void SetExternalId(string externalId)
+        {
+            ExternalId = externalId;
+        }
+
         public void SetVersion(string version)
         {
             Version = version;

**Comment by simpleidserver** [comment]
Thank you for your investigation, both bugs have been fixed and the release 1.1.6 is available.

**Comment by bzuidgeest** [comment]
Looks like its fixed. Thank!.
