### ISSUE TITLE
SCIM Attribute Data Types 

### ISSUE THREAD

**Issue by boris-meerovich-sp** [simpleidserver/SimpleIdServer#48]
Hi,
I'm wondering how can I set attributes values to decimal numbers or binary data?
According to SCIM [RFC](https://tools.ietf.org/html/rfc7643#section-2.3) there is decimal and binary values should be supported.
In SCIMRepresentationAttribute class there are only:

- string
- bool
- int
- DateTime

Also, how can I set null to ValuesDateTime property?
Maybe it should be define as 
public ICollection<DateTime?> ValuesDateTime { get; set; }

Please, advise

**Comment by simpleidserver** [comment]
Hi,

Indeed the Decimal and Binary types are not supported, we will include them in the next release (v1.1.7).

Why do you want to set null to ValuesDateTime property ?
If the SCIM representation doesn't contain valid DateTime property then the collection ValuesDateTime will be empty.

**Comment by boris-meerovich-sp** [comment]
Hi,
Thanks for the quick reply!!!
This is good news according to the next release? What's the time estimation for v1.1.7?

I've tried to add DateTime property with empty value, but got exception in SCIMRepresentationExtensions.cs (row:444)
System.InvalidOperationException: 'Sequence contains no elements'
for representationAttr.ValuesDateTime.First() code...

The ValuesDateTime field is empty, thus the exception is thrown.
I need that the DateTime field value will be null or empty...

**Comment by simpleidserver** [comment]
We are going to investigate your problem.
The next release will be ready next week (29 september).

**Comment by boris-meerovich-sp** [comment]
Thanks!!!

**Comment by abhishekkandi** [comment]
@simpleidserver Can you guys provide add user, update group samples?? Having a hard time to find one.

**Comment by simpleidserver** [comment]
@abhishekkandi : We don't provide a client to make HTTP request against the SCIM endpoint.
You can find samples in the acceptance test project : https://github.com/simpleidserver/SimpleIdServer/blob/master/tests/SimpleIdServer.Scim.Host.Acceptance.Tests/Features/Users.feature. For example, the first scenario describes how to create a user.

Otherwise, we add some samples in the directory : https://github.com/simpleidserver/SimpleIdServer/tree/release/1.1.7/src/Scim/FiddleRequests

**Comment by simpleidserver** [comment]
@boris-meerovich-sp  A pre-released version of the SCIM project has been published. Can-you please check if you still have the exception ? The types "binary" and "decimal" are now supported.
The nuget package is here : https://www.myget.org/feed/advance-ict/package/nuget/SimpleIdServer.Scim (version 1.1.7-ci-00146)

**Comment by abhishekkandi** [comment]
@simpleidserver Can you suggest me any scim client packages. If you know one.

**Comment by simpleidserver** [comment]
I don't know a valid SCIM client.
We can write one if we have some times (ticket  : https://github.com/simpleidserver/SimpleIdServer/issues/49)

**Comment by abhishekkandi** [comment]
Thanks, @simpleidserver. That'd be great not just to me but many other fellow developers.

**Comment by boris-meerovich-sp** [comment]
@simpleidserver I checked the new pre-released version and here are my conclusions:

- Can add decimal/binary data types
- Decimal values: Can you please add to SCIMSchemaAttributeBuilder.cs AddDecimalAttribute()  method?
- DateTime: Empty values collection exception is not thrown anymore

Thanks for a quick fix!!!
