### ISSUE TITLE
Extract DID Document

### ISSUE THREAD

**Issue by simpleidserver** [simpleidserver/SimpleIdServer#482]
* Deploy DID Contract : DONE
* Create Identity Document with one service endpoint : DONE
* Read Identity Document (with one service) from ethr : DONE
* Check JWT Token with DID Document : DONE
* Add and read veriKey : DONE

https://github.com/decentralized-identity/ethr-did-resolver/blob/master/doc/did-method-spec.md#public-keys

Support some key : https://w3c-ccg.github.io/ld-cryptosuite-registry/

**Comment by lechediaz** [comment]
Excuse me, I downloaded the branch 'release/v3.0.4' and I got error with **Nethereum** cannot resolve the dependency and I had to install .NET 5. I've been reading and **Nethereum** is for use _Ethereum_ a cryptocoin. why we need that in an OpenID server?

I want to work on issue #484 but actual branch blocks me and don't understand the using of **Nethereum**.

**Comment by simpleidserver** [comment]
I rolled back the branch "release/v3.0.4". DID projects are excluded from the solution.
Can-you please fetch the latest changes from "release/v3.0.4" and try again ?

The Nuget Package "Nethereum" will be used by our DID project in order to get a Distributed Identity Document from the blockchain. This change is required to support Digital Wallet.

**Comment by lechediaz** [comment]
Thank you, I'll try later.

I have a question, that Digital Wallet will be another product and not be part of idserver, right?

Because if will be part of OIDC provider server I suggest that could be optional and not required, maybe added as extension.

And I have a suggestion, about work on issues with branchs that born from release branch, so you could work in you issue and I in mine. At the end issues branch should be merged to release branch.

**Comment by simpleidserver** [comment]
By default, SimpleIdServer will not be configured to use `SimpleIdServer.Did` project.

All the logic will be located into separate projects :
* `SimpleIdServer.Did` : Contains the logic to parse and Generate Distributed Identity Document (DID). By default, DID will be stored into a blockchain for example ether.
* `SimpleIdServer.Did.Jwt` : Contains the logic to validate JWT token against DID.

About your last suggestion, I already create a branch named `DID`. It contains all the modifications made to support DID & Digital wallet.

**Comment by lechediaz** [comment]
Understood, thank you for explaining it.

**Comment by lechediaz** [comment]
"By the way, the ‘release/v3.0.4’ branch now compiles well.
