### ISSUE TITLE
Multiple requirements

### ISSUE THREAD

**Issue by lechediaz** [simpleidserver/SimpleIdServer#483]
Hello! I have been watching your project and it is very interesting, congratulations! I come from working with Identity Server 4 and the user interface that you developed is great, but in my personal project I have multiple requirements to be able to use it (these requirements affect both the UI and the IdServer):

- Allow create users manually at UI.
- Allow assigning roles to users.
  - The role must support "permissions" represented as claims. When a user has a role assigned, it inherits the role claims.
  - Some parts of the user interface are shown or hidden according to the associated role claims. This is because I would like some roles to be able to create users but not manage clients, for example.
  - A user could be assigned multiple roles, the claims of such roles should be combined.

I have a rough idea of how to do this, since I did something similar at another company, but I have a question regarding the repository. Are you interested in me creating these functionalities and adding them to the source code? Or should I just create a fork and create my own version?

I apologize for the question, I am new to collaborating with open source projects and would like to support them in addition to making my own modifications.

**Comment by simpleidserver** [comment]
Hello,

First thank you for your interest on the project :).

We are currently working on the `release\3.0.4` (branch release/v3.0.4). In this new version, it is already possible to Create/Add/Delete groups and assign them to a user.
Each group can be assigned to one or more Client Roles. When user's claims are built, roles are deduced from the inherited groups. Therefore the point 2.1 and 2.3 are already developed.

About the points "1" and "2.2", I create two tickets #484 : Create a user and Ticket #485 : Secure a website.
All contributions are welcomed ! You can create a "fork" and propose a merge request.

If you have questions about the repository, feel-free to ask questions.

KR,

SID


In the new version, we already developed a UI, which
