### ISSUE TITLE
[SCIM] userName attribute should be case insensitive

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#489]
Hello, how are you?

In RFC 7643 is is stated the the userName attribute is case insensitive.
When filtering on a username with a different case, it does not work.

See attached screenshot.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/33806717/234803584-4b70ecb3-8a5a-420d-8ad5-95163d2cdbec.png">

I'd like your assistance with a fix to this issue 🙏 

Kind regards
Dan

**Comment by danflomin** [comment]
I also found out that my `displayName` attribute (the name of the group) is defined as `"caseExact": false`, but when filtering on it with a different case it does not work.

**Comment by simpleidserver** [comment]
The issue should be fixed on different operations : 
* Equal : DONE
* Not Equal : DONE
* Start with : TODO
* End with : TODO
* Contains : TODO

**Comment by simpleidserver** [comment]
This bug is fixed in the branch "release/v3.0.4".
