### ISSUE TITLE
AttributeReferenceEnricher fills attributes with unexisting subattribute "id", instead of "value"?

### ISSUE THREAD

**Issue by SviatoslavVilkovych** [simpleidserver/SimpleIdServer#51]
Hello,
Please look at the next code:

						refLst.Add(new SCIMRepresentationAttribute
						{
							SchemaAttribute = new SCIMSchemaAttribute("id")
							{
								Name = "id",
								MultiValued = false,
								Type = SCIMSchemaAttributeTypes.STRING
							},
							ValuesString = new List<string>
							{
								filteredRepresentation.Id
							}
						});

I noticed that this code inserts "id", while in your SCIMConstants.cs class description of complex attributes both Group and User contains "value":
`c.AddStringAttribute("value");`

As a result, when getting **users** you will receive SCIMRepresentation with "_value_", but when the **user** returned after the update or create, it will "_id_" in its complex attributes. Same for **groups**. Is this intended or an issue?

Thanks!

**Comment by simpleidserver** [comment]
Hi,

The "id" attribute is mandatory and must be present in all SCIM representations for example : Users or Groups.
The class "AttributeReferenceEnricher" is used to add mandatory fields like "id", "display" or "$ref" into SCIM representations.
Those mandatory attributes are "normally" not inserted into sub complex attributes like "user\emails".

When a user is added :
```

POST http://localhost:60002/Users HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: localhost:60002
Content-Length: 416

{
 "schemas": [ "urn:ietf:params:scim:schemas:core:2.0:User", "urn:ietf:params:scim:schemas:extension:eid:2.0:User"],
 "userName": "loki3",
 "externalId": "externalId2",
 "name": { "formatted" : "formatted", "familyName": "familyName", "givenName": "givenName" },
"phoneNumbers": [ { "type": "mobile", "value": "01" }, { "type": "home", "value": "02" } ],
"validity": "22",
"birthDate": "25-09-20 13:35:33"
}
```
The following result is received : 

```
HTTP/1.1 201 Created
Date: Sun, 04 Oct 2020 16:53:21 GMT
Content-Type: application/scim+json
Server: Kestrel
Content-Length: 850
ETag: 76840920-7b48-4393-aaea-18b4678cc3bb
Location: http://localhost:60002/Users/53d7ef94-99b9-4f6b-93f2-f1ff3fb9dc70

{
  "id": "53d7ef94-99b9-4f6b-93f2-f1ff3fb9dc70",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User",
    "urn:ietf:params:scim:schemas:extension:eid:2.0:User"
  ],
  "meta": {
    "resourceType": "Users",
    "created": "2020-10-04T16:53:21.2108435Z",
    "lastModified": "2020-10-04T16:53:21.2108436Z",
    "version": "76840920-7b48-4393-aaea-18b4678cc3bb",
    "location": "http://localhost:60002/Users/53d7ef94-99b9-4f6b-93f2-f1ff3fb9dc70"
  },
  "externalId": "externalId2",
  "userName": "loki3",
  "name": {
    "formatted": "formatted",
    "familyName": "familyName",
    "givenName": "givenName"
  },
  "phoneNumbers": [
    {
      "type": "mobile",
      "value": "01"
    },
    {
      "type": "home",
      "value": "02"
    }
  ],
  "validity": 22.0,
  "birthDate": "2020-09-25T13:35:33"
}
```
When the new user is fetched :

```
GET http://localhost:60002/Users/53d7ef94-99b9-4f6b-93f2-f1ff3fb9dc70 HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
```


The following result is returned :

```
HTTP/1.1 200 OK
Date: Sun, 04 Oct 2020 16:53:55 GMT
Content-Type: application/scim+json
Server: Kestrel
Content-Length: 849
ETag: 76840920-7b48-4393-aaea-18b4678cc3bb
Location: http://localhost:60002/Users/53d7ef94-99b9-4f6b-93f2-f1ff3fb9dc70

{
  "id": "53d7ef94-99b9-4f6b-93f2-f1ff3fb9dc70",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User",
    "urn:ietf:params:scim:schemas:extension:eid:2.0:User"
  ],
  "meta": {
    "resourceType": "Users",
    "created": "2020-10-04T16:53:21.2108435",
    "lastModified": "2020-10-04T16:53:21.2108436",
    "version": "76840920-7b48-4393-aaea-18b4678cc3bb",
    "location": "http://localhost:60002/Users/53d7ef94-99b9-4f6b-93f2-f1ff3fb9dc70"
  },
  "externalId": "externalId2",
  "userName": "loki3",
  "birthDate": "2020-09-25T13:35:33",
  "phoneNumbers": [
    {
      "type": "home",
      "value": "02"
    },
    {
      "value": "01",
      "type": "mobile"
    }
  ],
  "name": {
    "givenName": "givenName",
    "formatted": "formatted",
    "familyName": "familyName"
  },
  "validity": 22.00
}
```

The "id" is not inserted into sub complex attributes (user\phoneNumbers).
I couldn't reproduce the error.

**Comment by SviatoslavVilkovych** [comment]
I don't know about the user\phoneNumbers, but I know that for user\groups I am getting "id" instead of "value", while I am setting "value".


        private IEnumerable<SCIMRepresentationAttribute> FillComplexGroupsAttribute(SCIMSchemaAttribute groupsAttribute, IEnumerable<ScimGroup> scimGroups)
        {
            var valueSubAttributeOfGroups = groupsAttribute.SubAttributes.Single(attr => attr.Name == ValueAttributeName);
            var refSubAttributeOfGroups = groupsAttribute.SubAttributes.Single(attr => attr.Name == RefAttributeName);
            var displaySubAttributeOfGroups = groupsAttribute.SubAttributes.Single(attr => attr.Name == DisplayAttributeName);

            var groupsScimAttributes = new List<SCIMRepresentationAttribute>();
            foreach (var group in scimGroups)
            {
                groupsScimAttributes.Add(new SCIMRepresentationAttribute(groupsAttribute.Id, groupsAttribute)
                {
                    Values = new List<SCIMRepresentationAttribute>()
                    {
                        new SCIMRepresentationAttribute(valueSubAttributeOfGroups.Id,
                                                        valueSubAttributeOfGroups,
                                                        valuesString: new List<string> { group.ObjectGuid }),
                        new SCIMRepresentationAttribute(displaySubAttributeOfGroups.Id,
                                                        displaySubAttributeOfGroups,
                                                        valuesString: new List<string> { group.DisplayName }),
                        new SCIMRepresentationAttribute(refSubAttributeOfGroups.Id,
                                                        refSubAttributeOfGroups,
                                                        valuesString: new List<string> { $"{Url}/{SCIMEndpoints.Group}/{group.ObjectGuid}" }),
                    },
                });
            }

            return groupsScimAttributes;
        }


Imagine having `IEnumerable<SCIMRepresentation>` of users with groups filled something like this. Then, during obtaining concrete user you will get model with "id", because it goes through your Enricher model, while model that will be returned after changing user will return model with "value", because it goes through CommandHandler and I am setting all the fields.
And it wouldn't be a problem, but I can't do something like this:

`
var valueSubAttributeOfGroups = groupsAttribute.SubAttributes.Single(attr => attr.Name == "id");
`

Groups attribute does not have "id" subattribute.

**Comment by simpleidserver** [comment]
Indeed it seems to be an issue. We will take a closer look and fix this issue.
Thank you for you feedback !

**Comment by simpleidserver** [comment]
The issue is fixed : https://github.com/simpleidserver/SimpleIdServer/commit/e7c5f6112b4aec61598fe9492775e76256d5ec75
