### ISSUE TITLE
[SCIM] Replace representation doesn't check uniqueness

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#510]
Hello,

I noticed that if I make a PUT to edit the user, the code doesn't take into account the uniqueness of the attribute.

I think that the call to CheckSCIMRepresentationExistsForGivenUniqueAttributes in the ReplaceRepresentationCommandHandler is missing.

Can you please check?

Regards.

**Comment by simpleidserver** [comment]
Hello,

First thank you for your contribution :)
The pull request has been merged into the branch `release\v3.0.4`.

KR,

SID

**Comment by gabrielemilan** [comment]
Ok thanks.

Can we have this version in nuget as prerelease?

**Comment by simpleidserver** [comment]
The Nuget package version 3.0.4 is available.

KR,

SID
