### ISSUE TITLE
Returning 403 status code by the GET, DELETE, POST, PATCH, PUT user endpoints

### ISSUE THREAD

**Issue by alexander-durovich-swi** [simpleidserver/SimpleIdServer#516]
Hello,

The current implementation of Internal[GET/DELETE/ADD/PATCH/UPDATE] methods in BaseApiController doesn't allow to return 403 status code.
Is it possible to add such possibility, please?
(Our provisioning service calls other internal services, and in some cases we should return 403 status code got from these internal services)

Is it possible to add the customizable possibility to return any status code?

Thank you in advance.
Best Regards,
Alex

**Comment by simpleidserver** [comment]
Some modifications have been made in the master branch.

As a developer, you can create and inherits one of the following class : 
* AddRepresentationCommandHandler : Add a representation
* DeleteRepresentationCommandHandler : Delete a representation
* PatchRepresentationCommandHandler : Patch a representation
* ReplaceRepresentationCommandHandler : Update a representation
* GetRepresentationQueryHandler : Get one representation
* SearchRepresentationsQueryHandler : Search representations.

Override the method `Handle`. This function returns a result of type `GenericResult<T>`.

You can return custom error message like this :

```
return GenericResult<SCIMRepresentation>.Error(System.Net.HttpStatusCode.InternalServerError, "errorMessage", "scimType")
```

**Comment by alexander-durovich-swi** [comment]
Hello,

Ok, I see, thank you very much!

Best Regards,
Alex
