### ISSUE TITLE
Multiple redirects when logging into simpleidserver manager (or website) deployed with Docker

### ISSUE THREAD

**Issue by lechediaz** [simpleidserver/SimpleIdServer#519]
Hi friend, I'm going to implement SimpleIdServer in a demo of an app I'm working on.

I have deployed both the SimpleIdServer server and the website that allows to manage it, but I have a problem.

I can authenticate correctly on the SimpleIdServer server, but not from the website :(

Multiple redirects occur:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/b25b3f76-3be3-4124-98dd-368656077767)

Looking at the logs of the website it is as if it did not find a Cookie (I guess the authentication cookie created by SimpleIdServer).

```
warn: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]
      '.AspNetCore.Correlation.7J9evnEhRsB3qClDRDASEgMLHDi_K8JyQLGq8RTYyMQ' cookie not found.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: An error was encountered while handling the remote login.
       ---> System.Exception: Correlation failed.
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

To deploy the containers I made some small modifications to the docker-compose file, to the psake instructions and in the StartUp project schedules. I have versioned the changes in this branch of my fork: https://github.com/lechediaz/SimpleIdServer/tree/release/v3.0.4-demo

I consider that my changes were not so drastic.

I ran `.\psake dockerBuild`, then exported the Docker images and uploaded them to my server, finally I ran another docker-compose file which is a copy of the one versioned in my branch but with the secret values in the environment variables.

Could you tell me if this error has happened to you, or how to set the SimpleIdServer Cookie, which I suspect is the problem, maybe set the `SameSite` to `Lax` value, but I don't know where to set it.

Thank you in advance

**Comment by simpleidserver** [comment]
Hello,

In the `Program.cs` file of the SimpleIdServer.IdServer.Website.Startup project, can-you please add the following line before `app.UseStaticFiles` and try again ?

```
app.UseCookiePolicy(new CookiePolicyOptions
{
    Secure = CookieSecurePolicy.Always
});
```

**Comment by simpleidserver** [comment]
Hello,

I think the authentication is not working in the administration website, because it is not hosted on HTTPS.
Cookie with "Secure" attribute can be created only by secured website , otherwise you'll receive the following error : 

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/22442223-b2ae-489d-b536-4d84d8e13b51)

**Comment by lechediaz** [comment]
Hello,

I did not see the need to deploy the administration site under the HTTPS protocol, but the SimpleIdServer server I did deploy that way.

I will take advantage that I have SSL certificate and I will try to deploy the administration site in HTTPS then.

I'll try and let you know.

Thanks.

**Comment by lechediaz** [comment]
It worked, deploying the administration site with HTTPS was no problem.

There was no need for this:

> ```
> app.UseCookiePolicy(new CookiePolicyOptions
> {
>     Secure = CookieSecurePolicy.Always
> });
> ```

greetings

**Comment by lechediaz** [comment]
Now I have another problem logging out :(

It tells me the following: 

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/dda8329e-4e3a-405e-a5af-0956b51dc578)

Message: `"subject contained in id_token_hint is invalid"`

**Comment by lechediaz** [comment]
Hello,

I think I have found the problem, the "aud" key in the JWT is not assigned:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/b2309649-828f-4ad6-85bc-a36ea553d0e6)

why can this happen, in this case I authenticated using a realm other than "master" using Postman. can that affect?

**Comment by simpleidserver** [comment]
I create a bug ticket #523 to fix the audience in the access_token.
When the `resource` parameter is missing from the HTTP request then the audience must be equals to `client_id`.
The `resource` parameter enables a client to indicate the protected resources where the requested access token will be used :)

The client `SIDS-manager` is working because the `id_token` is passed into the parameter `id_token_hint`.
I think, the `access_token` is passed and not the `id_token`, can-you please check ?

**Comment by lechediaz** [comment]
Yes, I use `access_token` to secure my API:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/d68ceb1d-7bc0-4d58-bfca-8a330eeae164)

**Comment by simpleidserver** [comment]
If I correctly understood. There is an exception in the SPA Application (condominiums) when you're clicking on the logout button, right ? 

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/dda8329e-4e3a-405e-a5af-0956b51dc578)

The issue #523 is already fixed in the master branch. Now, by default the audience of an access token will be equals to the client identifier.

**Comment by lechediaz** [comment]
Nope,

that error you're showing happened in administration website when sign out but I notice that every `access_token` created has no "aud" key, and maybe that is the reason why administration website fails to log out and my application's web API fails to validate authentication.

Do you use Discord? could show you and try to resolve together.

**Comment by lechediaz** [comment]
Hello,

I want to confirm that now the administration site lets you log out correctly.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/0409474f-effc-45f4-a490-67f4ef7dcc1e)

**Comment by lechediaz** [comment]
And I also want to tell you that happily my authorization is working!

I added an option to not validate the audience.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/ecee27cd-25b7-4e28-bfb6-da6b178133c0)

This is the generated token:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/b0d856c3-0976-4ac2-a033-12a6b5c02bcd)

Thank you very much for your support.
