### ISSUE TITLE
Swashbuckle (Swagger) for exposing SCIM API documentation

### ISSUE THREAD

**Issue by boris-meerovich-sp** [simpleidserver/SimpleIdServer#53]
I've tried to add support for [Swagger ](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#customize-and-extend)UI to expose API documentation with fancy UI.

I can see all end-point in the UI and event envoke part of the end-points.
But there are several issues:

- Since my custom controllers don't expose actual actions, I can't add XML comments to the methods (the UI documentation collects all data from the methods XML comments). My workaround is to implement my custom IDocumentFilter and manually patch all custom end-points metadata. It works but very ugly and hard to maintain.
My suggestion is to make all actions in BaseController virtual and then I could just override the methods and add my XML comments. The code of the overridden method will be only calling the base class.

- The second problem is the metadata method parameters. I'm talking about JObject parameters. I'm still looking for an elegant way to describe the parameters by XML comments.

Please, advise

**Comment by boris-meerovich-sp** [comment]
Awesome!!! 
Thanks for the so quick responses!!!

**Comment by simpleidserver** [comment]
The project "SimpleIdServer.Scim.Startup" has been updated in the branch "release/1.1.8" :
* The swagger  documentation is now enriched with information coming from SCIM Schemas.
* Some JObject parameter have been replaced but not all of them.

A pre-release version will be published next week (monday).

![image](https://user-images.githubusercontent.com/10213388/96147871-00a68480-0f08-11eb-95aa-d814de49b071.png)

**Comment by boris-meerovich-sp** [comment]
I switched to work with branch "release/1.1.8".
All overrides are really helped me!!! Thanks.
Several issues I encountered with:

- In Users get endpoint for example, how to display example value like in post? Currently, I  got this:
![image](https://user-images.githubusercontent.com/16177113/96417529-1236a780-11fa-11eb-8c4a-91562229a597.png)
- In SimpleIdServer.Scim.Swashbuckle\SCIMSchemaGenerator.cs, GenerateReferencedSchema() method, row 176 
schema.Properties.Remove(schema.Properties.First(_ => _.Key == "Attributes"));
I got exception: System.InvalidOperationException: 'Sequence contains no matching element'
for schema.Properties.First(_ => _.Key == "Attributes") row.
Any of my schemas contain Attributes in Properties.
Am I missing something?
Thanks

**Comment by simpleidserver** [comment]
* I don't think it's possible to set examples on HTTP GET operations, but only on HTTP POST, PATCH or PUT.
* This issue has been fixed in the latest commit.
* The DateTime is fixed in the latest commit.

**Comment by simpleidserver** [comment]
Do-you have any remarks on the Swagger endpoint / UI ?

If no, we will publish a new release.

**Comment by boris-meerovich-sp** [comment]
So far, so good!
