### ISSUE TITLE
[SCIM] EFCore.BulkExtensions usage

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#545]
Hello, how are you?

In the latest version of EFCore.BulkExtensions, the support of shadow properties in postgres was introduced.

Can you please upgrade the version to 7.1.4 ?

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello :)

I'll include this changes for the next release !

KR,

SID

**Comment by simpleidserver** [comment]
A pre-release candidate will be published next week :)

**Comment by danflomin** [comment]
OK thanks :)

Why is this a pre-release and not a release?

**Comment by simpleidserver** [comment]
We have made the decision to release a pre-release candidate version next week, as the forthcoming version 4.2 will not be fully completed :(.
Our intention is to incorporate the BFF framework into this version.

However, if you require an immediate solution, we can certainly proceed with an official release :)

**Comment by omri-za** [comment]
We prefer an immediate solution. Thanks! 🙏

**Comment by simpleidserver** [comment]
Ok :) we will release the version 4.2 next week !

KR,

SID

**Comment by omri-za** [comment]
Thank you! 😄

**Comment by danflomin** [comment]
You are awesome!

**Comment by danflomin** [comment]
Hello,
Can you please share a link to the commit that was used for 4.0.2?

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

The following commit contains the changes made on the SCIM project : 

https://github.com/simpleidserver/SimpleIdServer/commit/a7e38f2df9bc550dcf0fdce097dec60a313780fa

KR,

SID
