### ISSUE TITLE
Provide base controller to other controllers as well.

### ISSUE THREAD

**Issue by SviatoslavVilkovych** [simpleidserver/SimpleIdServer#56]
More like an enchantment. I really liked what you did with **BaseApiController** in 1.1.8. It would be nice to have something like this for other controllers as well.
I think that this is really important to have an ability to override controller actions. Having virtual methods allows clients of your framework disable requests which they don't need.

I even can help you with that.

**Comment by simpleidserver** [comment]
Thank you for your suggestion, the changes have been committed  to the branch "release/1.1.9"

**Comment by SviatoslavVilkovych** [comment]
Thank you for making SimpleIDServer more comfortable to use!
