### ISSUE TITLE
PublicKeyCredentialDescriptor.Id property is read only

### ISSUE THREAD

**Issue by lechediaz** [simpleidserver/SimpleIdServer#562]
Hello,

I tried to compile the master branch but there is an error beacause the `PublicKeyCredentialDescriptor.Id` property is readonly.

**Comment by simpleidserver** [comment]
Hello,

The build issue is fixed in the master branch. 
The latest release of the Nuget package `Fido2.AspNet` contains a breaking change on the `PublicKeyCredentialDescriptor.Id` property :)

KR,

SID

**Comment by lechediaz** [comment]
Hello,

I checked and now the server it builds succesfully.

Thank you.
