### ISSUE TITLE
[SCIM] Exception filtering by userName

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#565]
Hello guys,

I face this error in the last version:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/51672532-042b-49d7-b6ca-b15d609cc38c)

calling 

/v2/Users?filter=userName eq "testuser"

I tried to check the source code to fund the issue, but I don't understand why.

Regards.
Gabriele

**Comment by gabrielemilan** [comment]
Maybe found the issue, is a regression on this commet

https://github.com/simpleidserver/SimpleIdServer/commit/babdac33e366b34ee4ceb8b5f328f40d52cdc3d2

the row:

e1 = Expression.Coalesce(e1, Expression.Constant(string.Empty));

**Comment by simpleidserver** [comment]
Hello,

The LINQ Expression `{ValueString} ?? ""` is not supported by the Nuget package `MongoDB.Driver` version `2.11.6` but by the latest one, and it causes this exception.
I made some modifications in the branch `release/v4.0.2` to fix this issue.
A release is planned this week with all the changes : https://github.com/users/simpleidserver/projects/1

KR,

SID

**Comment by gabrielemilan** [comment]
Tested on 4.0.3
