### ISSUE TITLE
[SCIM] Error on patch group 4.0.3 

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#567]
Hello,

I tried new version 4.0.3 to solve the issue #565 .

Now I have this error on patch group:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/84539ad6-7ca3-458e-9e10-e01bd2465933)

**Comment by simpleidserver** [comment]
Hello,

It is true that there is a minor regression in the GetReferences operation. 
The problem has been resolved in the 4.0.4 branch.
A pre-release candidate version will be published as soon as I have completed the review of the Pull Request : https://github.com/simpleidserver/SimpleIdServer/pull/568

Best regards,

SID
