### ISSUE TITLE
Can't add new ApiResource to a scope in a non-master realm

### ISSUE THREAD

**Issue by mshwf** [simpleidserver/SimpleIdServer#569]
I'm facing this problem in the project I'm working on, before reporting the issue I tried the same steps on the demo website: https://website.simpleidserver.com/

**Steps to reproduce:**
Go to the demo administration website> Activate 'test' realm> Scopes> Select 'test' Scope
Try 'Add API resource'

**Actual behavior:** 
Nothing happens, and this error shows up in the console:
> Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
>     at Nt.send (blazor.server.js:1:54577)
>     at Ft._sendMessage (blazor.server.js:1:71300)
>     at Ft._sendWithProtocol (blazor.server.js:1:71341)
>     at Ft.send (blazor.server.js:1:71449)
>     at Object.beginInvokeDotNetFromJS (blazor.server.js:1:134874)
>     at w (blazor.server.js:1:2167)
>     at C.invokeMethodAsync (blazor.server.js:1:4035)
>     at blazor.server.js:1:11583
>     at T (blazor.server.js:1:11761)
>     at I (blazor.server.js:1:11552)

**Expected behavior:** 
The add new resource form shows up and I can add new API Resource (like I can when the 'master' realm is activated)

**Comment by mshwf** [comment]
Thanks for your help, appreciate it.
I couldn't do better than recording the issue, so here it is. I also tried on different browser/device (not sure if this could help) but still the same behavior.

![SID_add_api_resource](https://github.com/simpleidserver/SimpleIdServer/assets/10940379/1fec59f2-4aea-4746-b235-8a9e3841d7b4)

**Comment by simpleidserver** [comment]
Indeed there is an issue :(
It is already fixed in the branch `release\4.0.4`.

KR,

SID
