### ISSUE TITLE
Methods of ISCIMRepresentationQueryRepository don't support CancellationToken

### ISSUE THREAD

**Issue by andreidabryian** [simpleidserver/SimpleIdServer#572]
Let's add support of CancellationToken for methods of ISCIMRepresentationQueryRepository

**Comment by simpleidserver** [comment]
Hello,

I made some modifications in the `release/4.0.4` branch, the `CancellationToken` is now passed to the methods of `ISCIMRepresentationQueryRepository`.

KR,

SID
