### ISSUE TITLE
[SCIM] Azure Service Bus Notification issue on 4.0.4

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#576]
Hello,

I noticed an issue on MassTransit notification on Azure Service Bus.
The payload of the message is partially empty:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/38dbd727-5414-4271-9821-29c1c2a04563)

I tried to change this code:

`        
public JObject Representation
{
    get
    {
        return string.IsNullOrWhiteSpace(SerializedRepresentation) ? null : JObject.Parse(SerializedRepresentation);
    }
}
`
to

`        
public JsonObject Representation
        {
            get
            {
                return string.IsNullOrWhiteSpace(SerializedRepresentation) ? null : JsonNode.Parse(SerializedRepresentation).AsObject();
            }
        }
`

using builtin System.Text.Json.Nodes and it works fine:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/46ba69b0-2a89-4012-b8d5-23376a2b2853)

I don't know, maybe is my configuration issue.

Regards.

**Comment by simpleidserver** [comment]
Hello,

The Representation property should not be serialized into JSON by Masstransit. Integration events are consumed by clients, and deserialization must occur on the client side. Would it be acceptable to you if we decorate the property with a JsonIgnore attribute to skip the serialization?

KR,

SID

**Comment by simpleidserver** [comment]
You can see the changes here : https://github.com/simpleidserver/SimpleIdServer/commit/0bc6ab60e2f53f1549273a21a2660b9a84376bbd#diff-30e8359a09af336b70c23ac90cf902b6ec5eac596308042a93995743bb58dfe1R31

**Comment by gabrielemilan** [comment]
Ok, but I think will be not retro-compatible with the previous version, isn't it?

**Comment by gabrielemilan** [comment]
ok thanks, can you tell me the ETA?

**Comment by simpleidserver** [comment]
I can publish the Nuget package tomorrow afternoon (14/09) :)

**Comment by simpleidserver** [comment]
The Nuget package version "4.0.4-rc2" is published !
You can download it here : https://www.nuget.org/packages/SimpleIdServer.Scim/4.0.4-rc2
