### ISSUE TITLE
PATCH Replace operation on complex multi-valued attribute not working as expected

### ISSUE THREAD

**Issue by jivpif** [simpleidserver/SimpleIdServer#58]
Hi,

I am having some problems with the Patch Replace operation on complex multi-valued attribute.
I think the following scim definition for the Replace Patch operation is not working as expected:

>   If the target location is a multi-valued attribute for which a
      value selection filter ("valuePath") has been supplied and no
      record match was made, the service provider SHALL indicate failure
      by returning HTTP status code 400 and a "scimType" error code of
      "noTarget".

https://tools.ietf.org/html/rfc7644#section-3.5.2.3

Instead, no error is returned and the values that are sent in the patch request are added as new records to the multi-valued attribute.

Thanks

**Comment by simpleidserver** [comment]
First of all, thank you for your feedback :). 
The issue has been fixed in the branch "release/1.1.9".

**Comment by jivpif** [comment]
Hey, many thanks for the quick response and fix!
It works.

I want to mention two improvement suggestions related:

1. May be it's good to make the other responses for not matching attributes consistent and returning 400 "noTarget" as well. At the moment they are returning 500 "internalServerError":

https://github.com/simpleidserver/SimpleIdServer/blob/release/1.1.9/src/Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs#L38
https://github.com/simpleidserver/SimpleIdServer/blob/release/1.1.9/src/Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs#L45

2. Patch Remove scim docs:
https://tools.ietf.org/html/rfc7644#section-3.5.2.2

>  If "path" is unspecified, the operation fails with HTTP status
      code 400 and a "scimType" error code of "noTarget".

Reading this doc about the scim Remove operation, may be we should return this 400 "noTarget" only if the path is not specified at all on Remove operation. If there is a path specified for it but no matching attributes or records are found, no error should be returned - just nothing is removed. So this kind of 400 error because of no matching records probably applies only for the Replace op.

It's again a matter of interpretation I quess.

Thanks

**Comment by simpleidserver** [comment]
Good remarks :) the algorithm have been updated according to the RFC (always in the branch "release/1.1.9").

The following changes have been made :
* Remove operation : an exception is thrown if the path is invalid / empty.
* Replace operation : 
  * An exception is thrown if the target location is a multi-valued attribute for which a value selection filter have been supplied and no record match was made.
  * If the path is omitted, the target is assumed to be the resource itself.

**Comment by jivpif** [comment]
Hi,

Thanks a lot for the fixes, and apologies for the late response.

I was testing with the latest changes. The Remove operation looks good.

I think there might be a small regression for the Replace and Add opeartions in case the "path" points to an attribute that is not part of the schema definition. For example:

> "path": "UnknownAttr"
> "path": "roles.UnknownAttr"
> "path": "roles[value eq \"Member\"].UnknownAttr"

Now in that case the response is 200. And may be it should again be 400.

Also if the Replace path contains a filter and points to a sub-attribute:

> roles[value eq \"NoMatch\"].display

The response is still 200. May be it should be again 400.

I made an optional fix in the following PR, in case you find it useful, otheriwse it can be deleted:
https://github.com/simpleidserver/SimpleIdServer/pull/64

Thank you

**Comment by simpleidserver** [comment]
Thank you for your pull request :)
I made the changes on the branch "1.1.9" to fix the issue.

**Comment by jivpif** [comment]
Thank you too! The issue is fixed.
