### ISSUE TITLE
PATCH Replace operation on complex attribute not working as expected

### ISSUE THREAD

**Issue by jivpif** [simpleidserver/SimpleIdServer#59]
Hey again,

I think that the next Patch Replace definition from the scim protocol is not completely fulfilled:

> If the target location specifies a complex attribute, a set of
      sub-attributes SHALL be specified in the "value" parameter, which
      replaces any existing values or adds where an attribute did not
      previously exist.  Sub-attributes that are not specified in the
      "value" parameter are left unchanged.

https://tools.ietf.org/html/rfc7644#section-3.5.2.3

Reading this definition, I would expect that if I don't send some of the sub-attributes of the target complex attribute, they will remain unchanged. But instead, they are set to empty. Seems the whole complex attribute is replaced.

I am testing with a complex **multi-valued** attribute:

Example:

Complex multi-valued object "roles":

> "roles": [
        {
            "primary": false,
            "type": "WindowsAzureActiveDirectoryRole",
            "value": "Member",
            "display": "Member"
        }
    ]

Patch Replace operation:

> "op": "Replace",
            "path": "roles[value eq \"Member\"]",
            "value": {
                "display": "Team Member"
            }

			
Result:

> "roles": [
        {
            **"display": "Team Member"**
        }
    ]

Expected:

> "roles": [
        {
            "primary": false,
            "type": "WindowsAzureActiveDirectoryRole",
            "value": "Member",
            **"display": "Team Member"**
        }
    ]

	
I might be misinterpreting the scim requirements here. 
Please, excuse me if I am wrong and this definition does not apply to complex attributes which are multi-valued as well. 
And thanks again in advance for the time

**Comment by simpleidserver** [comment]
You're right, I made a mistake in the implementation.
The PATCH implementation has been updated in the branch "release/1.1.9" & the issue should be fixed.

**Comment by jivpif** [comment]
Hi, thanks a lot! The issue is fixed indeed in the release/1.1.9 branch.

We are currently making more tests on the patch requests following the scim documentation.
We found a couple of other issues. Here is one of them (related to this one):
https://github.com/simpleidserver/SimpleIdServer/issues/60

Will let you know, if we find something else.
Thank you again
