### ISSUE TITLE
Patch Replace operation on sub-attribute of a comlpex multi-valued object not working as expected

### ISSUE THREAD

**Issue by jivpif** [simpleidserver/SimpleIdServer#60]
Hi,

Testing with branch release 1.1.9 I am having the following issue:

Multi-valued complex model roles:

> "roles": [
        {
            "primary": false,
            "type": "WindowsAzureActiveDirectoryRole",
            "value": "Member",
            "display": "Member"
        }
    ]

	
Executing the following Replace Patch operation:

> "op": "Replace",
"path": "roles[value eq \"Member\"].display",
"value": "Team Member"

Expected:

> "roles": [
        {
            "primary": false,
            "type": "WindowsAzureActiveDirectoryRole",
            "value": "Member",
            **"display": "Team Member"**
        }
    ]

Actual result:

	

> "roles": [
>         {
>             "primary": false,
>             "type": "WindowsAzureActiveDirectoryRole",
>             "value": "Member",
>             **"display": "Member"**
>         }
>     ],
> 	**"display": "Team Member"**

Seems the new sub-attribute value is not replaced in the roles matching	record, but rather is added as a new attribute to the root level of the user object.

Thanks

**Comment by simpleidserver** [comment]
Indeed there is an issue with the REPLACE algorithm.
The issue is fixed in the branch "release/1.1.9" & some integration tests have been executed with Entity Framework (SQL SERVER)

**Comment by jivpif** [comment]
Thank you for the quick reaction!
