### ISSUE TITLE
[question]Does it support database SqlSugar

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#611]
Does the database support other databases besides SqlServer? How to change the database type used by the program if supported?

**Comment by simpleidserver** [comment]
Hello,

By default, SimpleIdServer supports two databases: `SQLSERVER` and `POSTGRESQL`. For more information, you can refer to the documentation: https://simpleidserver.com/docs/iam/storage

Of course, it is possible to support other database providers. You can find a list here: https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli

To support your preferred database, please follow these steps:

1. Create project named `IdServer` with the `SimpleIdServer.IdServer` Package.


```
dotnet new idserver -n IdServer --storageConnectionString "Data Source=.;Initial Catalog=IdServer;Integrated Security=True;TrustServerCertificate=True" --distributedCacheConnectionString "Data Source=.;Initial Catalog=IdServer;Integrated Security=True;TrustServerCertificate=True"
```

2. Navigate to the directory `IdServer` and install the appropriate Nuget package for example `Microsoft.EntityFrameworkCore.Sqlite` for SQLite.

```
dotnet add package Microsoft.EntityFrameworkCore.Sqlite
```

3. Open the `Program.cs` file in your preferred text editor.
4. Edit the `ConfigureStorage` method and configure SQLITE :

```
b.UseSqlite("CONNECTIONSTRING", o =>
{
    o.MigrationsAssembly("IdServer");
    o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
});
```

5. Edit the `ConfigureDistributedCache` method and configure your distributed caching storage. Please refer to the official documentation here: https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-7.0. If you want to use the InMemory implementation, you can comment out the content.
6. Run the following command line to create the migrations scripts
7. Run the project

The documentation will be updated in future releases to explain in more detail how to configure your storage. If you need support with your configuration, don't hesitate to contact us.

KR,

SID

**Comment by qq1176914912** [comment]
> Hello,
> 
> By default, SimpleIdServer supports two databases: `SQLSERVER` and `POSTGRESQL`. For more information, you can refer to the documentation: https://simpleidserver.com/docs/iam/storage
> 
> Of course, it is possible to support other database providers. You can find a list here: https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli
> 
> To support your preferred database, please follow these steps:
> 
> 1. Create project named `IdServer` with the `SimpleIdServer.IdServer` Package.
> 
> ```
> dotnet new idserver -n IdServer --storageConnectionString "Data Source=.;Initial Catalog=IdServer;Integrated Security=True;TrustServerCertificate=True" --distributedCacheConnectionString "Data Source=.;Initial Catalog=IdServer;Integrated Security=True;TrustServerCertificate=True"
> ```
> 
> 2. Navigate to the directory `IdServer` and install the appropriate Nuget package for example `Microsoft.EntityFrameworkCore.Sqlite` for SQLite.
> 
> ```
> dotnet add package Microsoft.EntityFrameworkCore.Sqlite
> ```
> 
> 3. Open the `Program.cs` file in your preferred text editor.
> 4. Edit the `ConfigureStorage` method and configure SQLITE :
> 
> ```
> b.UseSqlite("CONNECTIONSTRING", o =>
> {
>     o.MigrationsAssembly("IdServer");
>     o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
> });
> ```
> 
> 5. Edit the `ConfigureDistributedCache` method and configure your distributed caching storage. Please refer to the official documentation here: https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-7.0. If you want to use the InMemory implementation, you can comment out the content.
> 6. Run the following command line to create the migrations scripts
> 7. Run the project
> 
> The documentation will be updated in future releases to explain in more detail how to configure your storage. If you need support with your configuration, don't hesitate to contact us.
> 
> KR,
> 
> SID

Okay, I understand. Thank you for your reply.

**Comment by qq1176914912** [comment]
> Hello,
> 
> By default, SimpleIdServer supports two databases: `SQLSERVER` and `POSTGRESQL`. For more information, you can refer to the documentation: https://simpleidserver.com/docs/iam/storage
> 
> Of course, it is possible to support other database providers. You can find a list here: https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli
> 
> To support your preferred database, please follow these steps:
> 
> 1. Create project named `IdServer` with the `SimpleIdServer.IdServer` Package.
> 
> ```
> dotnet new idserver -n IdServer --storageConnectionString "Data Source=.;Initial Catalog=IdServer;Integrated Security=True;TrustServerCertificate=True" --distributedCacheConnectionString "Data Source=.;Initial Catalog=IdServer;Integrated Security=True;TrustServerCertificate=True"
> ```
> 
> 2. Navigate to the directory `IdServer` and install the appropriate Nuget package for example `Microsoft.EntityFrameworkCore.Sqlite` for SQLite.
> 
> ```
> dotnet add package Microsoft.EntityFrameworkCore.Sqlite
> ```
> 
> 3. Open the `Program.cs` file in your preferred text editor.
> 4. Edit the `ConfigureStorage` method and configure SQLITE :
> 
> ```
> b.UseSqlite("CONNECTIONSTRING", o =>
> {
>     o.MigrationsAssembly("IdServer");
>     o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
> });
> ```
> 
> 5. Edit the `ConfigureDistributedCache` method and configure your distributed caching storage. Please refer to the official documentation here: https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-7.0. If you want to use the InMemory implementation, you can comment out the content.
> 6. Run the following command line to create the migrations scripts
> 7. Run the project
> 
> The documentation will be updated in future releases to explain in more detail how to configure your storage. If you need support with your configuration, don't hesitate to contact us.
> 
> KR,
> 
> SID

I want to use POSTGRESQL in the project 'SimpleIdServer. IdServer. Startup', and I have changed the Type of 'appsettings. json' as follows:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/a685c9e0-d9c7-497c-9e69-c91f66991f4e)
After the result is started, an error is reported as follows:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ec5b0e14-ab6d-4140-8254-8187e024cd4b)
Why does this error occur?
