### ISSUE TITLE
After login to client the server does not redirect to the redirect url

### ISSUE THREAD

**Issue by Alik2015** [simpleidserver/SimpleIdServer#615]
I have a client set up and redirect url of https://localhost:7002/signin-oidc 
https://localhost:5001/form?state=CfDJ8Dz8jMtnZZdJsF3M8n78TpCm5g8gDzv0NrXXUbNB7CniNv4r5Pd6o61v-DoHa-VKd2xIOE_wLkbVZTwKCfTqEIUD975XAD1feECZp6O3kNf_sZaOkoBmoyTIHwzJLy4K6LZmDjsaLOWDTJ_BtjSrbpnpKZwi6kFtI32QqUHDG_bS6O6INN8j0I3xXqij4ygSJoe5RDaq-8y0l7C_GKkZOXWTFRJcPaJkYK38DmMpjjROtUDCQBnfhjVuROUomRJZeYzhhRJCaEyJFt_OSogNQnqS0YSbBIDbfTxP6tyHr9U3xfyEe5VzverskV_4o7rM_d3iBXfFHeid2UzxQodpc_hIKy7v6Vnlap-Awfr0r8K-6bbD6z_eX65Y_VJAJmubhg&code=75bcbc0e-cd63-46e5-9757-e3b7a7c6e9be&token_type=Bearer&session_state=Br4Q-R2_5b941iYMOG-of0giEuRqn-2RTNBJ9ZhnkTI.d02ba590-bb86-40c9-87be-92c647cbf5f0&redirect_url=https%3A%2F%2Flocalhost%3A7002%2Fsignin-oidc

After login the page remains on the id server and not redirect.

Also notice that if I change the redirect url to something like https://localhost:7002/callback the server still looks for sigin-oidc.

1) Set up client app in id server and set url to appurl/callback
2) Click on authorized endpoint on the app and dispays error saying invalid url as it looks for appurl/sigin-oidc for some reason.

Is this caching issue?

**Comment by simpleidserver** [comment]
Hello,

It is a known issue & it has already been fixed in the release `4.0.5`.
You can see the changes here : https://github.com/simpleidserver/SimpleIdServer/commit/f302a0d0b2e232bbc6b38a70a9ef02a6695bfa68#diff-e1b6f9746e093bb3c1319428e0ec1ba191e6cbeb3ff6f73c5ac320f68f302ca6

The URL `https://localhost:5001/form` is not correct and it must be `https://localhost:5001/master/form`

**Comment by qq1176914912** [comment]
> Hello,
> 
> It is a known issue & it has already been fixed in the release `4.0.5`. You can see the changes here : [f302a0d#diff-e1b6f9746e093bb3c1319428e0ec1ba191e6cbeb3ff6f73c5ac320f68f302ca6](https://github.com/simpleidserver/SimpleIdServer/commit/f302a0d0b2e232bbc6b38a70a9ef02a6695bfa68#diff-e1b6f9746e093bb3c1319428e0ec1ba191e6cbeb3ff6f73c5ac320f68f302ca6)
> 
> The URL `https://localhost:5001/form` is not correct and it must be `https://localhost:5001/master/form`

Hello, may I ask if the version of Dotnet new -- install SimpleIdServer. Templates is still 4.0.4, and when will the new version of 4.0.5 be updated?

**Comment by simpleidserver** [comment]
Hello @qq1176914912,

The release `4.0.5` will be published next week, the 14 november :)

KR,

SID

**Comment by agkoutis** [comment]
Hello, I'm currently facing a similar problem with the form post.

The "IsRealmEnabled" is set to **false** but the produced URL is "/master/form?state=CfDJ8IbwW-M"

When I delete the master form URL, everything works fine. I'm currently on 4.0.5.

**Comment by simpleidserver** [comment]
Indeed, there is still an issue with the redirect URL. :(

The issue has been fixed and pushed to the `master` branch !
