### ISSUE TITLE
IdentityServer - Implement swagger + gives some SWAGGER samples

### ISSUE THREAD

**Issue by simpleidserver** [simpleidserver/SimpleIdServer#627]
discussion #625 

* For each realm, create a swagger endpoint : DONE
* Add all the operations into swagger : DONE
* Add parameters (TOKEN) : DONE
* Serialize enum : DONE
* Add parameters (AUTHORIZATION) : DONE
* Support ReDoc : DONE

**Comment by Alik2015** [comment]
What is the swagger endpoint?

**Comment by simpleidserver** [comment]
For each `realm`, there is one OPENAPI endpoint exposed. 
It is used by the Swagger library to display the list of APIs and their operations.

**Comment by Alik2015** [comment]
For example?

**Comment by simpleidserver** [comment]
You can choose between the SWAGGER UI : 

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/5e1bdd02-c027-4b22-8ea2-cd8f55f449ad)

Or Redoc : 

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/5c338f03-8adf-4e08-8d25-7d0e1a1094f3)

**Comment by simpleidserver** [comment]
No problem!

I'm still working on this ticket :)

There is a first working version in the branch `origin/Ticket627`. 
If the property `IsRealmEnabled`  is set to false in the appsettings.json file, you can access the SWAGGER UI via this URL: https://localhost:5001/swagger. 
Otherwise, if the property is set to true, you can access the UI via this URL: https://localhost:5001/master/swagger.
