### ISSUE TITLE
Parent of sub-attributes not set when calling ExtractSCIMRepresentationFromJSON method

### ISSUE THREAD

**Issue by jivpif** [simpleidserver/SimpleIdServer#63]
Hey,

It looks like the Parent of the sub-attributes is not set when using the ExtractSCIMRepresentationFromJSON method.

I have an optional fix for the issue in this Pull Request to the release/1.1.9 branch (in case you find it useful):
https://github.com/simpleidserver/SimpleIdServer/pull/62

Thanks in advance for the time again.

**Comment by simpleidserver** [comment]
Your pull request fixed the issue. It has been merged into the branch "release/1.1.9".
Thank you for your contribution

**Comment by jivpif** [comment]
Thanks too!
