### ISSUE TITLE
Nuget.org for version 4.0.5

### ISSUE THREAD

**Issue by agkoutis** [simpleidserver/SimpleIdServer#636]
Hello all,

Correct me if i am wrong but it seems that the version of SID 4.0.5 does not exist in Nuget.org.

NuGet\Install-Package SimpleIdServer.IdServer -Version 4.0.5

![image](https://github.com/simpleidserver/SimpleIdServer/assets/25480598/6bb5e948-2c7e-46e3-8afe-26086b4407fd)

Also, I'm getting the same error while trying to install SimpleIdServer.IdServer.WebSite V4.0.5

  GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
  GET https://api.nuget.org/v3-flatcontainer/simpleidserver.idserver/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 191ms
  OK https://api.nuget.org/v3-flatcontainer/simpleidserver.idserver/index.json 613ms
  GET https://api.nuget.org/v3/vulnerabilities/index.json
  OK https://api.nuget.org/v3/vulnerabilities/index.json 45ms
  GET https://api.nuget.org/v3/vulnerabilities/vulnerability.base.json
  GET https://api.nuget.org/v3/vulnerabilities/vulnerability.update.json
  OK https://api.nuget.org/v3/vulnerabilities/vulnerability.update.json 42ms
  OK https://api.nuget.org/v3/vulnerabilities/vulnerability.base.json 44ms
NU1102: Unable to find package SimpleIdServer.IdServer with version (>= 4.0.5)
  - Found 12 version(s) in nuget.org [ Nearest version: 4.0.4 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in OverprintFeed
NU1102: Unable to find package SimpleIdServer.IdServer with version (>= 4.0.5)
  - Found 12 version(s) in nuget.org [ Nearest version: 4.0.4 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in OverprintFeed

**Comment by simpleidserver** [comment]
I pushed the missing package into Nuget.
Can-you try again ?

**Comment by agkoutis** [comment]
It's all right now on Nuget.org, I will test it later!

Thanks!
