### ISSUE TITLE
IdServer - Supports AccessTokenType (JWT or Reference)

### ISSUE THREAD

**Issue by simpleidserver** [simpleidserver/SimpleIdServer#640]

**Comment by qq1176914912** [comment]
When the client configuration token type is Reference
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/d1b18763-d675-4ef4-8cc7-66b61850d7ae)
When the client configuration token type is Reference, ids (5001) and client（5555） login will report errors
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ad8c2974-b6bb-496f-99d0-6851ca443446)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/a7239f70-0d28-4afb-8abc-ded02e738c4d)

**Comment by simpleidserver** [comment]
The issues have been resolved in the 'master' branch. Could you please try again?

Additionally, it is now possible to include the role in the access token (Ticket #641).

Please follow these steps to add the role to the access token:

1 Navigate to the 'Scopes' screen and choose the 'role' scope.
2 Click on the 'Mappers' tab and select the first mapping rule, named 'role.'
3 Choose 'Include in Access Token' and click the 'Save' button.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/23ab4700-0287-415d-9e9c-27b4d837e46b)

**Comment by qq1176914912** [comment]
> The issues have been resolved in the 'master' branch. Could you please try again?
> 
> Additionally, it is now possible to include the role in the access token (Ticket #641).
> 
> Please follow these steps to add the role to the access token:
> 
> 1 Navigate to the 'Scopes' screen and choose the 'role' scope. 2 Click on the 'Mappers' tab and select the first mapping rule, named 'role.' 3 Choose 'Include in Access Token' and click the 'Save' button.
> 
> ![image](https://private-user-images.githubusercontent.com/10213388/287065327-23ab4700-0287-415d-9e9c-27b4d837e46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTI0NzEsIm5iZiI6MTcwMTM5MjE3MSwicGF0aCI6Ii8xMDIxMzM4OC8yODcwNjUzMjctMjNhYjQ3MDAtMDI4Ny00MTVkLTllOWMtMjdiNGQ4MzdlNDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAwNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODRiMGEwNjBiZWE1YWM0MjRjMmFlYmI0M2MxMjAyMjBhZWRjNmQwMzIxOWI4ZGMzNDYyYjA4ZjY4ZGNkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Z3Z6n7uQpqwu8UiUuO-MXVfSNwSav7ADpiBSdP2tbw)

**Reference**
Yes, the client can now log in normally, but there is one more issue. When using Reference, my API needs to be configured as follows：
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/6eccbb74-22b7-4197-ad74-1cf953a2a73e)
The problem now is that I don't know how to configure 'ApiName' and 'ApiSecret' in your project and make them effective.
**Role**
Yes, now I can add roles to the accesstoken, and this change is great.
**Existing problems**
When I added 'Client scopes' to the client, I added the API Resource type, but if it is added for the first time without refreshing the page, it will display the' Identity Resource 'type:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/fc4224b9-61c3-4e55-bdd7-1cbb14f8d194)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/1fcb8660-d0df-4311-8785-d333ede06b1b)
And no matter what scope is added, as long as it is just added, if you click on the Name without refreshing the page, the redirect will report an error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/7d500929-5cca-4532-8efa-633500362e0f)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ef9bd402-e24e-430b-b891-0a88bbfbc00f)
**recommendation**
Suggest adding a delete button in 'API Resources'
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/60442cab-5ad9-4623-9841-f34beb651ad5)
