### ISSUE TITLE
[question]Regarding the issues encountered with Reference and Scope

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#646]
**Reference**
When using Reference, my API needs to be configured as follows：
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/6eccbb74-22b7-4197-ad74-1cf953a2a73e)
The problem now is that I don't know how to configure 'ApiName' and 'ApiSecret' in your project and make them effective.

**Existing problems**
When I added 'Client scopes' to the client, I added the API Resource type, but if it is added for the first time without refreshing the page, it will display the' Identity Resource 'type:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/fc4224b9-61c3-4e55-bdd7-1cbb14f8d194)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/1fcb8660-d0df-4311-8785-d333ede06b1b)
And no matter what scope is added, as long as it is just added, if you click on the Name without refreshing the page, the redirect will report an error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/7d500929-5cca-4532-8efa-633500362e0f)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ef9bd402-e24e-430b-b891-0a88bbfbc00f)
**recommendation**
Suggest adding a delete button in 'API Resources'
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/60442cab-5ad9-4623-9841-f34beb651ad5)

**Comment by simpleidserver** [comment]
**Reference**

The ApiName serves as the ClientId, and the ApiSecret functions as the ClientSecret.

To create a new machine client, follow these steps on the administration website:

* Navigate to the `Clients` screen and click on `Add client`.
* Choose `Machine` and proceed to the next step.
* Complete the form as follows and click on `Save`.

| Property   | Value   |
| ---------- | ------- |
| Identifier | product |
| Secret     | secret  |
| Name       | product |

**Existing problems**

Thank you once again for your feedback; all the issues have been addressed in the `master` branch.
