### ISSUE TITLE
Update packages to latest versions

### ISSUE THREAD

**Issue by Alik2015** [simpleidserver/SimpleIdServer#654]
I have bumped up packages in pull request https://github.com/simpleidserver/SimpleIdServer/pull/650 to the latest version net 7.  Also bumped up the version of one of the SCIM projects from net 5 to 7.  It seems one of the tests is failing due to the JSON now being correct it seems the json parser correctly reads what it might not have before.  I can't seem to pin point that test failure.  Hope it helps as it stops VS complaining about venerable packages.

**Comment by simpleidserver** [comment]
Thank you for your pull request! It has been merged into the `master` branch.
