### ISSUE TITLE
Create IdentityServer website project,encountered the problem of error reporting

### ISSUE THREAD

**Issue by lsleishu** [simpleidserver/SimpleIdServer#657]
![5002](https://github.com/simpleidserver/SimpleIdServer/assets/108246986/b1df44e8-a13d-4c83-8bb9-f83d5cac6392)

How can I solve this problem?

**Comment by simpleidserver** [comment]
Can-you open a command prompt and execute the command line below, a development certificate must be installed on your machine.

```
dotnet dev-certs https
```

For more information, please refer to the official documentation : https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-dev-certs
