### ISSUE TITLE
Version 1.1.9 timeline

### ISSUE THREAD

**Issue by boris-meerovich-sp** [simpleidserver/SimpleIdServer#66]
Hi,
Can you please update when do you planning to release version 1.1.9?
Thanks

**Comment by simpleidserver** [comment]
Hi,

We will publish the release 1.1.9 next Thursday (26/11/20). 
We will perform some integration tests to check if there is no regression.

**Comment by boris-meerovich-sp** [comment]
Thanks for the update!!!

**Comment by boris-meerovich-sp** [comment]
Hi,
Any updates about 1.1.9 release?

**Comment by simpleidserver** [comment]
Hi,

The project "SimpleIdServer.Scim" version 1.1.9 has already been released since 26/12 : https://www.nuget.org/packages/SimpleIdServer.Scim
