### ISSUE TITLE
Error caused by different project startup sequences

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#671]
If you start the web (5002) project first and then the 5001 project, an error will be reported when accessing the 5002 address:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f185e00b-13ad-4841-9682-fc49d088df2a)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/9132b3ab-eca4-4a47-930a-6058efb2cf40)

**Comment by simpleidserver** [comment]
This exception cannot be avoided. 
By default, when OPENID is enabled on a website, the OpenIdConnectHandler attempts to fetch the configuration from the .well-known/openid-configuration URL. 
If the Identity Server is not started, an exception is thrown.
