### ISSUE TITLE
Front-channel logout URL is not effective

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#674]
Is using the ids in this project:
 https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/SessionManagement/BackChannelClient
Front channel logout URL configured in ids:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/47e88a9b-7b99-45f2-994d-ce66a9ece310)
I found that when I log in to my client and then visit the 5001 (ids) page, the logged in user will be logged out on ids. When I click to log out, I can receive a message in the Logout section of my client (which is the configured Front channel logout URL), but I tried to use your project and also configured the Front channel logout URL:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/3f562b0f-45ac-475d-ac66-c7a6b724899e)
Using the same steps: first log in to the client, access 5001, log out the user on 5001, click on log out, and no message is received on the client's Logout. Why is this?

**Comment by qq1176914912** [comment]
> Hello, the Duende Server sample project is configured to use Back Channel Session Logout and not Front Channel Session Logout. To enable Front Channel Session Logout, perform the following actions:
> 
> In the LogoutController class, add the following action:
> 
> ```
> [HttpGet("logout/frontchannel")]
> public IActionResult FrontChannel(string sid)
> {
>     if (User.Identity.IsAuthenticated)
>     {
>         var currentSid = User.FindFirst("sid")?.Value ?? "";
>         if (string.Equals(currentSid, sid, StringComparison.Ordinal))
>         {
>             //await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
>             return new SignOutResult(new[] { "Cookies", "oidc" });
>         }
>     }
> 
>     return NoContent();
> }
> ```
> 
> Update the configuration of the client and set the 'Front-Channel logout URL' to `https://<URL>/logout/frontchannel`.

I also tried other ids in Duende and configured them with Front channel logout URLs, and the results were the same. I think this should be universal and not related to the project. I will try the method you provided.
Other issues:
1、The 5001 address client content is not displayed:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/49279a2a-08df-4267-a084-893fb91da49b)
2、Regarding SMS and email page design issues:
For example, when I ask test@163.com After successfully sending, when I filled out the verification code and prepared to update, I changed the top email to 123@qq.com He can also update successfully, and the email for the account update is also the one I changed later. Is this a bit unreasonable, and should the content above be prohibited from being modified?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/a75a4c20-d392-4a2e-bc8d-02c57ce8985e)

**Comment by simpleidserver** [comment]
**Front Channel Session**

I have reviewed the Duende sample project and, as anticipated, the logout functionality is not working. 
This is due to the absence of an action that accepts an HTTP GET request to revoke the current session. The sequence of actions I executed is as follows:

1. Run the BackChannelClient and IdentityServerHost projects.
2. Open the BackChannelClient and authenticate.
3. Navigate to the IdentityServerHost website and click on Logout.
4. Return to the BackChannelClient website and refresh the secure page. Despite the logout attempt, the user remains authenticated.

Without modification, this sample project cannot function correctly because there is no action that accepts an HTTP GET request to revoke the session. 
For more detailed information, you can refer to the documentation available here: https://openid.net/specs/openid-connect-frontchannel-1_0.html

**Client names are not displayed**

The issue has been addressed in the master branch. 
The problem stemmed from the incorrect culture used by Identity Server.

**Unexpected email**

This issue has also been resolved in the master branch.

**Comment by qq1176914912** [comment]
> **Front Channel Session**
> 
> I have reviewed the Duende sample project and, as anticipated, the logout functionality is not working. This is due to the absence of an action that accepts an HTTP GET request to revoke the current session. The sequence of actions I executed is as follows:
> 
> 1. Run the BackChannelClient and IdentityServerHost projects.
> 2. Open the BackChannelClient and authenticate.
> 3. Navigate to the IdentityServerHost website and click on Logout.
> 4. Return to the BackChannelClient website and refresh the secure page. Despite the logout attempt, the user remains authenticated.
> 
> Without modification, this sample project cannot function correctly because there is no action that accepts an HTTP GET request to revoke the session. For more detailed information, you can refer to the documentation available here: https://openid.net/specs/openid-connect-frontchannel-1_0.html
> 
> **Client names are not displayed**
> 
> The issue has been addressed in the master branch. The problem stemmed from the incorrect culture used by Identity Server.
> 
> **Unexpected email**
> 
> This issue has also been resolved in the master branch.


Thank you for your reply.
**Front Channel Session**
I tested successfully according to your previous method.
 **Unexpected email**
I think it's no longer useful to make arbitrary changes now. You can set the email input box above to a property that prohibits modification.
 **Other issues**
1、If the three pieces of information in the picture have already been added, they can only be changed and cannot be deleted.
When I try to clear the added content and click update, it will show that the update was successful, but when the page is refreshed, the content still exists.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/002d16d5-379d-426e-99c7-7cd6dc7cec15)
2、After adding credentials to the user, the page does not refresh:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/8cfea41a-2386-46a8-91b0-693cc6d547d8)

**Comment by simpleidserver** [comment]
Both issues are fixed in the `master` branch :)

**Comment by qq1176914912** [comment]
> Both issues are fixed in the `master` branch :)

Thank you for your help.

**Comment by qq1176914912** [comment]
> **Front Channel Session**
> 
> I have reviewed the Duende sample project and, as anticipated, the logout functionality is not working. This is due to the absence of an action that accepts an HTTP GET request to revoke the current session. The sequence of actions I executed is as follows:
> 
> 1. Run the BackChannelClient and IdentityServerHost projects.
> 2. Open the BackChannelClient and authenticate.
> 3. Navigate to the IdentityServerHost website and click on Logout.
> 4. Return to the BackChannelClient website and refresh the secure page. Despite the logout attempt, the user remains authenticated.
> 
> Without modification, this sample project cannot function correctly because there is no action that accepts an HTTP GET request to revoke the session. For more detailed information, you can refer to the documentation available here: https://openid.net/specs/openid-connect-frontchannel-1_0.html
> 
> **Client names are not displayed**
> 
> The issue has been addressed in the master branch. The problem stemmed from the incorrect culture used by Identity Server.
> 
> **Unexpected email**
> 
> This issue has also been resolved in the master branch.

Hello.
I am wondering if the "Front Channel url" configured in your 5002 project will be actively requested, for example, when I end a user session:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ec62288f-0994-40b1-8c32-72a736861f0b)
I created a new mvc project and added what you call the interface to the project's "Controllers" :
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/d68cd283-1233-4107-a8e1-b641ed668afb)
I was with the postman try to request the interface address "https://localhost:5030/logout/frontchannel" through debugging found that he could enter, and use but ids in the back-end logout project also try, When I log out of my current account on ids, the interface in my project can receive a message when ids and the project are opened and successfully logged in in the same browser, but I found no response using your 5001 attempt.

**Comment by qq1176914912** [comment]
> Hello,
> 
> It is normal for the front-channel endpoint not to be called when the session is revoked on the administration website. This aligns with the RFC specification at https://openid.net/specs/openid-connect-frontchannel-1_0.html#toc, which states that when the session is revoked, an IFRAME with the 'src' attribute equal to the Front Channel Logout URL must be displayed by the Identity Server.
> 
> Therefore, this scenario can only occur when the Identity Server Session UI is being displayed: https://github.com/simpleidserver/SimpleIdServer/blob/master/src/IdServer/SimpleIdServer.IdServer.Startup/Views/CheckSession/EndSession.cshtml#L14.

Thank you for your reply.
If you know where there is such a demo, I would like to test the front-end logout of your project.

**Comment by qq1176914912** [comment]
[](url)> Hello,
> 
> It is normal for the front-channel endpoint not to be called when the session is revoked on the administration website. This aligns with the RFC specification at https://openid.net/specs/openid-connect-frontchannel-1_0.html#toc, which states that when the session is revoked, an IFRAME with the 'src' attribute equal to the Front Channel Logout URL must be displayed by the Identity Server.
> 
> Therefore, this scenario can only occur when the Identity Server Session UI is being displayed: https://github.com/simpleidserver/SimpleIdServer/blob/master/src/IdServer/SimpleIdServer.IdServer.Startup/Views/CheckSession/EndSession.cshtml#L14.

This is what happens when I use 'ids' where 5001 is' ids' and 5030 is my client address. 
1. After you log in to the client, the 5001 also changes to the login state
2. When you click Exit on 5001, 5030 also exits.
https://github.com/simpleidserver/SimpleIdServer/assets/79817742/b809da2c-a61a-4d35-920f-84c645c1b67d
Then I replaced the ids with your 5001:
https://github.com/simpleidserver/SimpleIdServer/assets/79817742/54eb6670-c1a7-4260-ad0a-d2f99d2ba81c
As you can see, with ids, my 5030 client also exits when it exits on ids, but with your 5001 it doesn't, so what's the problem?

**Comment by qq1176914912** [comment]
I tried to repeat this using "ids" and I found that when I annotated the configured "FrontChannelLogoutUri" in "ids", I got the same effect as when I used your "5001" project, i.e. "5001 exits but the client does not exit"
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f5273c96-4ac4-41e4-85ba-586642e6d326)
This is my project, you can take a look at it if you have time, and if you don't mind, you can modify it and put it in your example.
[FrontChannelClient.zip](https://github.com/simpleidserver/SimpleIdServer/files/14929600/FrontChannelClient.zip)

**Comment by qq1176914912** [comment]
> I tried to repeat this using "ids" and I found that when I annotated the configured "FrontChannelLogoutUri" in "ids", I got the same effect as when I used your "5001" project, i.e. "5001 exits but the client does not exit" ![image](https://private-user-images.githubusercontent.com/79817742/321155470-f5273c96-4ac4-41e4-85ba-586642e6d326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzcyNjMsIm5iZiI6MTcxMjczNjk2MywicGF0aCI6Ii83OTgxNzc0Mi8zMjExNTU0NzAtZjUyNzNjOTYtNGFjNC00MWU0LTg1YmEtNTg2NjQyZTZkMzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA4MTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDcyOWVhNmYyYzY2OTkxMTJiNTQxZTZhN2EzOTA3NDBmMDNiYzkyMTQ4YmFmZWM2MDkxNmE0MDFlMDRiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTsdAlSubgKNNyW-QaZDHbTz01uFEpCx0VW_GT1hUrM) This is my project, you can take a look at it if you have time, and if you don't mind, you can modify it and put it in your example. [FrontChannelClient.zip](https://github.com/simpleidserver/SimpleIdServer/files/14929600/FrontChannelClient.zip)

My project When using your project instead of 'ids', I found that even if I uncheck "Front-channel logout session required" and set "Front-channel logout URL" to blank on 5002, Can still exit successfully, so now I'm confused.

**Comment by qq1176914912** [comment]
"[https://openid.net/specs/openid-connect-frontchannel-1_0.html#toc](https://openid.net/specs/openid-connect-frontchannel-1_0.html#toc)" in the "3. The OpenID Provider Logout Functionality 'seems to say' OP(5001 or ids) to logout and then notify the client to logout via the 'Front-channel logout URL'. 
But that's optional and may be the reason for the difference in the video above because your project didn't implement it.

**Comment by simpleidserver** [comment]
This problem is specific and has been fixed in the master branch. 
Hidden iframes are not displayed when the user clicks on the disconnect button of the identity server

**Comment by qq1176914912** [comment]
Sorry about the front end logout again, I have deployed the 5001 to ubuntu:
I deployed the 5001 and 5002 projects and configured the domain names on ubuntu, which uses the sqlite database.
1.This is the exit method of the front-end logout project:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/dc5a11cc-5adf-4b6c-aa5c-d37383bc85b5)
When I start the project, click the exit button, I get a "id_token", by analyzing the idtoken got sid, and then I use the browser request "https://xxxx:5001/master/end_session?" Id_token_hint ={id_token} ", the return result is:
"You are logged out." After logging into 5002 and going through User -> Sessions, I found that the status of the session id was still active.
2、My front-end logout project is local, and then the 5001 project is deployed on remote ubuntu, I want to achieve the effect we talked about earlier(5001 returned, front-end logout items also returned), this is the configuration configured on the 5002:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/b2a52407-19ee-4bd0-89ae-53e35f3fb0c3)
This address is accessible on ubuntu, except that the curl command ignores the certificate error to access it, but when I actually do it, I find that my local project does not receive the exit instruction, that is, the local front-end logout interface does not receive the request.The front-end logout project will not have this problem if it is on the same machine as the 5001 project (both locally).
The same backend logout project (project in local 5001 project in remote ubuntu), the configuration is similar to the front-end logout, but the port is different, but the 5002 project can successfully kick out my local project by ->" User "->" session "->" End session ", so I want to know what is the situation, Is there any difference in the logic of the request?

**Comment by simpleidserver** [comment]
Hello,

1. The code doesn't seem to be correct. The property is set to "https://xxx:25001", but the user-agent is not redirected to the URL. Instead of doing it manually, you can use the following code, configure the OpenIdConnect NuGet package, and set its authentication scheme to oidc:

```
SignOut(new AuthenticationProperties
            {
                RedirectUri = ""
            }, "oidc");
```		
		
2. When the front-channel URL is used, an iframe is displayed by the web browser, and no HTTP request is executed by the backend. Please check if the iframe is displayed and if the URL is accessible.

**Comment by qq1176914912** [comment]
> I have been understanding wrong, the correct should be the client by clicking logout jump to 5001 address login, and then 5001 address through the configured front-end logout address, through the iframe tag to notify the client (this address needs to clear the cookie of the client) ![image](https://private-user-images.githubusercontent.com/79817742/334058538-3f17974a-20f7-4c9d-939e-5f5260652101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzUwODIsIm5iZiI6MTcxNjk3NDc4MiwicGF0aCI6Ii83OTgxNzc0Mi8zMzQwNTg1MzgtM2YxNzk3NGEtMjBmNy00YzlkLTkzOWUtNWY1MjYwNjUyMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA5MjYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNjdkMzMwMzM2YmM3NGFlMWY2MWEyMGQwYmZlNWFhMmRkZTAwZWJmOGVmZmQ1MTVlZjUwMjYzNzM0YTYxYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8YDVpDv4mcOrdhL8dVngQJQ6dM4quufN4uwfoXAeFpw)

Sorry to interrupt.
If I follow my understanding, when 5001 and the front-end logout item are together (locally), when clicking Exit through the project to jump to the 5001 end session page, F12 can see that the iframe tag requests the front-end logout address I configured and responds to 200, but when I deploy 5001 to the remote, it cannot request:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/9dba9e42-7baf-45e8-955d-36e2aa2af7f6)
Where zxf-pc-01:5030 is the address of my front-end logged out project, and the remote server of 5001 can access this domain name + port:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/4f09c809-576b-42d6-baec-c1d44b558487)
