### ISSUE TITLE
Multiple groups in get Users

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#68]
Hello,

I found an issue on getting users, related to the enrichment of groups. It happens only on EF Persistence.

Step to reproduce:
1) create 2 users POST /v2/Users
2) create 1 group POST /v2/Groups
3) add the 2 users to that group PATCH /v2/Groups/...

`"Operations": [
        {
            "op": "add",
            "path": "members",
            "value": [
                {
                    "value": "<guid>"
                },
 {
                    "value": "<guid>"
                }
            ]
        }
    ]`

4) get users GET /v2/Users

Each user has 2 times the group:
![image](https://user-images.githubusercontent.com/10979448/101060587-dbd99f80-358f-11eb-9acc-06c9529eee02.png)

Please note that if I add another user to that group, the user returns with 3 groups.

I investigated a bit and it seems that the method _FindSCIMRepresentationByAttributes_ (in EF project) returns duplicated groups.

Thanks.
Bye :-)

**Comment by simpleidserver** [comment]
Hi,

I couldn't reproduce the bug with the latest version. 
You'll find in attachment the POSTMAN project, can-you do the following steps ?

* Get the latest changes.
* Disable the security in the project "SimpleIdServer.Scim.SqlServer.Startup".
* Launch "SimpleIdServer.Scim.SqlServer.Startup".
* Open POSTMAN and import the collection project.
* Run all the HTTP requests.

At the end, I obtained two users & each user has only one role.

[SCIM#68.postman_collection.zip](https://github.com/simpleidserver/SimpleIdServer/files/5642719/SCIM.68.postman_collection.zip)

**Comment by gabrielemilan** [comment]
Please try getting all users, if I want just one user it works properly, bu if you gett all users at the same time, it doesn't.

So please try this:

GET http://localhost:60002/Users

**Comment by gabrielemilan** [comment]
I tried to put this and it works, but I don't know if is the best solution:

![image](https://user-images.githubusercontent.com/10979448/101184717-53bbce80-3651-11eb-9bcc-40b6fdd6848b.png)

**Comment by simpleidserver** [comment]
You proposed the correct solution to fix this issue :)
I made the changes on the branch "release/1.2.0"
