### ISSUE TITLE
[question]Problems encountered during sample execution

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#686]
Hello, I tried to execute the "DeviceUseCIBA" project in your sample directory, following the process at that address:
https://simpleidserver.com/docs/tutorial/ciba/
**1. Configure a client certificate**
My steps are as follows:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/c2bfb9e8-9cbc-40bb-b2f1-b8d3b108ab25)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/9c5aebf9-e56b-47e2-bb31-78419550b08f)
After creating it, I downloaded the CA and installed it in the trusted root certificate authority location on my computer.
Then I followed your process to create "Client Certificates" and downloaded them, but they were not installed on my computer:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/29d53a62-738e-4958-8a7d-ed332c986f23)
**2. Configure an application**
Created the client according to the process:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/51fa8ac9-3045-4c92-97b9-82d46d11f25b)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/88f10f08-2595-4182-96c5-312c2bb4eac3)
**3. Create a consumption device**
Then open the "DeviceUseCIBA" project in your sample, replace the previously existing client certificate with the certificate I just downloaded again, and execute the project:
Certificate loaded successfully:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/90347771-725d-4051-8211-e8d5cf5aeb37)
When the "response" is executed, the content displays 400, and the error message is: "error": "invalid_request","Error description": "Certificate is required"
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/caadc79d-7726-4025-a3c7-05157afde833)
So it led to an error here, what is the situation?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f239fd48-1df2-420e-8824-ac861ee86edc)

**Comment by qq1176914912** [comment]
> This exception is thrown because the Identity Server cannot retrieve the client certificate Can you check in the `appsettings.json` file if the `ClientCertificate` property is set to `AllowCertificate` ?

Yes, you're right. We need to change the "ClientVerificateMode" attribute of 5001 to "AllowCertificate":
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/397ddea0-73bf-42e4-bd3c-9da863f76fc3)
And the LoginHint must have a user (login account) present in the network
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/9465379f-197d-4c3b-8f42-c5871893e237)
But I found an issue: Normally, according to your tutorial, when you receive a green message on 5001, go to the browser to verify and log in. The entered account should be the account configured in the program, which in this example is MobileUser:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/8eb3a2df-b52a-4a73-9db6-09f3886d5883)
But I found that it's normal to log in with another account without using "mobileUser"?

**Comment by qq1176914912** [comment]
I found that when adding a client on 5002, if the client already exists, it can still be added normally. After successful addition, the client cannot be edited or deleted, and can only be manually deleted from the database.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/6f5cb80a-5d42-468a-bbe5-8a28ee05f680)

**Comment by qq1176914912** [comment]
I tried to change the "metadata URL" of the built-in client "samlSp" and found an issue:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/659d75aa-b26a-43ae-9744-ef3761501b62)
You can see that it is now“ http://localhost:5125/Metadata ”When I tried to change HTTP to HTTPS, it showed that the update was successful, but the page changed back to HTTP:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/5d71077c-f12b-48fa-935e-d34922ed224d)
Actually, the modification was successful and we need to refresh the page to display the content we modified.

**Comment by simpleidserver** [comment]
**CIBA**

Indeed, the pending backchannel authorization request must only be validated by the `mobileUser` user.
I have made several modifications to the master branch to address this issue and others.

**Duplicate Client**

I have implemented additional checks to prevent the addition of two clients with the same ClientId.

**Metadata URL Not Updated**

The store has been fixed, and the property is now correctly updated.

**Comment by qq1176914912** [comment]
> **CIBA**
> 
> Indeed, the pending backchannel authorization request must only be validated by the `mobileUser` user. I have made several modifications to the master branch to address this issue and others.
> 
> **Duplicate Client**
> 
> I have implemented additional checks to prevent the addition of two clients with the same ClientId.
> 
> **Metadata URL Not Updated**
> 
> The store has been fixed, and the property is now correctly updated.

Thank you for your response. After testing, the issue has been resolved.

**Comment by qq1176914912** [comment]
1、 I followed your tutorial: https://simpleidserver.com/docs/tutorial/grantmgt There was an issue with testing your sample:
Certificate:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/cde0ae46-511c-4b24-b58d-2ec4a2afffc6)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/47fa978a-a000-4e0c-ba1e-e6e773a220e2)
One of the certificates has been installed in the "Trusted Root Certification Authority" location on the local computer (as I have previously tested your previous project, there are also root certificates installed locally for the projects "Highly Secure Regular Web Application" and "CIBA").
The JSON generated during the creation of the client has been replaced:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/eff87771-22d1-4386-9846-e250dc0409fd)
After starting the project, when redirecting to the login page and clicking the login button, an error message appears:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/74f076de-b89f-4639-8b7a-963146197567)
Error message:
> InvalidOperationException: Sequence contains no matching element
System.Linq.ThrowHelper.ThrowNoMatchException()
System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
SimpleIdServer.IdServer.UI.ConsentsController+<>c__DisplayClass10_0+<<Index>g__BuildConsentsFromGrant|0>d.MoveNext() in ConsentsController.cs
                var grant = user.Consents.First(c => c.Id == grantId);
SimpleIdServer.IdServer.UI.ConsentsController.Index(string prefix, string returnUrl, bool isProtected, CancellationToken cancellationToken) in ConsentsController.cs
                    return View(await BuildConsentsFromGrant(query, oauthClient, grantId));
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
SimpleIdServer.IdServer.Swagger.SidSwaggerUIMiddleware.Invoke(HttpContext httpContext) in SIDSwaggerUIMiddleware.cs
        await _staticFileMiddleware.Invoke(httpContext);
SimpleIdServer.IdServer.Swagger.SIDSwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) in SIDSwaggerMiddleware.cs
            await _next(httpContext);
SimpleIdServer.IdServer.Middlewares.MtlsAuthenticationMiddleware.InvokeAsync(HttpContext context) in MtlsAuthenticationMiddleware.cs
         await _next.Invoke(context);
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
SimpleIdServer.IdServer.Middlewares.LanguageMiddleware.InvokeAsync(HttpContext context) in LanguageMiddleware.cs
        await _requestDelegate.Invoke(context);
SimpleIdServer.IdServer.Middlewares.RealmMiddleware.InvokeAsync(HttpContext context) in RealmMiddleware.cs
            await _next.Invoke(context);
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

2、I found that the following content is mentioned in the introduction of "Highly Secure Regular Web Application" and "Grant Management":
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/4bb11e3d-927e-460b-b72f-c84b89175151)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/c5515a01-ab54-483f-b991-4361cce2cae6)
Some of the content can be found when configuring the client on 5002, but some do not know what the corresponding content is. For example, can the "Client Authentication Method" parameter also be configured on the 5002 client location, or is it an included parameter that is not displayed? Could you please explain which content corresponds to 5002 in the table?

**Comment by simpleidserver** [comment]
**Grant Management Exception**

The issue has been resolved in the `master` branch; the Grant Request was not saved.

**Client's Configuration**

Both tables list the properties of the new client once the creation formula is completed. To facilitate the creation process, and in alignment with FAPI 2.0 security best practices, not all properties are displayed during creation and are automatically assigned.


Grant management

| Configuration | Value | Required |
| ------------- | ----- | -------- |
| Client Authentication Method | tls_client_auth | Required by FAPI2.0 |
| Authorization Signed Response Algorithm | ES256 | Required by FAPI2.0 |
| Identity Token Signed Response Algorithm | ES256 | Required by FAPI2.0 |
| Request Object Signed Response Algorithm | ES256 | Required by FAPI2.0 |
| Pushed Authorization Request | Yes | Required by FAPI2.0 |
| Response Mode | JWT | Required by FAPI2.0 |
| Authorization Data Types | account_information | Editable |
| scopes | 	grant_management_query grant_management_revoke openid profile  | Required by FAPI2.0 |

Highly Secured Regular Web application

| Configuration | Value | Required |
| ------------- | ----- | -------- |
| Client Authentication Method | tls_client_auth | Required by FAPI2.0 |
| Authorization Signed Response Algorithm | ES256 | Required by FAPI2.0 |
| Identity Token Signed Response Algorithm | ES256 | Required by FAPI2.0 |
| Request Object Signed Response Algorithm | ES256 | Required by FAPI2.0 |
| Pushed Authorization Request | Yes | Required by FAPI2.0 |
| Response Mode | JWT | Required by FAPI2.0 |

**Client certificate**

A certificate window is displayed in your browser because the Kerstel Server accepts Client Certificates. When a client certificate is chosen, it will be retained by your web browser in its cache; therefore, the popup window is not displayed. It is not a problem that the popup window is not displayed because the client certificate is always passed by an HTTPCLIENT in C#.

**Comment by qq1176914912** [comment]
> **Grant Management Exception**
> 
> The issue has been resolved in the `master` branch; the Grant Request was not saved.
> 
> **Client's Configuration**
> 
> Both tables list the properties of the new client once the creation formula is completed. To facilitate the creation process, and in alignment with FAPI 2.0 security best practices, not all properties are displayed during creation and are automatically assigned.
> 
> Grant management
> 
> Configuration	Value	Required
> Client Authentication Method	tls_client_auth	Required by FAPI2.0
> Authorization Signed Response Algorithm	ES256	Required by FAPI2.0
> Identity Token Signed Response Algorithm	ES256	Required by FAPI2.0
> Request Object Signed Response Algorithm	ES256	Required by FAPI2.0
> Pushed Authorization Request	Yes	Required by FAPI2.0
> Response Mode	JWT	Required by FAPI2.0
> Authorization Data Types	account_information	Editable
> scopes	grant_management_query grant_management_revoke openid profile	Required by FAPI2.0
> Highly Secured Regular Web application
> 
> Configuration	Value	Required
> Client Authentication Method	tls_client_auth	Required by FAPI2.0
> Authorization Signed Response Algorithm	ES256	Required by FAPI2.0
> Identity Token Signed Response Algorithm	ES256	Required by FAPI2.0
> Request Object Signed Response Algorithm	ES256	Required by FAPI2.0
> Pushed Authorization Request	Yes	Required by FAPI2.0
> Response Mode	JWT	Required by FAPI2.0
> **Client certificate**
> 
> A certificate window is displayed in your browser because the Kerstel Server accepts Client Certificates. When a client certificate is chosen, it will be retained by your web browser in its cache; therefore, the popup window is not displayed. It is not a problem that the popup window is not displayed because the client certificate is always passed by an HTTPCLIENT in C#.

Thank you for your response.
There is a case of CIBA, his login process, he needs to get the green message in 5001 instance, I found that there is also a console in ACRS that also gets the green message in 5001, the question I have is, I am a developer, I can find this green message in 5001 black box and copy it out, what is the user going to do?

**Comment by qq1176914912** [comment]
> The green message is displayed in the console application when your configured client/relying party wishes to perform certain types of actions on behalf of the end-user. For example, confirming a bank transfer. The link displayed in the console application must be accessed by the end-user. Once the consent has been accepted, the relying party can proceed with the action.
> 
> By default, user accounts are configured to use the `console` application as a notification channel. However, you can choose another channel to send the consent/link, such as SMS, email, or Firebase. The notification mode can be updated in the `User details` view.

I see this option:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/2a4de14d-99fe-42b9-aba0-a17e14591429)
I did the following:
First, the "mobileUser" account has been added to the phone:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/e6cfee98-e63f-4cf6-a583-2bfcb129c157)
Then change the "Notification mode" to "sms"：
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/bc8b6662-d444-48bc-9c69-780a8b1293ed)
Then add console to acrs：
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/802005dc-5f94-4a65-99c2-ca76b71b1d20)
Enter and send the verification code:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/a5c705b8-495e-4ed8-b818-da630f373ba5)
1、He did not configure the sms verification code according to me, it seems that it is still sent in the console, my use of the wrong way.
2、The green input in the console looks like this:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/115f261c-f693-4ff8-9086-a38b201c80b4)

**Comment by qq1176914912** [comment]
Hello, sample "ProtectBlazorPWA" and "ProtectBlazorPWAMultiTenant" program cannot be started, show lack of file "below \ service - worker js". How to execute these two samples after startup? How do you test it?

**Comment by qq1176914912** [comment]
> _User's Notification Method_
> 
> The user notification method is utilized by the Identity Server to send notifications to the user via email, Firebase, or SMS. Therefore, when running the DeviceUseCIBA sample project, a consent message is sent to the user through the selected notification channel.
> 
> _ProtectBlazorPwdMultitenant and ProtectBlazorPWA_
> 
> We have not created any tutorials for both projects; however, we plan to do so in a future release (Ticket #688)
> 
> _UseOpenIddictAsDatasource_
> 
> I have resolved the build issues in the UseOpenIddictAsDatasource project. The goal is to demonstrate how to use the Microsoft.AspNetCore.Identity library as a data source by overriding the repository IUserRepository. While this sample project is not fully functional, it can serve as a guide for any developer looking to store users in Microsoft.AspNetCore.Identity.
> 
> _CustomUserApi_
> 
> I have resolved the build issues in the CustomUserApi project. The goal is to demonstrate how to use a REST API to retrieve user information. Although this sample project is not entirely functional, it can serve as a guide for any developer interested in managing users within their own REST API.

**User's Notification Method**
Yes, CIBA projects can indeed be sent according to my choice.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/d2c7dda7-8605-4b09-8ce3-db012748b93b)
But I am curious about the console in ACRS. I found that it could not be sent according to what I selected in user, but could only be found in the program black box of 5001. Then how can the user receive it? Is this just for internal testing?

**Comment by qq1176914912** [comment]
Can you use FAPI to set 5001 ClientCertificateMode to NoCertificate? Currently, an error message will be displayed. The client certificate must be used. Does the FAPI process require the use of client certificates?

**Comment by simpleidserver** [comment]
In accordance with security best practices outlined in FAPI 2.0, the client is required to employ a certificate for authentication. Consequently, the ClientCertificateMode cannot be configured as NoCertificate.

The 'console' authentication method is utilized for internal testing purposes. It generates an OTP code and displays it within the console application. :)

**Comment by qq1176914912** [comment]
> In accordance with security best practices outlined in FAPI 2.0, the client is required to employ a certificate for authentication. Consequently, the ClientCertificateMode cannot be configured as NoCertificate.
> 
> The 'console' authentication method is utilized for internal testing purposes. It generates an OTP code and displays it within the console application. :)

Thank you for your patient reply. I understand.

**Comment by qq1176914912** [comment]
I tested the CIBA project. I changed the "Address" in the project to the 5001 project that I deploy to the server instead of the local 5001 project. When I use a browser to access "https:// server address: 5001/master/mtls/bc-authorize",
 the page says:
> {
  "error": "invalid_request",
  "error_description": "certificate is required"
}

The "ClientCertificateMode" of the server's 5001 project has been set to "AllowCertificate".
How am I supposed to fix this?

**Comment by qq1176914912** [comment]
I tested the CIBA project. I changed the "Address" in the project to the 5001 project that I deploy to the server instead of the local 5001 project. When I use a browser to access "https:// server address: 5001/master/mtls/bc-authorize",
 the page says:
> {
  "error": "invalid_request",
  "error_description": "certificate is required"
}

The "ClientCertificateMode" of the server's 5001 project has been set to "AllowCertificate".
How am I supposed to fix this?

**Comment by simpleidserver** [comment]
Certificate Required

The displayed error message indicates that the selected certificate in your browser is incorrect.
You must choose a valid Client Certificate and provide the parameters required by the Authorization endpoint. 
For additional information, please refer to the RFC:  https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint

SAML Exception

An exception is thrown by the HTTP Client when attempting to load the metadata of the Service Provider (SP). 
I have made modifications in the master branch to ignore certificate errors.

**Comment by qq1176914912** [comment]
> Certificate Required
> 
> The displayed error message indicates that the selected certificate in your browser is incorrect. You must choose a valid Client Certificate and provide the parameters required by the Authorization endpoint. For additional information, please refer to the RFC: https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint
> 
> SAML Exception
> 
> An exception is thrown by the HTTP Client when attempting to load the metadata of the Service Provider (SP). I have made modifications in the master branch to ignore certificate errors.

Thank you for your reply, the problem has been solved
