### ISSUE TITLE
Description Failed to obtain user information

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#689]
Sorry to bother you.
When I try to get administrator information:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/9812382e-e0cd-4944-889f-0b6be6dd25c1)
5002 Error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/2c91f0a5-71f7-44ac-ae0e-b354aae49f85)
What's the problem?

**Comment by simpleidserver** [comment]
The problem has been resolved in the `master` branch. 
It was not possible to deserialize the authorization data from the consent.

**Comment by qq1176914912** [comment]
> The problem has been resolved in the `master` branch. It was not possible to deserialize the authorization data from the consent.

Unfortunately, after downloading the latest version of your project, an error occurs when trying to access 5002:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/7060a6a6-9fbf-4aa6-92d7-19a612ea2d15)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/a4357649-a227-4d5d-b2ac-669b34c3b7e5)

**Comment by simpleidserver** [comment]
This exception is thrown because the realm has been disabled in the appsettings.json file. 
The configuration file has been corrected in the master branch.

**Comment by qq1176914912** [comment]
> This exception is thrown because the realm has been disabled in the appsettings.json file. The configuration file has been corrected in the master branch.

Thank you for your reply, the problem has been solved
