### ISSUE TITLE
Patch reaonly property issue

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#69]
Hello, I found this bug on readonly property.

User resource has readonly property groups, but if I try to patch user using:

PATCH /Users/c724d055-1c0c-4fe6-ade7-2f43676f411f

`{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "add",
            "path": "groups",
            "value": [{"value":"a8296265-a6f8-4276-96b6-bcc832cc00a3"}]
        }
    ]
}`

I get this result:

![image](https://user-images.githubusercontent.com/10979448/102321078-761ce880-3f7d-11eb-9f68-b8e6228b4a10.png)

Thanks. 👍

**Comment by simpleidserver** [comment]
Hi,

The issue has been fixed in the branch "release/1.2.0". In fact, there is an error when the HTTP response is built.
UTS have been updated to check empty value is not returned.

**Comment by gabrielemilan** [comment]
I tried version 1.2.0, but I have this issue on mongo db, I don't know in SQL.

The groups property is created, even if is empty, also in the db I have this property empty.

![image](https://user-images.githubusercontent.com/10979448/102467567-bbf6b100-4050-11eb-8086-131c8a05fe5f.png)

I created a PR to try to solve it, please review it.

**Comment by simpleidserver** [comment]
your pull request has been accepted & the issue should be fixed.
thank you for your contribution :)
