### ISSUE TITLE
[SCIM] PATCH User name issue 

### ISSUE THREAD

**Issue by polybogdan** [simpleidserver/SimpleIdServer#690]
Hello,

Am am experiencing an issue while patching a user with name details:

 {
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "value": {
                "name": {
                    "givenName": "Given Updated"
                }
            }
        }
    ]
}

![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/ce8ba400-3191-4fc7-bfd1-07ac705331fb)

Same if both properties of the name "familyName" , "givenName" are passed in 2 different operations
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/415150e0-f48b-466b-bf8a-8968c47ed766)

**Comment by simpleidserver** [comment]
It is normal for this issue to occur. You are attempting to replace the 'name' attribute, but the required attributes specified in the HTTP request are not being passed. The required attributes are defined in UserSchema :)

**Comment by polybogdan** [comment]
so your advice is to just change the required type of the attributes ?

**Comment by simpleidserver** [comment]
There are two methods to update the name property.

Update the entire name property and pass the required parameters. 
If the sub-properties are not present, they will be removed.

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "value": {
        "name": {
          "formatted": "formatted",
          "middleName": "middleName",
          "familyName": "familyName",
          "givenName": "Given Updated"
        }
      }
    }
  ]
}
```

Use the `path` parameter to update a specific property:

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "path": "name.givenName",
      "value": "Given Updated"
    }
  ]
}
```

**Comment by simpleidserver** [comment]
Hello,

Indeed, there is an issue in the current implementation. This issue will be fixed as soon as possible.

Best regards,

SID

**Comment by simpleidserver** [comment]
After verification, the current implementation appears to be correct.

# First scenario

When the target location (path attribute) is specified and specifies a complex attribute, sub-attributes that are not specified in the value parameter are left unchanged.

**Request** :

```
HTTP PATH : http://localhost/Users/$id$
{
	"Operations": [ { "op": "replace", "path": "name", "value" : { "formatted" : "newformatted", "familyName": "newfamilyName" } } ]
}
```
**Result**

As you can see below, the givenName is not overridden.

```
HTTP GET : http://localhost/Users/$id$

{
	{ "name" : { "formatted": "newFormatted", "familyName": "newfamilyName", "givenName": "givenName" } }
}
```

# Second scenario

 the path parameter is not specified, the value contains a list of one or more attributes that are to be replaced.

**Request** :

```
HTTP PATH : http://localhost/Users/$id$

{
	"Operations": [ { "op": "replace", "value" : { "name": { "formatted" : "newformatted", "familyName": "newfamilyName" } } } ]
}
```

**Result**

```
HTTP GET : http://localhost/Users/$id$

{
	{ "name" : { "formatted": "newFormatted", "familyName": "newfamilyName" } }
}
```

**Comment by vincentmauduit** [comment]
Hello,

Great, understood. I didn't pay attention to this part of the RFC:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/63850913/bbb27e18-94a5-47da-94ac-395f70457047)

Thanks
