### ISSUE TITLE
SCIM Issue after latest update

### ISSUE THREAD

**Issue by Alik2015** [simpleidserver/SimpleIdServer#691]
After latest update am getting an issue with SCIM.  It seems that now the endpoint is https://localhost:5001 instead of https://localhost:5001/master which it use to be.

Here is the screenshot.
As you can see 5001 and 5003 endpoints are working just fine. And am able to login using 5001.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/31630746/a3044a9b-b818-4275-9c76-c33e66147d65)

Something seems to be missing from the configuration maybe?  As usual I am using the MySQL db freshly created using latest migrations.

**Comment by simpleidserver** [comment]
This exception is thrown because the realm has been disabled in the appsettings.json file. 
The configuration file has been corrected in the master branch.
