### ISSUE TITLE
Client Credentials Grant and basic

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#692]
Hello, excuse me,Refer to the following case:
https://github.com/DuendeSoftware/Samples/tree/a3784de886a88302c832d3257dc352ef0bd241ee/IdentityServer/v5/Quickstarts/1_ClientCredentials
When a client uses the "ClientCredentials" mode to request tokens, it uses the client id and key. The packet capture shows that the client id and key are stored in the header:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/93005eb7-620d-45ab-9925-567225724ac8)
But for your M2M project, I caught the packet and found that your project request flow looks like this:
>  POST / master / token HTTP / 1.1
Host: localhost: 5001
Content - Type: application / x - www - form - urlencoded
Content - Length: 77
grant_type = client_credentials & client_id = m2m & client_secret = password & scope = readHTTP / 1.1 200 OK
Content - Type: application / json; charset = utf - 8
Date: Sat, 27 Jan 2024 07:33:23 GMT
Server: Kestrel
Cache - Control: no - store
Pragma: no - cache
Set - Cookie: CurrentRealm = master; path =/
Transfer - Encoding: chunked
{ "expires_in":1800,
"scope":"read",
"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IndzRmVkS2lkIiwieDV0IjoiR042OThqWkNKV055NjlQMXIwNUN3cmw0WXc4IiwidHlwIjoiSldUIn0.eyJhdWQiOlsic2hvcEFwaSJdLCJjbGllbnRfaWQiOiJtMm0iLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTcwNjM0MjYwNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxL21hc3RlciIsImlhdCI6MTcwNjM0MDgwNCwibmJmIjoxNzA2MzQwODA0fQ.Ol9VFPAdjh1L2Kt9LESwZKS6C2Us4D_RCvoqnaO_N97k5JiAMQWpz-CdV6GmVSbnW3FWE36SmQie3wHO50gScOOaPJFTK43qZWO86MtfeXOfktnrY5sN6q164z7XXEDeQ-Ug7wgZPg5FEBSfg0RT2IimlXwz-lyW8E4ZWI6oMEDvXuT03ytdLt0N8txT-6Vwap4SKKOU8zNByBIp9yNcSDMOcGnGUTGzcrHqbZFW1m_vSiVsrmnQCthrNsPllwqJ5a3y1lFSTe7iU4rswlOyQGIoHq8w1M6BvftYIHsld5ODecLFakLVqd0IksEg3y4akhDSBUbuPt7qJXT4coCGPQ",
"refresh_token":"a43c786e-681a-422b-bc8c-889abaa27a57",
"token_type":"Bearer"}

The client id and key are not transmitted as Authorization: Basic client id: key in the header.

**Comment by simpleidserver** [comment]
It is normal for the Authorization header not to be used to authenticate the client because, by default, when a machine client is created, the authentication method is set to 'Client Secret Post.' 
If you wish to use the Authorization header, the authentication method must be set to 'Client Secret Basic.'

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/65aea122-a3fb-45d6-8652-9f06813cfbf7)

**Comment by qq1176914912** [comment]
> It is normal for the Authorization header not to be used to authenticate the client because, by default, when a machine client is created, the authentication method is set to 'Client Secret Post.' If you wish to use the Authorization header, the authentication method must be set to 'Client Secret Basic.'
> 
> ![image](https://private-user-images.githubusercontent.com/10213388/300210783-65aea122-a3fb-45d6-8652-9f06813cfbf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTE4MTQsIm5iZiI6MTcwNjQ5MTUxNCwicGF0aCI6Ii8xMDIxMzM4OC8zMDAyMTA3ODMtNjVhZWExMjItYTNmYi00NWQ2LTg2NTItOWYwNjgxM2NmYmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAxMjUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDQ0ODczY2M0ZTcwOTEyMDQ3M2RkZDczNDQwMTczZTg4NTg1MzA2ZTM2MzcxZTI3YTI5MDA1OTVhYzFlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kr06m67X4SuzRU5rYkrEhF8b-_u60QWl4YriVqyOpSE)

Yes, what you said is right, but I found a problem that when I changed "authentication method "to" Client Secret Basic ", I could still request the token without changing the code of your sample m2m. Does this mean that the code using the original "Client Secret Post" mode can still request the token, is this normal?

**Comment by simpleidserver** [comment]
Indeed, there was a small issue in the OAuthClientSecretBasicAuthenticationHandler; the result was not returned. :(
The issue is now fixed in the master branch.

**Comment by qq1176914912** [comment]
> Indeed, there was a small issue in the OAuthClientSecretBasicAuthenticationHandler; the result was not returned. :( The issue is now fixed in the master branch.

Thank you for your help, the problem has been solved.

**Comment by qq1176914912** [comment]
> > It is normal for the Authorization header not to be used to authenticate the client because, by default, when a machine client is created, the authentication method is set to 'Client Secret Post.' If you wish to use the Authorization header, the authentication method must be set to 'Client Secret Basic.'
> > ![image](https://private-user-images.githubusercontent.com/10213388/300210783-65aea122-a3fb-45d6-8652-9f06813cfbf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTE4MTQsIm5iZiI6MTcwNjQ5MTUxNCwicGF0aCI6Ii8xMDIxMzM4OC8zMDAyMTA3ODMtNjVhZWExMjItYTNmYi00NWQ2LTg2NTItOWYwNjgxM2NmYmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAxMjUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDQ0ODczY2M0ZTcwOTEyMDQ3M2RkZDczNDQwMTczZTg4NTg1MzA2ZTM2MzcxZTI3YTI5MDA1OTVhYzFlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kr06m67X4SuzRU5rYkrEhF8b-_u60QWl4YriVqyOpSE)
> 
> Yes, what you said is right, but I found a problem that when I changed "authentication method "to" Client Secret Basic ", I could still request the token without changing the code of your sample m2m. Does this mean that the code using the original "Client Secret Post" mode can still request the token, is this normal?  
 

Remember this project we discussed earlier?  
https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/SessionManagement
This project has a function to request a refresh token, which is done in basic mode:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/650fc773-5fb6-4f4a-a133-cce3a6911cf3)

It can be used normally before you fix the problem I mentioned, but it cannot be used after you fix it. I guess because this issue has been fixed, the project itself uses "Client secret post" for login, so there is an error when using basic request to refresh the token, the error is as follows:
""error": "invalid_client",
"error_description": "bad client credential""
Can you try it out, if there is a problem, should I change the basic mode of this project to post or should your project processing logic change?

**Comment by simpleidserver** [comment]
Hello,

This exception is thrown because the function RequestRefreshTokenAsync is using a different authentication method than the one configured in the client.
Could you please check if they are different and update the RequestRefreshTokenAsync to use the correct one?

**Comment by qq1176914912** [comment]
> Hello,
> 
> This exception is thrown because the function RequestRefreshTokenAsync is using a different authentication method than the one configured in the client. Could you please check if they are different and update the RequestRefreshTokenAsync to use the correct one?

I found "by caught tokenClient. RequestRefreshTokenAsync" method will increase in the request header, basic logo, because the authentication client Settings is post, so you mean to increase in the request header bearerer rather than basic, But like the project we discussed earlier: ids in "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/SessionManagement", authentication on the client and authentication on the request refresh token do not seem to conflict. So I was wondering if the authentication method for requesting a refresh token is different from the authentication method set by the client, and I looked it up on the web and everyone seemed to be using basic instead of bearer.

**Comment by simpleidserver** [comment]
The authentication method utilized by the token endpoint is defined by the `token_endpoint_auth_method` property. 
Further information about this property can be found in the official RFC: https://datatracker.ietf.org/doc/html/rfc7591.

It is peculiar that the client_secret is transmitted in the HTTP body by the library. 
According to the RFC, this practice is not recommended, as it poses a security risk: https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1.

```
Including the client credentials in the request-body using the two parameters is NOT RECOMMENDED and SHOULD be limited to clients unable to directly utilize the HTTP Basic authentication scheme
```

It is understandable that your code is not functioning correctly because the authorization header is incorrect. It should resemble something like this:

```
const string clientId = "clientid";
const string clientSecret = "clientsecret";
string basicCredentials = Convert.ToBase64String(ASCIIEncoding.ASCII.GetBytes(clientId + ":" + clientSecret));
tokenRequest.Headers.Authorization = new AuthenticationHeaderValue("Basic", basicCredentials);
```
