### ISSUE TITLE
Attributes are missing in SearchSCIMRepresentationsParameter

### ISSUE THREAD

**Issue by shachar-radoshinsky-sp** [simpleidserver/SimpleIdServer#70]
Hi,
Is it possible to add to the SearchSCIMRepresentationsParameter the Attributes that are sent ?

I can see them inside SearchSCIMResourceParameter but not in SearchSCIMRepresentationsParameter

**Comment by simpleidserver** [comment]
Hello,

The *attributes* property is not used by the Persistence layer, therefore this property is not passed to *SearchSCIMRepresentationsParameter*.
Can-you explain why you want to pass this property ?

**Comment by shachar-radoshinsky-sp** [comment]
We actually migrated from a different implementation to yours and we used the attributes field to retrieve additional fields from the db query.

**Comment by simpleidserver** [comment]
I made some modifications in the branch *release/1.2.0* to pass the "attributes" property into the class "SearchSCIMRepresentationsParameter".
It can be used by the persistence layer in order to get specific fields.

**Comment by shachar-radoshinsky-sp** [comment]
Looks great, thanks a lot.
