### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#702]
1、I have two demo sites here:
https://webauthn.io/
https://demo.quado.io/
Their webauthn calls Windows hello, while yours does not.
Do you need some extra configuration, or do you need to change the code?
2、What is "Authentication attempt today" on the home page of 5002 address, and what can be done to increase its number?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/a87f7930-b1ed-46bb-9360-a4743fd870e4)
3、I noticed that all the interfaces in your project use the "CheckAccessToken" method to authenticate the token instead of adding "[Authorize]" above the interface. In my testing, I found that "CheckAccessToken" doesn't seem to decide on the expiration time of the token: I created a test interface myself, and I found that I used expired tokens to access the interface "CheckAccessToken" that still passed validation

**Comment by simpleidserver** [comment]
**Windows hello**

In the popup, could you please click on the button labeled `other device` and check if the `windows hello` option is available.
We are using the `Fido2.AspNet` library, and according to their documentation, this authentication method must be supported.

**Authentication attempt**

The event `UserLoginFailureEvent` was not consumed by the IdServerEventConsumer. 
This issue has been resolved in the `master` branch. If an anonymous user attempts to submit incorrect credentials, the Counter will now be incremented.

**CheckAccessToken**

There was indeed an issue in the `ReadSelfIssuedJsonWebToken` function within the `JwtBuilder` class. The `ValidateLifetime` property was set to false.

To validate the access token, we are not utilizing the `AuthorizeAttribute` but rather the `CheckAccessToken` function, for several reasons : 

* Performance reason : The Microsoft.AspNetCore.Authentication.JwtBearer library fetches the Json Web Key from the /jwks URL, but this additional call is unnecessary as the Jwks can be directly retrieved from our store.
* Caching problem :  When the JWKS is rotated, the keys cached by JwtBearer must be refreshed.
* Custom error : To remain compliant with various standards, we return different error messages when the access token is expired or invalid.

**Comment by qq1176914912** [comment]
> **Windows hello**
> 
> In the popup, could you please click on the button labeled `other device` and check if the `windows hello` option is available. We are using the `Fido2.AspNet` library, and according to their documentation, this authentication method must be supported.
> 
> **Authentication attempt**
> 
> The event `UserLoginFailureEvent` was not consumed by the IdServerEventConsumer. This issue has been resolved in the `master` branch. If an anonymous user attempts to submit incorrect credentials, the Counter will now be incremented.
> 
> **CheckAccessToken**
> 
> There was indeed an issue in the `ReadSelfIssuedJsonWebToken` function within the `JwtBuilder` class. The `ValidateLifetime` property was set to false.
> 
> To validate the access token, we are not utilizing the `AuthorizeAttribute` but rather the `CheckAccessToken` function, for several reasons :
> 
> * Performance reason : The Microsoft.AspNetCore.Authentication.JwtBearer library fetches the Json Web Key from the /jwks URL, but this additional call is unnecessary as the Jwks can be directly retrieved from our store.
> * Caching problem :  When the JWKS is rotated, the keys cached by JwtBearer must be refreshed.
> * Custom error : To remain compliant with various standards, we return different error messages when the access token is expired or invalid.

Thank you very much for your reply, problem solved.
