### ISSUE TITLE
Email and profile picture problems

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#707]
hello.
1、I see that if he passes the verification by binding a mobile phone, the field of "phone_number_verified" will appear in the claim, but after I bind the mailbox, he has no related field. So what should I do if I want to know whether the mailbox passes the verification?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/90a5f9e9-ec4b-4ebc-bcc4-c51da21d2c3d)
2、As for the avatar, I see that there is a field about picture in the claim. How does this address come from? If I log in with google, will he get my google avatar address? Does your project now not support setting your own avatar?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/262510ba-c14a-438b-8b41-00c019ba5988)

**Comment by qq1176914912** [comment]
> hello. 1、I see that if he passes the verification by binding a mobile phone, the field of "phone_number_verified" will appear in the claim, but after I bind the mailbox, he has no related field. So what should I do if I want to know whether the mailbox passes the verification? ![image](https://private-user-images.githubusercontent.com/79817742/311100384-90a5f9e9-ec4b-4ebc-bcc4-c51da21d2c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjY1MTksIm5iZiI6MTcwOTg2NjIxOSwicGF0aCI6Ii83OTgxNzc0Mi8zMTExMDAzODQtOTBhNWY5ZTktZWM0Yi00ZWJjLWJjYzQtYzUxZGEyMWQyYzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YTYwMzIzNDNjZTkyMDExZmJmODJiYjI5YTFhZGQxZjI4NjgzY2M4Y2FlMjlmOTVmYzU1NWJkOTBmYjg3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y0F99XzwSr5_o7opT-48MYOFTPIHDavrkN4BNH1PHkI) 2、As for the avatar, I see that there is a field about picture in the claim. How does this address come from? If I log in with google, will he get my google avatar address? Does your project now not support setting your own avatar? ![image](https://private-user-images.githubusercontent.com/79817742/311101150-262510ba-c14a-438b-8b41-00c019ba5988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjY1MTksIm5iZiI6MTcwOTg2NjIxOSwicGF0aCI6Ii83OTgxNzc0Mi8zMTExMDExNTAtMjYyNTEwYmEtYzE0YS00MzhiLThiNDEtMDBjMDE5YmE1OTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZTY1NGI1ZjJmOTNlYzRjNThkN2M4OWVlMWE5NTEyNWRlNTc5YTlmYjBkNWU5NjU1MGQ5NmM5Zjg3NWJhYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgL7Z1dddqAfcOkUw1wtjR5VOQoMooJrAIHPStKOosk)

r the first question, I found it in scope:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/588bddb5-c344-4f8d-b540-e3bc0b60da81)

**Comment by qq1176914912** [comment]
3、When adding a scope, if an error occurs, the error persists regardless of any scope click.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/63f61f94-29ca-440a-b6e9-244b44f85313)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/12465bc8-0ae6-4168-b49b-181a852c0688)

**Comment by qq1176914912** [comment]
4、I found that when I added scope, I accidentally added one more space to the value of "Token claim name". After saving, this value was with space. When I tried to delete the space and save it again, I would get an error: "Token claim name must be unique".
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/e7c61ac2-4abf-4d6b-9311-0602d0d1b192)

**Comment by simpleidserver** [comment]
Hello,

Currently, the end-user lacks the capability to define their picture in SimpleIdServer. 
I have initiated ticket #708 to address and implement this feature.

When a user authenticates with their Google account, it becomes feasible to incorporate their picture into the picture claim. 
To achieve this, you need to add a mapping rule in the Identity Provider by following these steps:

1. Navigate to the Authentications window and select Google.

2. Go to the Mappers tab.

3. Click on the Add mapper button.

4. Select the Property button and proceed to the Next button.

5. Complete the form with the following values and click on the Save button:

| Parameter | Value |
| --------- | ----- |
| Name | Picture |
| Source claim name | picture (https://developers.google.com/identity/openid-connect/openid-connect?hl=fr) |
| User property | picture |

Upon attempting to save these settings, you may encounter the error message "Token claim name must be unique." 
This error is displayed when the scope already contains a mapping rule with the same name.

1. Check if your scope includes mapping rules identical to the ones specified above.
2. If the error persists, provide detailed steps on how to reproduce the error message, including any specific configurations or settings that might contribute to the issue.

**Comment by qq1176914912** [comment]
> Token claim name must be unique

**On the issue of "Token claim name must be unique"**
The operation is as follows:
1. I added a "scope" whose type is "Identity Value" and name is "testscope ".
2. Then add "Mappers" to it and click "Mappers"
Add Mapper, add an Attribute, and set Name and Token claim name to test:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/8b78408c-a11c-4d2a-8d1c-11494e6b5c1e)
3. Then repeat the operation of the second part, this is the "Name must be unique" at the top of the prompt. After the prompt appears, close the window and click the "Add Mapper" button again. Whether I select "Attribute" or "Property", the error message still exists even if I haven't entered anything:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/63480752-b497-4ff5-8850-712d611c76eb)
4. The same thing happens with "API Resources", which basically means that if an error occurs once, even if I close the window and reopen it, the error still persists.
5. Even if I click on "Client" to jump from its "ClientScope" to "Scope", this error still persists:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/b767949a-04d6-480c-bf27-18a32aff8083)
The same goes for the "Token claim name must be unique" error prompt, which persists for as long as an error has occurred.

**Comment by qq1176914912** [comment]
> > Token claim name must be unique
> 
> **On the issue of "Token claim name must be unique"** The operation is as follows:
> 
> 1. I added a "scope" whose type is "Identity Value" and name is "testscope ".
> 2. Then add "Mappers" to it and click "Mappers"
>    Add Mapper, add an Attribute, and set Name and Token claim name to test:
>    ![image](https://private-user-images.githubusercontent.com/79817742/311563519-8b78408c-a11c-4d2a-8d1c-11494e6b5c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDgzMjIsIm5iZiI6MTcxMDE0ODAyMiwicGF0aCI6Ii83OTgxNzc0Mi8zMTE1NjM1MTktOGI3ODQwOGMtYTExYy00ZDJhLThkMWMtMTE0OTRlNmI1YzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYWZmNTcwYWEwNjE1YTQyY2Y0YzRhMDE3NDcwMDZkY2NmZWY5ZTFjMmI2OWI5ZmUxMTAyZWM4ZDU2MDdmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAHEtbAwxVggWr3yJhaHTTT3lAN-GxhFhj71FgUwilo)
> 3. Then repeat the operation of the second part, this is the "Name must be unique" at the top of the prompt. After the prompt appears, close the window and click the "Add Mapper" button again. Whether I select "Attribute" or "Property", the error message still exists even if I haven't entered anything:
>    ![image](https://private-user-images.githubusercontent.com/79817742/311564126-63480752-b497-4ff5-8850-712d611c76eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDgzMjIsIm5iZiI6MTcxMDE0ODAyMiwicGF0aCI6Ii83OTgxNzc0Mi8zMTE1NjQxMjYtNjM0ODA3NTItYjQ5Ny00ZmY1LTg4NTAtNzEyZDYxMWM3NmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NmZmOWI3MGNhOTk1NjM5OWNhZjVkY2QwNjQ3YTZhMmY2Mjc0YmIyMDU0MzQ5ZjJjMzc0YzU4NGVkMWZiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XAJOWtorjOpmYbcJ1ZnHN_-Ld5MBDbvt7NAkEoQ2-II)
> 4. The same thing happens with "API Resources", which basically means that if an error occurs once, even if I close the window and reopen it, the error still persists.
> 5. Even if I click on "Client" to jump from its "ClientScope" to "Scope", this error still persists:
>    ![image](https://private-user-images.githubusercontent.com/79817742/311565977-b767949a-04d6-480c-bf27-18a32aff8083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDgzMjIsIm5iZiI6MTcxMDE0ODAyMiwicGF0aCI6Ii83OTgxNzc0Mi8zMTE1NjU5NzctYjc2Nzk0OWEtMDRkNi00ODBjLWJmMjctMThhMzJhZmY4MDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5MDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjRhNzliOWY4OTJkM2Y4NmZiYmNkZTNmYTE4YjQyZDJjYjg3M2I5ODJmOTc5OGE0ODViNmFmNTQwNzhjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gv90hUR1Z42Y7dnvHqGMvc7KMeOPSFrAYdfPWpgiu-k)
>    The same goes for the "Token claim name must be unique" error prompt, which persists for as long as an error has occurred.

I found that the pop-up window of the "Add client" button also has this problem. As long as there is an error once, the error will always exist. Maybe all pop-ups have this problem.

**Comment by simpleidserver** [comment]
When an error message was displayed in the popup window, it was never removed, even when the window was closed. 
This issue has been fixed in all popup windows.

**Comment by qq1176914912** [comment]
> When an error message was displayed in the popup window, it was never removed, even when the window was closed. This issue has been fixed in all popup windows.

Thank you for your modification.
