### ISSUE TITLE
Add CHANGELOG to repo and into GigHub Release notes

### ISSUE THREAD

**Issue by LazaroOnline** [simpleidserver/SimpleIdServer#712]
As a SimpleIdServer user, when it comes to upgrading, I would much appreciate if the [releases](https://github.com/simpleidserver/SimpleIdServer/releases) had a Changelog so I could see if there are breaking changes or what are the differences and be prepared for it without getting an unexpected surprise in production latter.

You can either have one or multiple `Changelog.md` files in the project and then add that into the github release description.
It would also appreciated if those changes were separated by package or if it specified the packages affected, since my project uses just the "SimpleIdServer.Scim" package at the moment, so I would be able to read just the changes in SCIM.

Here are some changelog style examples:
- [Powershell changelog](https://github.com/PowerShell/PowerShell/tree/master/CHANGELOG) using files in repo.
- [vscode dotnet runtime](https://github.com/search?q=repo%3Adotnet%2Fvscode-dotnet-runtime%20changelog&type=code) using simple changelog files for each project. (personally recommended)
- [dotnet MAUI changelog](https://github.com/dotnet/maui/releases) using github release notes.

**Comment by simpleidserver** [comment]
Indeed, we do not yet have documents listing the changes between different versions. However, starting from version 4.0.3, we have been listing all the tickets included in the various releases. For the upcoming releases, we will endeavor to produce release notes.

Projects : https://github.com/simpleidserver?query=is%3Aclosed&tab=projects
