### ISSUE TITLE
Upgrade to dotnet 8

### ISSUE THREAD

**Issue by LazaroOnline** [simpleidserver/SimpleIdServer#713]
At the moment the latest v4.0.7 uses dotnet 7 for some of the packages like:
"SimpleIdServer.Scim.Swashbuckle", "SimpleIdServer.Scim.Persistence.EF" and others.

Dotnet 7 not being a long-term-supported version, is not available for some scenarios like [AWS Lambdas (not containerized)](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) and other services.
Adding support to dotnet 8 (by upgrading) would enable users of SimpleIdServer using those services that require LTS to upgrade to the latest version instead of being stuck with v4.0.3 that is the latest release for dotnet 6.

**Comment by simpleidserver** [comment]
We are considering migrating to version 8.0 soon, after the release of 4.0.8.

**Comment by simpleidserver** [comment]
@LazaroOnline : The SCIM project version 5.0.0 is available, and it is using .NET 8.0.
