### ISSUE TITLE
SCIM POST /Users/.search Error 500 with 'attributes' property containing null

### ISSUE THREAD

**Issue by LazaroOnline** [simpleidserver/SimpleIdServer#719]
POST /Users/.search returns error 500 with attributes property containing null
Example body:
```json
{ "attributes": [null] }
```

SimpleIdServer\src\Scim\SimpleIdServer.Scim\Extensions\SCIMRepresentationExtensions.cs line 77
```c#
if (attribute.TryContainsGroupingExpression(out SCIMComplexAttributeExpression complexAttributeExpression))
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
attribute was null.

Tested in the current latest of "SimpleIdServer.Scim" v4.0.7

**Comment by simpleidserver** [comment]
This issue will be fixed in the `Release 4.0.8`.

**Comment by simpleidserver** [comment]
The issue is fixed in the `master` branch.

**Comment by LazaroOnline** [comment]
Thanks a lot for the quick support!
