### ISSUE TITLE
Creating ComplexAttribute with decimal value

### ISSUE THREAD

**Issue by shachar-radoshinsky-sp** [simpleidserver/SimpleIdServer#72]
Hello,
I'm trying to add a decimal value to a complex attribute however I see only a list of integers exist.
Is this by design ? can it be added ?

just for reference example of what I meant

When trying to create a new SCIMRepresentation using SCIMRepresentationBuilder
var builder = SCIMRepresentationBuilder.Create(schemas })
.AddComplexAttribute("", c => {
 missing => c.AddDecimalAttribute
}

Thank you.

**Comment by simpleidserver** [comment]
Hi,

We forgot to update the "SCIMRepresentationBuilder" class in order to support the "decimal" and "binary" types.
Changes have been committed in the branch "origin/release/1.2.0".

**Comment by shachar-radoshinsky-sp** [comment]
saw it, thanks
