### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#727]
Hello, I found that your new version has made changes to the database. After I downloaded your latest project, I still used the original database for operation. After the project started, he successfully created a table in the database that did not exist before and modified the data table structure, but there is still a problem:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/6aace80b-dfb8-4781-ba64-e57983c30211)
He will try to insert data into the Realms table, but I already have data, which causes a "duplicate key violation of the unique constraint "PK_Realms", but the data in my original database can't be changed, so what do I do?

**Comment by qq1176914912** [comment]
I annotated "SeedData", which solved the problem, but I wasn't sure if something else would happen.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/18e80b5d-5d4e-40de-b1d7-4d883bba149d)

**Comment by simpleidserver** [comment]
This issue is fixed in the `master` branch :)
