### ISSUE TITLE
New function: #620 :Finds problem

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#728]
On the client, Default acr methods supports multiple methods by default. When multiple methods are selected, only the first method takes effect. The second method does not take effect.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/4a78a783-9361-45c7-9277-413e3e343e15)
For example, I chose pwd and sms:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/142a4482-dd0a-453e-87f6-f5de86ce8afc)
Then I click Log out and go to the login page:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/de7b83c8-056c-46be-be07-9014bbc2d233)
Only pwd login, not sms.
I think it should be changed to single, if it is multiple, the choice of registration method will be confused.

**Comment by simpleidserver** [comment]
The RFC https://openid.net/specs/openid-connect-registration-1_0-19.html provides the following definitions for the default_acr_values. Therefore, it is normal for the first value to be selected if no value is specified in the acr_values request.

```
the default_acr_values is an array of strings that specifies the default acr values that the Authorization Server is being requested to use for processing requests from this client, with the values appearing in order of preference.
```
