### ISSUE TITLE
Remember me expiration date

### ISSUE THREAD

**Issue by lsleishu** [simpleidserver/SimpleIdServer#730]
1. Remember me is achieved through cookies, then what is its validity period?
2. Can this valid time be changed manually? If so, where should it be configured?

**Comment by simpleidserver** [comment]
Hello,

You can set the expiration time of the cookie in the 'Token expiration time' field of your client. 
By default, the value is set to 1800 seconds / 30 minutes.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/1ceb28a8-baff-466a-91c3-efd4d73abeed)
