### ISSUE TITLE
SCIM MongoDB Size must be between 0 and 16793600(16MB)

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#740]
Hello,

we have an issue with the representation group with a lot of users inside:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/231ee8a4-0568-4283-b10b-5a9a1f8fd756)

Do we have to rethink the way we use the group, or is something that can be fix on API side?

Thanks.
Gabriele

**Comment by simpleidserver** [comment]
This issue is fixed in the version 5.0.0
