### ISSUE TITLE
LDAP tutorial

### ISSUE THREAD

**Issue by lsleishu** [simpleidserver/SimpleIdServer#743]
The LDAP tutorial in the official website is different from the LDAP of ldentity server. There are many new configuration items in the LDAP of ldentity server, so I will not use it. Can you update the latest tutorial?

**Comment by simpleidserver** [comment]
Hello,

Indeed, the documentation will be updated in the next release, version 5.0.0.

KR,

SID

**Comment by simpleidserver** [comment]
@lsleishu : The tutorial has been updated in the `master` branch
