### ISSUE TITLE
Can you provide a non-Entity Framework ORM, e.g. one that uses SqlSugar?

### ISSUE THREAD

**Issue by landonzeng** [simpleidserver/SimpleIdServer#744]
Is it possible to provide an ORM that is not Entity Framework, e.g. one that uses SqlSugar, as the current project uses the SqlSugar ORM framework in all places?

**Comment by landonzeng** [comment]
> Hello,
> 
> It is possible to consider using another ORM such as SqlSugar. We will be developing a new NuGet Package to support this ORM in release 5.0.0.
> 
> Best regards,
> 
> SID

Great, thanks for your support in later releases, mainly SqlSugar has been a great help to me in my projects!

**Comment by simpleidserver** [comment]
@landonzeng : I've finished making the modifications in the master branch to support other ORMs such as SQL SUGAR. 
You can find a working version in this sample project: https://github.com/simpleidserver/SimpleIdServer/tree/master/src/IdServer/SimpleIdServer.IdServer.SqlSugar.Startup

KR,

SID

**Comment by landonzeng** [comment]
> @landonzeng : I've finished making the modifications in the master branch to support other ORMs such as SQL SUGAR. You can find a working version in this sample project: https://github.com/simpleidserver/SimpleIdServer/tree/master/src/IdServer/SimpleIdServer.IdServer.SqlSugar.Startup
> 
> KR,
> 
> SID

It's perfect. Thank you very much.
