### ISSUE TITLE
BulkExtensions licencing complexity

### ISSUE THREAD

**Issue by RoystonS** [simpleidserver/SimpleIdServer#748]
I've just discovered that the EFCore.BulkExtensions library, **required** by the SimpleIdServer projects, is not actually provided under a FOSS licence:

https://github.com/borisdj/EFCore.BulkExtensions/blob/master/LICENSE.txt

The page at https://simpleidserver.com/, which compares id server implementations, shows SimpleIdServer as being 'free' and 'Apache 2.0' licenced. However, this is somewhat misleading, as the SimpleIdServer code itself requires the use of a third party package which is not free, and whose licence is incompatible with the Apache 2.0 licence.

I can't see any mention anywhere, on any SimpleIdServer pages, of the fact that the EFCore.BulkExtensions dependency brings with it various licencing encumbrances and costs for commercial use.

I'm not a lawyer, so I'm not sure what the impact is.

- Does SimpleIdServer need to stop using EFCore.BulkExtensions in order to be Apache 2.0 compatible?
- Does SimpleIdServer need to change its licence?
- Should there be a mention somewhere that, whilst the source for SimpleIdServer is free to _look at_, *use* of SimpleIdServer may require a paid-for EFCore.BulkExtensions licence?

**Comment by simpleidserver** [comment]
Hello,

First, thank you for noticing this issue. We will replace the "BulkExtensions" NuGet package with another one to maintain the APACHE 2.0 license.

Kind regards,

SID

**Comment by simpleidserver** [comment]
I made some modifications to the master branch to remove the NuGet package "EFCore.BulkExtensions" from the project. :)

The NuGet package has been replaced by the "linq2db.EntityFrameworkCore" library to execute BULK UPDATE / MERGE.

Kind regards,

Sid

**Comment by RoystonS** [comment]
Great stuff - thank you!

**Comment by simpleidserver** [comment]
This issue is fixed in the version 5.0.0
