### ISSUE TITLE
Turn off the user logout issue

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#750]
Hello, I'm sorry to bother you, but I have a question to ask for your advice. You now have a "Manual action is required to revoke a session" option for the client configuration. The current situation is that when the user clicks to withdraw, it will jump to the 5001 item and then jump back. I don't think is to perform a process (that is, don't jump to 5001), I am in your "CheckSessionController. Cs" method of "EndSession" added at the end of this code:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/0f6e64cd-87bb-45b4-880d-d5191d076888)
Because the front-end logout is more special, I made a judgment, the other are directly triggered 302 jump, so that the effect, when the user clicks exit, will directly exit, rather than jump to 5001, do you think I can do this, or is it safe? If so, can this feature also be added to the client configuration item?

**Comment by simpleidserver** [comment]
An acceptable solution is to redirect the user-agent to the "EndSessionCallback" action when the following conditions are met:

* The property "RedirectToRevokeSessionUI" is set to false.
* The list of "Front Channel Logouts" URLs is empty.

These modifications can be made for the release 5.0.0.

**Comment by simpleidserver** [comment]
The logic described above is implemented in the master branch.
