### ISSUE TITLE
Multiple login failures locked

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#758]
Hello, I am disturbing your current system. When I fail to log in, for example, if I enter the wrong password, I can keep clicking to log in. Is this unreasonable? Will you consider adding a locking function to lock the account after several consecutive failures, and I will need to wait for some time before I can continue to try to log in

**Comment by simpleidserver** [comment]
I made some modifications in the master branch to support this feature. You can edit the following properties in the `Authentications > Lock account` view:

* Account lock time
* Max login attempts
