### ISSUE TITLE
Handling search filter string with ( ) inside

### ISSUE THREAD

**Issue by shachar-radoshinsky-sp** [simpleidserver/SimpleIdServer#76]
Hello,
Inside our Scim endpoint implementation we have a filter property fullPath which represent a windows file location 
if this folder contains () such as "C:\Program Files (x86)\Internet Explorer"
it causes the SplitStringIntoFilters method to split the path at the ) positioncausing a parse error 

I'm not sure how to get around this, any ideas ?

**Comment by simpleidserver** [comment]
Hello,

The issue should be fixed in the branch "origin/release/1.2.0". UTS have been updated to check if filter value can contains '(' and ')'.
You can test the modifications by using the following filter :

`
filePath eq "C:\Program Files (x86)\Internet Explorer"
`

**Comment by shachar-radoshinsky-sp** [comment]
Tested and works, thanks a lot for the quick response
