### ISSUE TITLE
Super administrators, realm administrators, and regular users

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#765]
Hello, excuse me, do you have a plan to realize the permission?
For example, a super administrator and a realm administrator can log in to 5002, but only a super administrator can switch between realms and enter different realms, realm administrators cannot switch realms and can only manage their own realm content, and ordinary users cannot log in to 5002 for administrative operations.
The current situation is that all users are equivalent to the super administrator and can log in to 5002 to operate everything.

**Comment by simpleidserver** [comment]
Hello,

We can develop this feature and include it in the next release. At the moment, we are busy with several tasks:

* Ensuring compliance with the EBSI conformance test (issuer).
* Supporting OpenID federation.

When we have finished both tasks, we can work on it. If you feel comfortable with our codebase, you can also contribute to it :)

Kind regards,

SID

**Comment by qq1176914912** [comment]
> Hello,
> 
> We can develop this feature and include it in the next release. At the moment, we are busy with several tasks:
> 
> * Ensuring compliance with the EBSI conformance test (issuer).
> * Supporting OpenID federation.
> 
> When we have finished both tasks, we can work on it. If you feel comfortable with our codebase, you can also contribute to it :)
> 
> Kind regards,
> 
> SID

Thank you for your reply. I understand.

**Comment by simpleidserver** [comment]
* Change the URL when the realm is changed.
* Assign the client "SIDS-manager" to all the realms.
* Can manage the realms assigned to a user.
* Can manage the realms assigned to a client.
* In the realm view, add a new tab "Roles" and display the list of roles.
* Develop a screen to display a role : 

# Permissions matrix

| Component | Read only  | Manage |
| ------------- | ------------ | --------- |
| Clients         | true            | true |
| Scopes         | true           | false |

* Update the UI group , rename the tab "Roles" to "Client roles" and add a new one "Realm roles"

**Comment by simpleidserver** [comment]
@qq1176914912 : this feature is developed and will be included in the release 5.0.1
