### ISSUE TITLE
FormatException occurring for BooleanAttribute returns "Internal Server Error"

### ISSUE THREAD

**Issue by sw-kosaki** [simpleidserver/SimpleIdServer#77]
Hello, 
we tested with Postman client and we made a Create user request with 'active'(bool) attribute in it. 

We found that if this field has wrong format(for example string different from "true"/"false" or some digit), validation of library returns unexpected "Internal Server Error" with status code 500. 
Can you please check this? 
Thank you in advance.

Request:
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "externalId": "KR",
    "userName": "rz20210120130312@bps.com",
    "active": **"test"**,
    "meta": {
        "resourceType": "User"
    },
    "name": {
        "givenName":"testGivName",
        "familyName":"testFamilyName"
    }
}

Response:
{
    **"status": "500"**,
    "response": {
        "schemas": [
            "urn:ietf:params:scim:api:messages:2.0:Error"
        ],
        "status": "500",
        "scimType": "**internalServerError**",
        "detail": "System.FormatException: String 'test' was not recognized as a valid Boolean.\n   at System.Boolean.Parse(ReadOnlySpan`1 value)\n   at System.Boolean.Parse(String value)\n   at System.Linq.Enumerable.SelectIListIterator`2.ToList()\n  ....
    }
}

**Comment by simpleidserver** [comment]
Hello,

The issue should be fixed in the branch "release/1.2.0".

KR

**Comment by sw-kosaki** [comment]
Hello,
and thank you!

Regards,
Konstantin
