### ISSUE TITLE
Version 5.0.*-* missing on nuget for SimpleIdServer.IdServer.Notification.Fcm package

### ISSUE THREAD

**Issue by jhermsen** [simpleidserver/SimpleIdServer#770]
Just tried creating a project with the latest templates, but the package is missing for SimpleIdServer.IdServer.Notification.Fcm version 5.0.*.

Can you please publish that package or is there a reason it is not published?

**Comment by simpleidserver** [comment]
My apologies, I forgot to publish the NuGet package. The version 5.0.0 has now been published to NuGet.

https://www.nuget.org/packages/SimpleIdServer.IdServer.Notification.Fcm/5.0.0

**Comment by jhermsen** [comment]
No problem that can happen.
You're fast in responding thanks.
