### ISSUE TITLE
Help for required fields value validation

### ISSUE THREAD

**Issue by sw-kosaki** [simpleidserver/SimpleIdServer#78]
Hello,

we аre trying to validate some of required fields for a Create User request(for example subName attributes "givenName" and  "familyName"), but for now without success.

At the moment when we execute a request with given "name" attributes:

    "name": {
        "givenName": "",
        "familyName": ""
    }
    
    or 
    
    "name": {
        "givenName": null,
        "familyName": null
    }
    
    validation is success and a new user with missing required name info is created successfully.
    
    We want to avoid that and protect our services of storing users without required info.
    
    Our configuration looks like this:
    
    .AddComplexAttribute("name", c =>
    {
         c.AddStringAttribute("familyName", description: "The family name", required: true);
         c.AddStringAttribute("givenName", description: "The given name", required: true);
    }, required: true)
    
    Do you mean that this is possible without additional checks in our side?

**Comment by simpleidserver** [comment]
Hello,

The issue should be fixed in the branch "release/1.2.0".

KR

**Comment by sw-kosaki** [comment]
Thank you for this quick fix again!

Regards,
Konstantin
