### ISSUE TITLE
quickstart could load type

### ISSUE THREAD

**Issue by 104652091** [simpleidserver/SimpleIdServer#783]
Unhandled exception. System.TypeLoadException: Could not load type 'SimpleIdServer.Configuration.ConfigurationRecordAttribute' from assembly 'SimpleIdServer.Configuration, Version=5.0.1.0, Culture=neutral, PublicKeyToken=null'.
   at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)

**Comment by simpleidserver** [comment]
Hello,

Could you explain how to reproduce this exception?

Kind regards,
SID

**Comment by 104652091** [comment]
i have solved the issue ,cause the template used the wrong package,SimpleIdServer.IdServer.Notification.Fcm should be 5.0.1 but it's 5.0.0

**Comment by simpleidserver** [comment]
Indeed, the NuGet package SimpleIdServer.IdServer.Notification.Fcm was not published on NuGet. :(

The package has now been uploaded.

Kind regards,
SID
