### ISSUE TITLE
Visit 404

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#786]
Long time no see, I see the last 2 months you update a lot of content, so I try to download your mater branch under the project, but when I started after the two projects, I found that 5001 project, accessed through https://localhost:5001/master shows 404, 404 is also displayed when the 5002 project accesses https://localhost:5002/ directly. It seems that the previous access can not be accessed. Do some parts of the configuration file need to be modified or the access method has changed?

**Comment by qq1176914912** [comment]
The database uses libraries that were recreated by the project

**Comment by qq1176914912** [comment]
Access https://localhost:5002/master/clients:
![image](https://github.com/user-attachments/assets/89100b62-b756-490d-bbb2-ebbd2350fdd9)

**Comment by qq1176914912** [comment]
Problem solving and to regenerate the project, to regenerate the project, you can access, 5002 to allow access to https://localhost:5002/master/clients, not as before to https://localhost:5002/ directly

**Comment by qq1176914912** [comment]
> 访问https://localhost:5002/master/clients： ![图像](https://private-user-images.githubusercontent.com/79817742/365871567-89100b62-b756-490d-bbb2-ebbd2350fdd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTIxMjEsIm5iZiI6MTcyNTk1MTgyMSwicGF0aCI6Ii83OTgxNzc0Mi8zNjU4NzE1NjctODkxMDBiNjItYjc1Ni00OTBkLWJiYjItZWJiZDIzNTBmZGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA3MDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MmNiODQ2YjZmOWE0YzY4ZGE5OGU4ZGExOTQ3YTQwN2Q5OWMwYzgxZTA0NmY4NmQxYWM4OTE1MGIzN2I3NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xq1h6wWD_rviDzsa46s0YxGACr8iUGD4yVKki03UubU)

There's still a problem, sometimes there's a problem, don't know how to fix it, re-create the library or not

**Comment by qq1176914912** [comment]
> > 访问[https://localhost:5002/master/clients：](https://localhost:5002/master/clients%EF%BC%9A) ![图像](https://private-user-images.githubusercontent.com/79817742/365871567-89100b62-b756-490d-bbb2-ebbd2350fdd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTIxMjEsIm5iZiI6MTcyNTk1MTgyMSwicGF0aCI6Ii83OTgxNzc0Mi8zNjU4NzE1NjctODkxMDBiNjItYjc1Ni00OTBkLWJiYjItZWJiZDIzNTBmZGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA3MDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MmNiODQ2YjZmOWE0YzY4ZGE5OGU4ZGExOTQ3YTQwN2Q5OWMwYzgxZTA0NmY4NmQxYWM4OTE1MGIzN2I3NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xq1h6wWD_rviDzsa46s0YxGACr8iUGD4yVKki03UubU)
> 
> There's still a problem, sometimes there's a problem, don't know how to fix it, re-create the library or not

Should I go back to the login page if it's empty or didn't get it?

**Comment by simpleidserver** [comment]
Hello,

Version 5.0.2 has not been published yet, and the version currently in the master branch is not stable. We will provide documentation to explain how to migrate from version 5.0.1 to the latest release
