### ISSUE TITLE
New version 5.0.2 not released yet?

### ISSUE THREAD

**Issue by jhermsen** [simpleidserver/SimpleIdServer#789]
Is it correct that documentation is updated to 5.0.2 and no release and docker image update is available?

Or were there some issues why you had to delay the release?

**Comment by simpleidserver** [comment]
Hello :)

Indeed, the 5.0.2 release is not yet finished. The website has been updated to publish the mobile application in the Android and iOS stores, as well as to obtain the EBSI certification. :)

Apologies for the confusion. :(

The 5.0.2 release will be published once the following tasks are completed:

* Support for OpenID FastFed
* Obtain EBSI certification

Kind regards,
SID

**Comment by jhermsen** [comment]
Ah okay that's clear now thank you
