### ISSUE TITLE
Ask: No entity class dynamic table

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#798]
Hello bother, I have a question I would like to consult, that is, there is a dynamic table, the table name is not fixed, but the internal structure and column name are the same, because there is no entity class, I added a method like this in the StoreDbContext.cs of your project:
![image](https://github.com/user-attachments/assets/9104932c-954b-4ece-877d-fa9b2f469294)
CasbinPolicy because they all have the same internal structure so I use this for data reception.
But to delete and other operations made difficult, other tables are directly can _dbContext. remvoe, but now this table has no entity class, I do not want to continue to use sql statements, because it is not safe, do you have any good method?

**Comment by simpleidserver** [comment]
Hello,

I made a naive implementation in the branch "Ticket798" to support your scenario.
Can-you take a look ? 

https://github.com/simpleidserver/SimpleIdServer/commit/68e538c3957a62a230888a54c55774fdc6580ca6

KR,

SI

**Comment by qq1176914912** [comment]
> Ticket798

Thank you for taking the time to help me write a sample, I tried it, it is indeed dynamic query table.
1. Let me tell you about my side first:
Suppose there are three menus, two of which are to read the contents of the table, and one menu is responsible for setting the other two menus to get the contents of those table names (the table structure and the number of column names are the same, the only difference is the table name).
I read your sample and wrote the code according to it. The difference is that you executed the GetAll interface in Program.cs, but I followed the method you used to invoke the interface on the page before and bound the interface to the corresponding menu. The problem I have found is as follows: The content returned by GetAll is related to the name of the table in which the interface query is executed for the first time. For example, when the project starts the first query table named CasbinP1 with 10 pieces of data, when I call the interface query table named CasbinP2 again for the second time, the content returned is still the content of CasbinP1 table.
2, also ask a question, that is to create a dynamic table, just said three menus, one of the menus is responsible for setting the other two menu binding table, this binding table is casually entered, that is, when the input table name does not exist, this time to dynamically create this table in the database (structure column names are the same, the difference is only the table name is different).
3, I have a question when I look at your code, that is, I see that the 'CustomDataContext' interface you created is similar to the 'StoreDbContext' method, should be able to merge it together, you write this just for our convenience.
If you put the content created by 'CustomDataContext' into 'StoreDbContext', don't you have to write the content of 'services.AddDbContext<CustomDataContext>' in Program.cs?

**Comment by qq1176914912** [comment]
I forgot to mention that I'm using postgresql

**Comment by simpleidserver** [comment]
Hello,

**Question 1**: The modifications made on the branch are only examples and will not be incorporated into SimpleIdServer, as your requirements are specific to your project. The proposed implementation is also not stable and needs further improvement.

**Question 2**: To create tables dynamically, you cannot rely on the EF CORE migration tool. You can either execute raw SQL to create tables or use another ORM library, such as DAPPER, to achieve this.

**Question 3**: Since your requirement is very specific and unrelated to the SimpleIdServer project, I recommend creating a separate library with its own DbContext. Additionally, the two DbContexts cannot be merged because the CustomDataContext has its own lifecycle and cannot depend on Dependency Injection, as the ModelConfiguration is updated at runtime.

I'm interested in your motivation for adding CASBIN to SimpleIdServer. Could you provide more details on your motivation and the use case you aim to support by implementing such features?

KR
SID

**Comment by qq1176914912** [comment]
> Hello,
> 
> **Question 1**: The modifications made on the branch are only examples and will not be incorporated into SimpleIdServer, as your requirements are specific to your project. The proposed implementation is also not stable and needs further improvement.
> 
> **Question 2**: To create tables dynamically, you cannot rely on the EF CORE migration tool. You can either execute raw SQL to create tables or use another ORM library, such as DAPPER, to achieve this.
> 
> **Question 3**: Since your requirement is very specific and unrelated to the SimpleIdServer project, I recommend creating a separate library with its own DbContext. Additionally, the two DbContexts cannot be merged because the CustomDataContext has its own lifecycle and cannot depend on Dependency Injection, as the ModelConfiguration is updated at runtime.
> 
> I'm interested in your motivation for adding CASBIN to SimpleIdServer. Could you provide more details on your motivation and the use case you aim to support by implementing such features?
> 
> KR SID

Thank you for your answer.
I don't know if you know Casbin, but it can be used for very flexible permission management. My original intention is to configure policies in 5002, and then have a unified interface that can invoke corresponding casbin policies. In this way, after configuring policies in 5002, you can directly invoke interfaces to determine whether they meet the corresponding requirements. Of course, casbin supports the configuration of permissions in the form of text on the back end, but if the fixed backend cannot be dynamically configured, and you have a 5002 administration page, so I want to put these things in the 5002 project.
If you are interested, you can take a look at this address: "https://demo.casdoor.com/models" about casbin content
