### ISSUE TITLE
How do I include the userID in the jwt?

### ISSUE THREAD

**Issue by BrunoFelipe-dev** [simpleidserver/SimpleIdServer#819]
I'm trying to add the user id to the jwt token but I can't, I didn't find this option in the manager, I saw in another issue that there is a way to do this, what should I do to include it?

**Comment by simpleidserver** [comment]
To include the UserId in the JWT token, follow these steps:

* Open the `Scopes` screen and edit the profile scope.
* Click on the `Mappers` tab and select `Add Mapper`.
* Choose `User Property` and click the `Next` button.
* Complete the form with the following values and click the `Save` button.

![image](https://github.com/user-attachments/assets/d2129a33-b7c8-4bf1-b099-f2fc84cfb96e)

**Comment by BrunoFelipe-dev** [comment]
Understood works, thank you!
