### ISSUE TITLE
How to update User Claims Programmatically

### ISSUE THREAD

**Issue by BrunoFelipe-dev** [simpleidserver/SimpleIdServer#820]
Hello, I have a question.

How do I update user claims programmatically?

I thought it should be done using the SCIM server, but from what I've seen I can only do this for users created on the SCIM server. When a user registers using the normal flow, such as PWD, for example, I can't update claims from SCIM, such as the profile picture, for example, for this user on the SCIM server. 
Only through the Manager interface can I do this. I'm a bit lost.

**Comment by simpleidserver** [comment]
Hello,

When a user is created in an external resource such as a SCIM server or an LDAP server, the user will not automatically exist in the Identity Server. 
To address this, an `automatic provisioning` workflow must be configured to establish a two-way communication relationship between the Identity Server and the SCIM server.

Once such a workflow is configured, the following scenarios are supported:

* When a user is created in the SCIM server, it will also be created in the Identity Server.
* When a claim (such as a profile picture) is updated in the SCIM server, it will be updated in the Identity Server as well.

For more information about automatic provisioning, please refer to this documentation: [Automatic Identity Provisioning](https://simpleidserver.com/docs/next/iam/automaticidentityprovisioning).

Additionally, user claims can be programmatically updated by executing an HTTP request.
To try this, you can import the attached Postman project and execute the HTTP request under the Manage one user folder.

[SimpleIdServerManagement.postman_collection.json](https://github.com/user-attachments/files/17850893/SimpleIdServerManagement.postman_collection.json)

KR,
SID

**Comment by BrunoFelipe-dev** [comment]
Understood, thank you very much!
